#!/usr/bin/env python3
"""Write the served surface for the shock-reflection act: the reflecting wall.

    python3 sdk/geometry/_generate_dmr_wall.py

WHY THE WALL AND NOT "THE GEOMETRY". This benchmark's body is a boundary, not
a solid: a Mach 10 shock runs down a channel and reflects off the floor. The
one surface a viewer can point at is that floor, and it is the surface the
whole structure on screen is generated by. Anything else would be a picture of
the domain rather than of the body.

WHAT IS MEASURED AND WHAT IS A DISPLAY CHOICE, stated here so the act does not
have to claim more than it can show:

* MEASURED, and gated by the act's geometry stage against the graded run's own
  mesh: where the wall starts (x = 1/6, the shock foot at the start time) and
  how far it runs (to x = 4, the end of the domain). Both are read back out of
  ``verification/runs/DMR_runs/res120/constant/polyMesh/boundary`` by the act
  -- the boundary split between the fixed-inflow strip and the reflecting wall
  is 20 faces and 460 faces at 1/120, which is exactly 1/6 and 23/6.
* A DISPLAY CHOICE, and never quoted as a measurement: the span across the
  channel and the plate's thickness. The calculation is two-dimensional and
  one cell thick, so neither exists in the solved case. They are here to give
  the viewport something with volume to light.

Regenerating this file changes what the server serves. The act names the
SERVED copy and the contract checks it, so a regenerated surface cannot
silently serve a stale body.
"""

from __future__ import annotations

import struct
from pathlib import Path

#: The pre-registered domain (DMR_PREREGISTRATION.md §1), measured.
X_START = 1.0 / 6.0
X_END = 4.0

#: Display only. Neither exists in a one-cell-thick two-dimensional case.
SPAN = 1.0
THICKNESS = 0.04

OUT = Path(__file__).resolve().parent / "dmr_reflecting_wall.stl"


def box(x0, x1, y0, y1, z0, z1):
    """The twelve triangles of an axis-aligned box, outward normals."""
    c = [(x0, y0, z0), (x1, y0, z0), (x1, y1, z0), (x0, y1, z0),
         (x0, y0, z1), (x1, y0, z1), (x1, y1, z1), (x0, y1, z1)]
    quads = [(0, 3, 2, 1), (4, 5, 6, 7), (0, 1, 5, 4),
             (2, 3, 7, 6), (0, 4, 7, 3), (1, 2, 6, 5)]
    tris = []
    for a, b, cc, d in quads:
        tris.append((c[a], c[b], c[cc]))
        tris.append((c[a], c[cc], c[d]))
    return tris


def normal(tri):
    (ax, ay, az), (bx, by, bz), (cx, cy, cz) = tri
    ux, uy, uz = bx - ax, by - ay, bz - az
    vx, vy, vz = cx - ax, cy - ay, cz - az
    nx, ny, nz = uy * vz - uz * vy, uz * vx - ux * vz, ux * vy - uy * vx
    length = (nx * nx + ny * ny + nz * nz) ** 0.5 or 1.0
    return nx / length, ny / length, nz / length


def main() -> int:
    tris = box(X_START, X_END, -THICKNESS, 0.0, 0.0, SPAN)
    with open(OUT, "wb") as fh:
        fh.write(b"reflecting wall, double Mach reflection".ljust(80, b"\0"))
        fh.write(struct.pack("<I", len(tris)))
        for tri in tris:
            fh.write(struct.pack("<3f", *normal(tri)))
            for vertex in tri:
                fh.write(struct.pack("<3f", *vertex))
            fh.write(struct.pack("<H", 0))
    print(f"wrote {OUT} ({len(tris)} triangles)")
    print(f"  wall runs from x = {X_START:.10g} to x = {X_END:.10g}")
    print(f"  span {SPAN:.10g} and thickness {THICKNESS:.10g} are display only")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
