#!/usr/bin/env python3
# =============================================================================
# PER-CASE u_read EMITTER -- PROPOSED CHANGE.  DRAFT (ansys-lane-opus).  NOT A FREEZE.
# UNTRACKED.  NOT COMMITTED.  NO QUEUE ROW.  Gates nothing.
#
# WHAT THIS IS, AND WHY IT IS A NEW FILE AND NOT A DIFF TO THE INSTRUMENT
# ---------------------------------------------------------------------------
# Charter S36.1 records, and I confirmed against the source line by line, that
# NEITHER frozen digitizer instrument persists anything:
#
#   digitize_calibrate.py      (blob 2092c55d..., frozen at 0fab170f)  -- `json`
#                              appears at :69 (import) and :519 (print). No
#                              open(...,"w"), no json.dump anywhere in 600 lines.
#   digitize_calibrate_r2.py   (blob c1d275a2..., frozen at 5714f2c7)  -- `json`
#                              appears at :42 (import) and :196 (print). Same.
#
# So no code path in either instrument can produce the per-case artifact that
# S25.4/S25.7 require and that grade_vmfl008.py:161 names
# (`reference/UREAD_VMFL008.json`).  That is the D5 blocker of S35.4, and by the
# REFERENCE_FORM_CENSUS it is the blocker in front of every figure-only case.
#
# BOTH THOSE FILES ARE FROZEN AND COMMITTED, so rule 6 and S31.3 forbid editing
# them, and S36.1 already ruled the shape of the repair:
#
#     "D5 IS A NEW PER-CASE INSTRUMENT, NOT A RE-RUN.  It imports both frozen
#      files read-only with their hashes asserted ... and edits neither."
#
# This file is that instrument's REUSABLE HALF.  It adds persistence and provenance
# and NOTHING ELSE.  It contains no reading algorithm of its own: every number it
# writes is computed by the frozen bytes, and --parity DEMONSTRATES that (it does
# not assert it) by reproducing the frozen calibrate_r2() report and comparing
# every float bit-for-bit against this file's own path to the same number.
#
# THE SECOND DEFECT IT REPAIRS, ALSO WITHOUT TOUCHING FROZEN BYTES
# ---------------------------------------------------------------------------
# The frozen report dicts are NOT JSON-serialisable.  Both instruments pass
#     default=lambda o: float(o) if isinstance(o, np.floating) else o
# which returns an np.bool_ UNCHANGED (np.bool_ is not np.floating), so the
# encoder re-enters the same object and raises "Circular reference detected".
# That is the rc-1 crash in DIGITIZER/R2/GRADE_R2.err at :196, and its single
# source is plant_detect.band_ok = (np.float64 <= float).  Reproduced in
# isolation.  _jsonable() below normalises numpy scalars EXHAUSTIVELY and
# REFUSES on any type it does not recognise, instead of handing the encoder back
# an object it cannot encode.
#
# WHAT IT DOES NOT DO
# ---------------------------------------------------------------------------
#   * It does not read, open, accept or reference any real plate.  Its ONLY
#     inputs are a PlateSpec (the target's ANSWER-BLIND format per S28.6 -- DPI,
#     axis ranges, tick values, scale type, orientation, line width, aspect) and
#     synthetic curves generated by the frozen family.  There is no parameter
#     through which a raster could enter.  That is what makes it answer-blind,
#     and it is a property of the API, not a promise in a comment.
#   * It does not choose, widen, narrow or transfer any u_read.  S33.1: what
#     transfers between plates is the reader's error IN PIXELS; u_read in data
#     units never transfers.  The caller supplies the case's own spec.
#   * It gates nothing.  S25.7 still requires the case's own freeze afterwards.
#
# MODES
#   --selftest   persistence plants + contract arms.  Pure python, no plates.
#   --parity     bit-for-bit parity against the frozen calibrate_r2() report.
#   --demo       end-to-end emit on a SYNTHETIC demo format that is deliberately
#                no real case's format.  Writes into a directory you name.
#
# BYTE-REPRODUCIBILITY (supervisor ruling 1).  The artifact carries NO wall-clock
# field.  Two emits with identical inputs and an identical emitter produce
# BYTE-IDENTICAL files with an identical sha256, so the freeze pin can be checked
# by re-derivation the way row #56's stdout was.  The emission time lives in
# <artifact>.emitted.json, a sidecar no comparator pins.
#
# ON "NO ARITHMETIC" (supervisor correction, recorded as he phrased it).  This file
# DOES contain the error-residual loop -- `errs.append(q.measure(rd) - truth)` -- a
# transcription of calibrate_r2()'s own loop, and that is arithmetic.  The accurate
# claim is narrower and is the operative one: EVERY REPORTED NUMBER IS THE FROZEN
# GRADER'S.  --parity is what makes that safe, which is why the bit-identical parity
# result is load-bearing evidence and not a formality.
# =============================================================================
import os, sys, json, math, time, hashlib, argparse, tempfile, shutil, subprocess
import numpy as np

# ---- import BOTH frozen instruments read-only (rule 6) ----------------------
_HERE       = os.path.dirname(os.path.abspath(__file__))
_R2_DIR     = os.path.dirname(_HERE)                       # .../DIGITIZER/R2 is a sibling
_R2_DIR     = os.path.join(_R2_DIR, "R2")
_FROZEN_DIR = os.path.dirname(_HERE)                       # .../DIGITIZER
sys.path.insert(0, _FROZEN_DIR)
sys.path.insert(0, _R2_DIR)
import digitize_calibrate as dc                            # frozen R1
import digitize_calibrate_r2 as r2                         # frozen R2

FROZEN_R1_BLOB = "2092c55dd59d36c490b5fc3681bfd36c30d5b49b"
FROZEN_R2_BLOB = "c1d275a29ad67504b22a9d6b15e16e06a5675f86"

# ---- the persistence plant (rule 3).  A KNOWN NON-ZERO, written through the
# production writer and read back FROM DISK.  Distinctive enough that it cannot
# be mistaken for any plausible u_read, and it is planted on EVERY emit, in a
# temp directory, before the real artifact is written.
PERSIST_PLANT = 7.3125e-03          # exactly representable in binary64
PLANT_TAG     = "PERSIST-PLANT-7.3125e-03"

# ---- the placeholder units the frozen classes carry.  S38.2: the frozen
# ValueQuantity.units is the dimensionless "y-data" (digitize_calibrate.py:337),
# and grade_vmfl008.py:247 refuses it.  Refuse it HERE too, at the producer.
PLACEHOLDER_UNITS = ("y-data", "x-data", "", None)


class Refuse(SystemExit):
    def __init__(self, msg):
        SystemExit.__init__(self, 2)
        self.msg = msg


def refuse(msg):
    sys.stderr.write("REFUSE (exit 2): %s\n" % msg)
    raise Refuse(msg)


# =============================================================================
# FROZEN-BLOB ASSERTION.  The numbers this file persists are produced by the
# frozen bytes; if those bytes have moved, the artifact is not what it claims.
# =============================================================================
def _git_blob(path):
    try:
        return subprocess.check_output(["git", "hash-object", path],
                                       cwd=os.path.dirname(path),
                                       stderr=subprocess.DEVNULL).decode().strip()
    except Exception as e:
        refuse("cannot hash frozen instrument %s (%s) -- this file will not emit a "
               "u_read it cannot pin to the bytes that produced it" % (path, e))


def assert_frozen():
    """Refuse unless BOTH frozen instruments are byte-identical to their freezes."""
    p1 = os.path.join(_FROZEN_DIR, "digitize_calibrate.py")
    p2 = os.path.join(_R2_DIR, "digitize_calibrate_r2.py")
    b1, b2 = _git_blob(p1), _git_blob(p2)
    if b1 != FROZEN_R1_BLOB:
        refuse("frozen R1 blob %s != %s (%s)" % (b1, FROZEN_R1_BLOB, p1))
    if b2 != FROZEN_R2_BLOB:
        refuse("frozen R2 blob %s != %s (%s)" % (b2, FROZEN_R2_BLOB, p2))
    return {"r1_path": p1, "r1_blob": b1, "r2_path": p2, "r2_blob": b2}


# =============================================================================
# JSON NORMALISATION -- the S36/GRADE_R2.err crash, repaired OUTSIDE frozen bytes.
# Exhaustive and REFUSING, never a passthrough default= that can loop.
# =============================================================================
def _jsonable(o, _path="$"):
    if isinstance(o, (str, int, float, bool)) or o is None:
        if isinstance(o, float) and not math.isfinite(o):
            refuse("non-finite float at %s: %r -- JSON cannot carry it and a NaN "
                   "u_read term must never reach a gate" % (_path, o))
        return o
    if isinstance(o, np.bool_):          # <-- THE CRASH.  Checked BEFORE np.integer:
        return bool(o)                   #     np.bool_ is not np.integer, but order
    if isinstance(o, np.integer):        #     is stated so a reader need not check.
        return int(o)
    if isinstance(o, np.floating):
        return _jsonable(float(o), _path)
    if isinstance(o, np.ndarray):
        return [_jsonable(v, "%s[%d]" % (_path, i)) for i, v in enumerate(o.tolist())]
    if isinstance(o, dict):
        out = {}
        for k, v in o.items():
            if not isinstance(k, str):
                refuse("non-string JSON key at %s: %r" % (_path, k))
            out[k] = _jsonable(v, "%s.%s" % (_path, k))
        return out
    if isinstance(o, (list, tuple)):
        return [_jsonable(v, "%s[%d]" % (_path, i)) for i, v in enumerate(o)]
    refuse("unserialisable object at %s: type %s -- this emitter REFUSES rather "
           "than handing json an object it cannot encode (that passthrough is the "
           "GRADE_R2.err circular-reference crash)" % (_path, type(o).__name__))


# =============================================================================
# THE ARTIFACT CONTRACT.  Every key here is demanded by a consumer line I read:
#   grade_vmfl008.py:234-235  top-level presence loop (8 keys)
#   :238 dim=="value"   :247 units value-checked   :254 verdict=="PASS"
#   :257 plate_interior_px_h   :262 u_read positive finite
#   :279 UREAD_TERM_KEYS presence   :285-292 pixel_floor == span/interior
#   :287 u_read == max(term_A, half_spread, pixel_floor)
#   :298 statistic "rms" admissible only if max < floor
# =============================================================================
REQUIRED_TOP  = ("dim", "units", "u_read", "statistic", "verdict",
                 "terms", "plate_interior_px_h", "y_span_data_units")
REQUIRED_TERM = ("term_A", "half_spread", "pixel_floor", "max")


def _assert_contract(d, where):
    """Re-assert on the ARTIFACT what the consumer will assert (L-221/L-222: a
    lesson is not applied until every call site asserts it).  Producer-side."""
    for k in REQUIRED_TOP:
        if k not in d:
            refuse("%s: artifact missing required top-level key %r" % (where, k))
    t = d["terms"]
    if not isinstance(t, dict):
        refuse("%s: 'terms' is %s, not an object" % (where, type(t).__name__))
    for k in REQUIRED_TERM:
        if k not in t:
            refuse("%s: 'terms' missing required sub-key %r" % (where, k))
    if d["units"] in PLACEHOLDER_UNITS:
        refuse("%s: units=%r is the frozen instrument's dimensionless placeholder. "
               "S28.2 requires every S25.4 term in the GATED QUANTITY'S OWN UNITS; "
               "the per-case registration must declare the physical unit"
               % (where, d["units"]))
    u = d["u_read"]
    if not isinstance(u, float) or not math.isfinite(u) or not (u > 0.0):
        refuse("%s: u_read is not a positive finite float: %r" % (where, u))
    span = float(d["y_span_data_units"])
    ipx  = float(d["plate_interior_px_h"])
    if not (span > 0.0) or not (ipx > 0.0):
        refuse("%s: span %r / interior_px %r must both be positive" % (where, span, ipx))
    floor = span / ipx
    if abs(float(t["pixel_floor"]) - floor) > 1e-12 * max(1.0, floor):
        refuse("%s: recorded pixel_floor %.17g != span/interior_px %.17g"
               % (where, float(t["pixel_floor"]), floor))
    three = (float(t["term_A"]), float(t["half_spread"]), floor)
    if abs(u - max(three)) > 1e-12 * max(1.0, u):
        refuse("%s: u_read %.17g != max(term_A, half_spread, pixel_floor) %.17g (S25.4)"
               % (where, u, max(three)))
    if d["statistic"] not in ("rms", "max", "p95"):
        refuse("%s: unknown statistic %r" % (where, d["statistic"]))
    if d["statistic"] == "rms" and not (float(t["max"]) < floor):
        refuse("%s: S29.3 rms INADMISSIBLE -- max per-plate %.17g >= pixel floor %.17g"
               % (where, float(t["max"]), floor))
    return True


# =============================================================================
# THE WRITER.  Atomic, then READ BACK FROM DISK AND RE-VERIFIED.
# =============================================================================
def _serialize(payload):
    return json.dumps(_jsonable(payload), indent=2, sort_keys=True).encode("utf-8") + b"\n"


def _sha256_bytes(b):
    return hashlib.sha256(b).hexdigest()


def _sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for blk in iter(lambda: fh.read(65536), b""):
            h.update(blk)
    return h.hexdigest()


def _write_atomic(path, blob):
    d = os.path.dirname(os.path.abspath(path))
    os.makedirs(d, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=d, prefix=".uread_", suffix=".tmp")
    try:
        with os.fdopen(fd, "wb") as fh:
            fh.write(blob)
            fh.flush()
            os.fsync(fh.fileno())
        # mkstemp creates 0600.  A committed lab artifact must be readable like
        # every other file beside it, so the mode is set explicitly rather than
        # inherited from the temp-file API.
        os.chmod(tmp, 0o644)
        os.replace(tmp, path)
    except Exception:
        try: os.unlink(tmp)
        except OSError: pass
        raise


def _deep_equal(a, b, _path="$"):
    """Exact equality, floats included.  json round-trips binary64 exactly in
    py3 (shortest-repr), so a difference here is a real difference, not noise."""
    if type(a) is not type(b):
        if not (isinstance(a, (int, float)) and isinstance(b, (int, float))
                and not isinstance(a, bool) and not isinstance(b, bool)):
            return False, _path
    if isinstance(a, dict):
        if set(a) != set(b):
            return False, _path
        for k in a:
            ok, p = _deep_equal(a[k], b[k], "%s.%s" % (_path, k))
            if not ok:
                return False, p
        return True, _path
    if isinstance(a, list):
        if len(a) != len(b):
            return False, _path
        for i, (x, y) in enumerate(zip(a, b)):
            ok, p = _deep_equal(x, y, "%s[%d]" % (_path, i))
            if not ok:
                return False, p
        return True, _path
    if isinstance(a, float) or isinstance(b, float):
        return (float(a) == float(b)), _path
    return (a == b), _path


def _verify_on_disk(path, expected_payload, expected_sha, where):
    """THE VERIFIER.  Everything the plant control is used to prove has power.
    Refuses on: sha drift, unreadable JSON, ANY field difference, contract break."""
    if not os.path.isfile(path):
        refuse("%s: artifact not on disk after write: %s" % (where, path))
    got_sha = _sha256_file(path)
    if got_sha != expected_sha:
        refuse("%s: sha256 on disk %s != written %s" % (where, got_sha, expected_sha))
    try:
        with open(path) as fh:
            back = json.load(fh)
    except Exception as e:
        refuse("%s: artifact on disk is not readable JSON: %s" % (where, e))
    ok, p = _deep_equal(_jsonable(expected_payload), back)
    if not ok:
        refuse("%s: read-back differs from what was written, first at %s" % (where, p))
    _assert_contract(back, where + " (read-back)")
    return back, got_sha


# =============================================================================
# RULE 3 -- THE PLANTED-PERTURBATION CONTROL ON THE PERSISTENCE PATH.
#
# "A zero from a reader not shown able to see a non-zero is not evidence."  The
# persistence path is a reader as much as a writer: it claims a value reached
# disk.  So on EVERY emit, before the real artifact is written:
#
#   ARM A  positive   -- a KNOWN NON-ZERO (PERSIST_PLANT) is written through the
#                        PRODUCTION writer and read back FROM DISK; it must be
#                        recovered EXACTLY, in the u_read field itself and in a
#                        tag field.  If it cannot be seen, the emitter REFUSES.
#   ARM B  planted    -- S35.2: a control that cannot fail has no power, so the
#          FAILURE       FAILURE IS PLANTED.  The artifact on disk is corrupted
#                        (u_read -> 0.0) and the expected sha is RECOMPUTED from
#                        the corrupted file, so the sha arm cannot catch it and
#                        ONLY the field-by-field read-back compare can.  The
#                        verifier MUST refuse.  If it does not, the verifier has
#                        no power and the emitter REFUSES.
#   ARM C  zero       -- a payload carrying u_read = 0.0 must be refused by the
#                        contract check, mirroring the consumer's :262 guard.
#   ARM D  sha        -- a byte appended after the write must be caught by the
#                        sha arm alone.
#
# All four run in a temp directory and touch nothing under the case.
# =============================================================================
def persistence_plant_control(verbose=True):
    tmp = tempfile.mkdtemp(prefix="uread_plant_")
    try:
        base = {
            "dim": "value", "units": "m/s", "statistic": "max", "verdict": "PASS",
            "u_read": PERSIST_PLANT, "plant_tag": PLANT_TAG,
            "plate_interior_px_h": 495.0, "y_span_data_units": 2.5,
            "terms": {"term_A": PERSIST_PLANT, "half_spread": 1.0e-9,
                      "pixel_floor": 2.5 / 495.0, "max": PERSIST_PLANT},
            "nested": {"deep": {"band_ok": np.float64(1.0) <= 2.0}},   # the np.bool_
        }
        # ARM A -- positive: the known non-zero must survive the round trip exactly.
        pa = os.path.join(tmp, "arm_a.json")
        blob = _serialize(base)
        _write_atomic(pa, blob)
        back, sha = _verify_on_disk(pa, base, _sha256_bytes(blob), "PLANT ARM A")
        if back["u_read"] != PERSIST_PLANT or back["plant_tag"] != PLANT_TAG:
            refuse("PLANT ARM A: planted %.17g not recovered from disk (got %r) -- the "
                   "persistence path cannot be shown able to record a known non-zero, "
                   "so nothing it writes is evidence (rule 3)"
                   % (PERSIST_PLANT, back.get("u_read")))
        if back["nested"]["deep"]["band_ok"] is not True:
            refuse("PLANT ARM A: np.bool_ did not round-trip as a JSON true")
        arm_a = True

        # ARM B -- PLANTED FAILURE: corrupt the file, recompute the sha from the
        # corrupted bytes so the sha arm is disarmed, and require a refusal anyway.
        pb = os.path.join(tmp, "arm_b.json")
        _write_atomic(pb, blob)
        with open(pb) as fh:
            damaged = json.load(fh)
        damaged["u_read"] = 0.0
        dblob = json.dumps(damaged, indent=2, sort_keys=True).encode("utf-8") + b"\n"
        _write_atomic(pb, dblob)
        arm_b = False
        try:
            _verify_on_disk(pb, base, _sha256_bytes(dblob), "PLANT ARM B")
        except Refuse:
            arm_b = True
        if not arm_b:
            refuse("PLANT ARM B: the read-back comparison did NOT refuse a corrupted "
                   "artifact whose sha was recomputed -- the verifier has no power "
                   "and its passing on a clean file proves nothing (S35.2)")

        # ARM C -- a zero u_read must be refused by the contract, at the producer.
        zero = dict(base); zero["u_read"] = 0.0
        arm_c = False
        try:
            _assert_contract(_jsonable(zero), "PLANT ARM C")
        except Refuse:
            arm_c = True
        if not arm_c:
            refuse("PLANT ARM C: a zero u_read was accepted by the contract check")

        # ARM D -- sha arm alone: append one byte after a clean write.
        pd = os.path.join(tmp, "arm_d.json")
        _write_atomic(pd, blob)
        with open(pd, "ab") as fh:
            fh.write(b" ")
        arm_d = False
        try:
            _verify_on_disk(pd, base, _sha256_bytes(blob), "PLANT ARM D")
        except Refuse:
            arm_d = True
        if not arm_d:
            refuse("PLANT ARM D: a one-byte append was not caught by the sha arm")

        if verbose:
            print("PERSIST PLANT: A(positive, %.6g recovered from disk)=%s  "
                  "B(planted failure, sha disarmed)=%s  C(zero refused)=%s  "
                  "D(one-byte append caught)=%s"
                  % (PERSIST_PLANT, arm_a, arm_b, arm_c, arm_d))
        return {"planted": PERSIST_PLANT, "arm_A_positive": arm_a,
                "arm_B_planted_failure_refused": arm_b, "arm_C_zero_refused": arm_c,
                "arm_D_sha_append_caught": arm_d}
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


# =============================================================================
# CALIBRATION -- ORCHESTRATION ONLY.  Every arithmetic step below is a call into
# the frozen bytes.  This function owns NO reading algorithm and NO statistic.
# It mirrors digitize_calibrate_r2.calibrate_r2():161-190 with the spec, station
# and quantity supplied per case instead of hard-wired to dc.default_spec().
# --parity proves the mirror is exact.
# =============================================================================
def calibrate_for_spec(spec, kind, statistic, n, x_station=None, sublocator=False,
                       verbose=False):
    if kind not in ("value", "position"):
        refuse("kind must be 'value' or 'position'; got %r" % kind)
    if n < 20:
        refuse("S25.3 requires N >= 20 calibration plates; got %d" % n)
    labels = dc.labels_of(spec)
    if kind == "value":
        if x_station is None:
            refuse("a value read needs an x_station (the abscissa the gate reads at)")
        q = dc.ValueQuantity(spec, float(x_station))
    else:
        q = (r2.PositionQuantityParabolic(spec) if sublocator else dc.PositionQuantity(spec))

    errs, fam0 = [], None
    for i in range(n):
        feat_x, kw = dc.cal_plate_params(i)
        cf = dc.nozzle_curve(spec, feat_x, **kw)
        rd = dc.digitize(dc.render_plate(spec, cf, 0.0), labels)   # AXIS PLANT inside
        if kind == "value":
            errs.append(q.measure(rd) - float(cf(np.array([q.x_station]))[0]))
        else:
            errs.append(q.measure(rd) - feat_x)
        if i == 0:
            fam0 = (cf, feat_x, kw)
    cf0, feat0, kw0 = fam0

    if kind == "value":
        control_render = lambda d: dc.render_plate(spec, cf0, y_displace=d)
        control_truth  = float(cf0(np.array([q.x_station]))[0])
    else:
        control_render = lambda d: dc.render_plate(spec, dc.nozzle_curve(spec, feat0 + d, **kw0), 0.0)
        control_truth  = feat0

    rep = r2._grade_quantity(spec, labels, q, errs, control_render, control_truth,
                             statistic, verbose)      # <-- FROZEN grader, frozen plants

    # shared AXIS negatives, exactly as calibrate_r2:184-190
    lspec = dc.default_spec(x_log=True)
    log_caught = dc._neg_control_refuses(lambda: dc.digitize(
        dc.render_plate(lspec, dc.nozzle_curve(lspec, 5.0), 0.0),
        {**dc.labels_of(lspec), "x_log": False}))
    flip_caught = dc._neg_control_refuses(lambda: dc.digitize(
        dc.render_plate(spec, cf0, 0.0), labels, {"force_pair_flip": True}))
    if not (log_caught and flip_caught):
        rep = dict(rep); rep["verdict"] = "NOT A RESULT"
        rep["reason"] = "shared AXIS negative not caught"
    return rep, {"log_as_linear_caught": log_caught, "planted_flip_caught": flip_caught}


def _spec_record(spec):
    """The ANSWER-BLIND format, serialised in full (S28.6).  Every field here is
    measurable from the plate WITHOUT reading the plotted curve."""
    return {"dpi": spec.dpi, "w_px": spec.w, "h_px": spec.h, "margin_px": spec.margin,
            "interior_w_px": float(spec.bx1 - spec.bx0),
            "interior_h_px": float(spec.by1 - spec.by0),
            "x_range": [spec.x0, spec.x1], "y_range": [spec.y0, spec.y1],
            "x_ticks": list(spec.x_ticks), "y_ticks": list(spec.y_ticks),
            "x_log": spec.x_log, "y_log": spec.y_log,
            "x_orient": spec.x_orient, "y_orient": spec.y_orient,
            "line_width_px": spec.line_width, "tick_len_px": spec.tick_len}


# =============================================================================
# EMIT -- the whole point of the file.
# =============================================================================
def emit_uread(out_path, spec, kind, statistic, units, units_provenance,
               case_id, figure_ref, n=dc.N_CAL, x_station=None, sublocator=False,
               verbose=True):
    """Derive u_read for ONE gated quantity on ONE case's answer-blind format and
    PERSIST it, with provenance, verified from disk.  Returns (payload, sha256).

    THERE IS NO PARAMETER THROUGH WHICH A REAL PLATE CAN ENTER."""
    frozen = assert_frozen()
    plants = persistence_plant_control(verbose=verbose)      # rule 3, on EVERY emit
    if units in PLACEHOLDER_UNITS:
        refuse("units=%r is the frozen placeholder; declare the physical unit "
               "(S28.2, and grade_vmfl008.py:247 refuses it downstream)" % units)
    if not units_provenance:
        refuse("units_provenance is required: name the frozen registration line "
               "that declares this unit.  A unit is a DECLARATION, not a "
               "measurement, and it is recorded as one.")

    rep, axis = calibrate_for_spec(spec, kind, statistic, n, x_station, sublocator,
                                   verbose=verbose)
    if rep.get("verdict") != "PASS":
        refuse("per-case calibration verdict is %r, not PASS -- S25.7 authorises no "
               "digitized gate on an instrument that did not certify (reason: %s)"
               % (rep.get("verdict"), rep.get("reason", "n/a")))

    t = rep["terms"]
    if kind == "value":
        span, ipx, axis_name = (spec.y1 - spec.y0), float(spec.by1 - spec.by0), "y"
    else:
        span, ipx, axis_name = (spec.x1 - spec.x0), float(spec.bx1 - spec.bx0), "x"

    payload = {
        # --- the 8 keys grade_vmfl008.py:234-235 requires ---
        "dim": rep["dim"],
        "units": units,
        "u_read": float(rep["u_read"]),
        "statistic": rep["statistic"],
        "verdict": rep["verdict"],
        "terms": {
            "term_A":      float(t["syn_stat"]),     # S25.4 floor 1 (S29.3 statistic)
            "half_spread": float(t["half_spread"]),  # S25.4 floor 2 (two read-offs)
            "pixel_floor": float(t["pixel_floor"]),  # S25.4 floor 3 (one plate pixel)
            "max":         float(t["syn_max"]),      # S29.3 admissibility datum
            "syn_rms":     float(t["syn_rms"]),
            "syn_p95":     float(t["syn_p95"]),
        },
        # NOTE ON THE KEY NAME: `y_span_data_units` / `plate_interior_px_h` are the
        # names the VMFL008 comparator froze.  For a POSITION read the gated axis is
        # x, so those two keys carry the X span and interior WIDTH.  The unambiguous
        # names are emitted beside them so no reader has to infer it.
        "plate_interior_px_h": ipx,
        "y_span_data_units": float(span),
        "gated_axis": axis_name,
        "gated_span_data_units": float(span),
        "gated_interior_px": ipx,

        # --- provenance (rule 2, S25.2, S25.5, S33.1) ---
        "case_id": case_id,
        "figure_ref": figure_ref,
        "units_provenance": units_provenance,
        "units_is_a_declaration_not_a_measurement": True,
        "answer_blind": {
            "target_raster_read": False,
            "why": "this emitter's only inputs are the answer-blind format (S28.6) "
                   "and synthetic curves from the frozen family; it has no parameter "
                   "that accepts a raster",
            "plate_spec": _spec_record(spec),
        },
        "portable_pixel_terms": {          # S33.1: what transfers is PIXELS
            "term_A_px":      float(t["syn_stat"]) / (span / ipx),
            "half_spread_px": float(t["half_spread"]) / (span / ipx),
            "max_px":         float(t["syn_max"]) / (span / ipx),
            "pixel_floor_px": 1.0,
        },
        "n_plates": int(n),
        "seed0": int(dc.SEED0),
        "sublocator": bool(sublocator),
        "x_station": (None if x_station is None else float(x_station)),
        "plants": {
            "plant_detect": rep["plant_detect"],
            "plant_null":   rep["plant_null"],
            "axis_negatives": axis,
            "persistence":  plants,
        },
        "rms_bias": float(rep["rms_bias"]),
        "frozen_instruments": frozen,
        "emitter": {"path": os.path.abspath(__file__),
                    "sha256": _sha256_file(os.path.abspath(__file__)),
                    "status": "UNTRACKED DRAFT -- NOT FROZEN, NOT COMMITTED"},
        # RULING 1 (supervisor, S3 check 1): NO WALL-CLOCK FIELD LIVES IN THE
        # PAYLOAD.  The artifact's sha256 IS its freeze pin, so byte-reproducibility
        # from identical inputs is the strongest verification available -- it is how
        # register row #56's numbers were checked.  A convenience timestamp destroys
        # that property for nothing, so the emission time goes to a SIDECAR beside
        # the artifact and never into the bytes that are pinned.
        "frozen_report": rep,          # lossless: nothing the frozen bytes said is dropped
        "NOT_A_GATE": "S25.7 unmet until this case's own registration freezes "
                      "prediction, this artifact's sha, band arithmetic and plate hash",
    }

    _assert_contract(_jsonable(payload), "EMIT (pre-write)")
    blob = _serialize(payload)
    sha  = _sha256_bytes(blob)
    _write_atomic(out_path, blob)
    back, disk_sha = _verify_on_disk(out_path, payload, sha, "EMIT")
    # RULING 1: the emission time, and the sha it belongs to, in a SIDECAR.  It is
    # written AFTER the artifact is verified, is never pinned by any comparator,
    # and its absence can never change a number.
    side_path = out_path + ".emitted.json"
    side = {"artifact": os.path.basename(out_path),
            "artifact_sha256": disk_sha,
            "emitted_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "emitter_path": os.path.abspath(__file__),
            "emitter_sha256": payload["emitter"]["sha256"],
            "note": "PROVENANCE SIDECAR -- not part of the artifact, not pinned by "
                    "any comparator, and deliberately excluded from the artifact so "
                    "the artifact is byte-reproducible from its inputs"}
    _write_atomic(side_path, _serialize(side))
    if verbose:
        print("EMIT: %s" % out_path)
        print("      dim=%s statistic=%s u_read=%.17g %s  (term_A=%.6g half=%.6g floor=%.6g max=%.6g)"
              % (back["dim"], back["statistic"], back["u_read"], back["units"],
                 back["terms"]["term_A"], back["terms"]["half_spread"],
                 back["terms"]["pixel_floor"], back["terms"]["max"]))
        print("      sha256 = %s   <-- this is what UREAD_JSON_SHA256 is set to AT THE FREEZE" % disk_sha)
        print("      sidecar: %s (emission time; NOT in the pinned bytes)" % side_path)
    return payload, disk_sha


# =============================================================================
# --parity : DEMONSTRATE (not assert) that this file changes no reading number.
# =============================================================================
def parity(n=None, verbose=True):
    assert_frozen()
    n = n or dc.N_CAL
    frozen_rep = r2.calibrate_r2(n=n, sublocator=False, out_dir=None, verbose=False)
    ok = True
    for kind, key, stat, xs in (("value", "value", "rms", dc.X_STATION),
                                ("position", "position", "max", None)):
        mine, _ = calibrate_for_spec(dc.default_spec(), kind, stat, n,
                                     x_station=xs, sublocator=False, verbose=False)
        theirs = frozen_rep[key]
        same, where = _deep_equal(_jsonable(mine), _jsonable(theirs))
        print("PARITY %-8s frozen u_read=%.17g   this file=%.17g   full-report identical: %s%s"
              % (kind, float(theirs["u_read"]), float(mine["u_read"]), same,
                 "" if same else "  (first difference at %s)" % where))
        ok = ok and same
    print("PARITY: %s" % ("IDENTICAL -- EVERY REPORTED NUMBER IS THE FROZEN GRADER'S. "
                          "(This file does contain the error-residual loop, which is "
                          "arithmetic; this parity result is what makes that safe.)"
                          if ok else "DIVERGENCE ABOVE"))
    return 0 if ok else 1


def selftest(verbose=True):
    ok = True
    f = assert_frozen()
    print("SELFTEST 1 frozen blobs pinned: R1=%s R2=%s" % (f["r1_blob"][:12], f["r2_blob"][:12]))
    p = persistence_plant_control(verbose=True)
    ok = ok and all(p[k] for k in ("arm_A_positive", "arm_B_planted_failure_refused",
                                   "arm_C_zero_refused", "arm_D_sha_append_caught"))
    print("SELFTEST 2 persistence plants: all four arms = %s" % ok)
    # 3) the S36 crash object is now serialisable, and the frozen handler still is not
    crash = {"a": {"b": {"band_ok": np.float64(1.0) <= 2.0}}}
    frozen_handler_fails = False
    try:
        json.dumps(crash, default=lambda o: float(o) if isinstance(o, np.floating) else o)
    except ValueError:
        frozen_handler_fails = True
    mine_ok = json.dumps(_jsonable(crash)) == '{"a": {"b": {"band_ok": true}}}'
    print("SELFTEST 3 GRADE_R2.err crash: frozen handler still raises=%s ; _jsonable encodes=%s"
          % (frozen_handler_fails, mine_ok))
    ok = ok and frozen_handler_fails and mine_ok
    # 4) contract refuses each required key's absence, one at a time
    good = {"dim": "value", "units": "m/s", "u_read": 2.5 / 495.0, "statistic": "max",
            "verdict": "PASS", "plate_interior_px_h": 495.0, "y_span_data_units": 2.5,
            "terms": {"term_A": 1e-9, "half_spread": 1e-9, "pixel_floor": 2.5 / 495.0,
                      "max": 1e-9}}
    _assert_contract(good, "SELFTEST 4 baseline")
    missing_all = True
    for k in REQUIRED_TOP:
        d = dict(good); d.pop(k)
        try:
            _assert_contract(d, "x"); missing_all = False
            print("   NOT REFUSED on missing top-level %r" % k)
        except Refuse:
            pass
    for k in REQUIRED_TERM:
        d = dict(good); d["terms"] = dict(good["terms"]); d["terms"].pop(k)
        try:
            _assert_contract(d, "x"); missing_all = False
            print("   NOT REFUSED on missing terms.%r" % k)
        except Refuse:
            pass
    print("SELFTEST 4 contract refuses every single missing key (%d top + %d term): %s"
          % (len(REQUIRED_TOP), len(REQUIRED_TERM), missing_all))
    ok = ok and missing_all
    # 5) placeholder units and a broken S25.4 max are refused
    bad_u = dict(good); bad_u["units"] = "y-data"
    r5a = False
    try: _assert_contract(bad_u, "x")
    except Refuse: r5a = True
    bad_m = dict(good); bad_m["u_read"] = 1e-9          # < pixel floor -> not the max
    r5b = False
    try: _assert_contract(bad_m, "x")
    except Refuse: r5b = True
    print("SELFTEST 5 refuses placeholder units=%s ; refuses u_read != max-of-three=%s" % (r5a, r5b))
    ok = ok and r5a and r5b
    print("SELFTEST: %s" % ("ALL PASS" if ok else "FAILURES ABOVE"))
    return 0 if ok else 1


# =============================================================================
# --demo : end-to-end on a SYNTHETIC format that is DELIBERATELY no real case's.
# =============================================================================
def demo_spec():
    """A made-up answer-blind format.  y-span 3.3 over a 512x384 figure: it is not
    dc.default_spec()'s registered R2 format and it is not any VMFL plate.  Nothing
    it produces may be transferred to any case (S28.6, S33.1)."""
    return dc.PlateSpec(x_range=(0.0, 1.0), y_range=(0.0, 3.3),
                        x_ticks=[0.0, 0.2, 0.4, 0.6, 0.8, 1.0],
                        y_ticks=[0.0, 0.55, 1.1, 1.65, 2.2, 2.75, 3.3],
                        w=512, h=384, margin=64, dpi=100)


def demo(out_dir, n=20, verbose=True):
    spec = demo_spec()
    out = os.path.join(out_dir, "UREAD_DEMO_SYNTHETIC.json")
    payload, sha = emit_uread(
        out_path=out, spec=spec, kind="value", statistic="rms",
        units="m/s",
        units_provenance="DEMO ONLY -- no registration; this file gates nothing",
        case_id="DEMO-SYNTHETIC-NOT-A-CASE",
        figure_ref="synthetic plate rendered by digitize_calibrate.render_plate; "
                   "no manual figure was opened",
        n=n, x_station=0.4137, verbose=verbose)
    return payload, sha


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description="Per-case u_read emitter (charter S25.4/S25.7, S36.1 blocker).")
    ap.add_argument("--selftest", action="store_true")
    ap.add_argument("--parity", action="store_true")
    ap.add_argument("--demo", metavar="OUT_DIR")
    ap.add_argument("--n", type=int, default=dc.N_CAL)
    a = ap.parse_args()
    try:
        if a.selftest: sys.exit(selftest())
        if a.parity:   sys.exit(parity(n=a.n))
        if a.demo:
            demo(a.demo, n=a.n); sys.exit(0)
    except Refuse:
        sys.exit(2)
    except dc.SystemExit2:
        sys.exit(2)
    ap.print_help(); sys.exit(64)
