#!/bin/bash
# DRIVAER R2 -- assemble and build ONE layered mesh level.
# Registered by verification/campaign/DRIVAER_R2_LAYERED_PREREGISTRATION.md.
#
# THE ONE CHANGE, PROVEN BY DIFF: system/snappyHexMeshDict is replaced by a
# BYTE-IDENTICAL copy of the A1 dict.  Every other system/ file and the STL are
# asserted byte-identical to the graded r1_<level> by cmp.  The .eMesh is
# REGENERATED by surfaceFeatureExtract and then asserted byte-identical to the
# graded one -- a stronger check than copying it.
#
# rc is captured INSIDE this wrapper: `setsid timeout cmd` exits 0 for every
# outcome, so an rc read around the setsid line is meaningless.
# NEVER deletes anything.  REFUSES an existing level root rather than removing it.
set -u
LVL="$1"; CAP_MIN="$2"; PRED_GIB="$3"
D=/home/ubuntu/Certonomous/verification/runs/navier_class/DRIVAER
SRC="$D/r1_$LVL"
A1="$D/LAYERFIX_A1_coarse_relativeSizes"
R="$D/r2_$LVL"

[ -d "$SRC" ] || { echo "REFUSE: no graded source $SRC"; exit 2; }
[ -e "$R" ]   && { echo "REFUSE: $R exists. A guard is satisfied by MOVING the case, never by disabling the guard."; exit 2; }

# ---- Class 3b: PRE-LAUNCH MEMORY REFUSAL --------------------------------------
AVAIL=$(free -g | awk '/^Mem:/{print $7}')
CEIL=$(( AVAIL - 4 ))
echo "MEMORY GATE: free -g available=${AVAIL} GiB, ceiling=available-4=${CEIL} GiB, predicted peak=${PRED_GIB} GiB"
if awk -v p="$PRED_GIB" -v c="$CEIL" 'BEGIN{exit !(p>c)}'; then
  echo "BLOCKED: predicted snappy peak ${PRED_GIB} GiB exceeds available-4 = ${CEIL} GiB. NOTHING LAUNCHED."
  exit 3
fi

mkdir -p "$R/system" "$R/constant/triSurface"

# ---------------------------------------------------------------------------
# TRIAGE FINDING 2026-09-12, r2_fine blockMesh rc=1 -- AND THE REASON THE OLD
# ASSERTION COULD NOT CATCH IT.
#
# r1_fine's system/ was MUTATED by Stage A: controlDict, fvSchemes and fvSolution
# were replaced by SOLVER versions and the mesh-build originals survive beside
# them as *.meshbuild.  r1_coarse and r1_medium were never solved and carry only
# the mesh-build versions.  So `controlDict` means two different files depending
# on the level, and r1_fine's carries `#include "forceCoeffs"`, which is not a
# mesh-build input and was not copied -- blockMesh died on the missing include.
#
# THE OLD ASSERTION WAS `cmp $SRC/system/$f $R/system/$f` IMMEDIATELY AFTER
# COPYING $SRC -> $R.  IT COMPARED THE COPY WITH ITS OWN SOURCE AND COULD NEVER
# FAIL, AT ANY LEVEL, FOR ANY FILE.  That is the same defect class this campaign
# exists to hunt: a check with no failing branch.
#
# THE REPAIR: take *.meshbuild where it exists, and assert the CHOSEN file is
# byte-identical to r1_COARSE's -- a comparison ACROSS levels, which CAN fail and
# which is what "the family differs only in blockMeshDict" actually asserts.
# blockMeshDict is excluded because it is per-level BY DESIGN (h_bg halves).
# ---------------------------------------------------------------------------
REF="$D/r1_coarse"
cp -p "$SRC/system/blockMeshDict" "$R/system/blockMeshDict"
for f in controlDict fvSchemes fvSolution meshQualityDict surfaceFeatureExtractDict; do
  src="$SRC/system/$f"
  [ -f "$SRC/system/$f.meshbuild" ] && src="$SRC/system/$f.meshbuild"
  cp -p "$src" "$R/system/$f"
  cmp -s "$REF/system/$f" "$R/system/$f" || {
    echo "REFUSE: $f taken from $src is NOT byte-identical to the graded r1_coarse/system/$f."
    echo "        The family is supposed to differ only in blockMeshDict."
    exit 2; }
  echo "$f <- $src (byte-identical to r1_coarse/system/$f)" >> "$R/SYSTEM_PROVENANCE.txt"
done
grep -l '#include' "$R/system/"* 2>/dev/null | while read -r g; do
  echo "REFUSE: $g carries an #include; a mesh-build dict must be self-contained"; exit 2
done
grep -q '#include' "$R/system/controlDict" && { echo "REFUSE: controlDict carries an #include -- this is a SOLVER controlDict, not a mesh-build one"; exit 2; }
cp -p "$A1/system/snappyHexMeshDict" "$R/system/snappyHexMeshDict"
cmp -s "$A1/system/snappyHexMeshDict" "$R/system/snappyHexMeshDict" || { echo "REFUSE: snappyHexMeshDict is not byte-identical to the A1 dict"; exit 2; }
cp -p "$SRC/constant/triSurface/drivaer_466.stl" "$R/constant/triSurface/"
cmp -s "$SRC/constant/triSurface/drivaer_466.stl" "$R/constant/triSurface/drivaer_466.stl" || { echo "REFUSE: STL differs"; exit 2; }

# the single registered change, printed as a diff into the run directory
{ echo "# THE ONE CHANGE: r1_$LVL/system/snappyHexMeshDict -> r2_$LVL/system/snappyHexMeshDict"
  diff "$SRC/system/snappyHexMeshDict" "$R/system/snappyHexMeshDict"
  echo "# (empty below == byte-identical to the A1 graded dict)"
  diff "$A1/system/snappyHexMeshDict" "$R/system/snappyHexMeshDict"
} > "$R/THE_ONE_CHANGE.diff" 2>&1

S=$(date +%s)
# ADDENDUM 2026-09-12 (owner directive "i dont want any cap on any run", relayed
# by the cfd-supervisor): NO SPEND CAP TERMINATES ANY RUN, LAB-WIDE.  CAP_MIN is
# retained as a PREDICTION SCORED against the actual at completion under rule 12
# and is written to CAP_SCORED.txt below.  It is not a kill.
# MEMORY DISCIPLINE IS UNAFFECTED and is enforced above: it is a HARDWARE limit,
# not a budget, and the owner lifted caps without adding RAM.  A run still stops
# for PHYSICS and for TRIAGE -- a crash, a divergence, a mesh the solver refuses.
bash /home/ubuntu/Certonomous/cases/navier_class/DRIVAER/mesh/run_build.sh \
    "$LVL" "$R" 1 > "$R/launcher.out" 2>&1
RC=$?                                     # <-- captured INSIDE the wrapper
E=$(date +%s); W=$((E-S))
echo "$RC" > "$R/RUN_RC"
echo "$W"   > "$R/WALL_SECONDS.txt"
awk -v w="$W" 'BEGIN{printf "%.2f\n", w/60.0}' > "$R/CORE_MINUTES.txt"   # serial: ranks=1
{ echo "level=$LVL"; echo "cap_core_min=$CAP_MIN"; echo "predicted_peak_GiB=$PRED_GIB"
  echo "free_g_available_at_launch_GiB=$AVAIL"; echo "ceiling_GiB=$CEIL"
  echo "wall_s=$W"; echo "core_min=$(cat "$R/CORE_MINUTES.txt")"; echo "rc=$RC"
  echo "finished_utc=$(date -u +%FT%TZ)"; } > "$R/RUN_META.txt"
awk -v w="$W" -v c="$CAP_MIN" 'BEGIN{printf "cap_core_min=%s\nactual_core_min=%.2f\nactual_over_predicted=%.3f\nnote=THE CAP IS A PREDICTION SCORED AT COMPLETION (rule 12), NOT A KILL -- addendum 2026-09-12\n", c, w/60.0, (w/60.0)/c}' \
    > "$R/CAP_SCORED.txt"
if [ "$RC" = "137" ] || [ "$RC" = "143" ]; then
  echo "rc=$RC: KILLED FROM OUTSIDE (OOM, operator, or session end). Falsifier class 3d -- NOT A RESULT. This is NOT a cap stop; no spend cap is armed." \
      > "$R/EXTERNAL_KILL.txt"
fi

# eMesh regenerated by the build; assert it matches the graded one
if [ -f "$R/constant/triSurface/drivaer_466.eMesh" ] && [ -f "$SRC/constant/triSurface/drivaer_466.eMesh" ]; then
  if cmp -s "$SRC/constant/triSurface/drivaer_466.eMesh" "$R/constant/triSurface/drivaer_466.eMesh"; then
    echo "eMesh REGENERATED AND BYTE-IDENTICAL to r1_$LVL" >> "$R/RUN_META.txt"
  else
    echo "eMesh REGENERATED BUT DIFFERS from r1_$LVL -- FINDING" >> "$R/RUN_META.txt"
  fi
fi
echo "build_r2_level $LVL done rc=$RC wall=${W}s" >> "$R/launcher.out"
exit $RC
