#!/bin/bash
# DRIVAER R2 -- assemble and build ONE layered mesh level.
# Registered by verification/campaign/DRIVAER_R2_LAYERED_PREREGISTRATION.md.
#
# THE ONE CHANGE, PROVEN BY DIFF: system/snappyHexMeshDict is replaced by a
# BYTE-IDENTICAL copy of the A1 dict.  Every other system/ file and the STL are
# asserted byte-identical to the graded r1_<level> by cmp.  The .eMesh is
# REGENERATED by surfaceFeatureExtract and then asserted byte-identical to the
# graded one -- a stronger check than copying it.
#
# rc is captured INSIDE this wrapper: `setsid timeout cmd` exits 0 for every
# outcome, so an rc read around the setsid line is meaningless.
# NEVER deletes anything.  REFUSES an existing level root rather than removing it.
set -u
LVL="$1"; CAP_MIN="$2"; PRED_GIB="$3"
D=/home/ubuntu/Certonomous/verification/runs/navier_class/DRIVAER
SRC="$D/r1_$LVL"
A1="$D/LAYERFIX_A1_coarse_relativeSizes"
R="$D/r2_$LVL"

[ -d "$SRC" ] || { echo "REFUSE: no graded source $SRC"; exit 2; }
[ -e "$R" ]   && { echo "REFUSE: $R exists. A guard is satisfied by MOVING the case, never by disabling the guard."; exit 2; }

# ---- Class 3b: PRE-LAUNCH MEMORY REFUSAL --------------------------------------
AVAIL=$(free -g | awk '/^Mem:/{print $7}')
CEIL=$(( AVAIL - 4 ))
echo "MEMORY GATE: free -g available=${AVAIL} GiB, ceiling=available-4=${CEIL} GiB, predicted peak=${PRED_GIB} GiB"
if awk -v p="$PRED_GIB" -v c="$CEIL" 'BEGIN{exit !(p>c)}'; then
  echo "BLOCKED: predicted snappy peak ${PRED_GIB} GiB exceeds available-4 = ${CEIL} GiB. NOTHING LAUNCHED."
  exit 3
fi

mkdir -p "$R/system" "$R/constant/triSurface"
for f in blockMeshDict controlDict fvSchemes fvSolution meshQualityDict surfaceFeatureExtractDict; do
  cp -p "$SRC/system/$f" "$R/system/$f"
  cmp -s "$SRC/system/$f" "$R/system/$f" || { echo "REFUSE: $f differs from the graded r1_$LVL"; exit 2; }
done
cp -p "$A1/system/snappyHexMeshDict" "$R/system/snappyHexMeshDict"
cmp -s "$A1/system/snappyHexMeshDict" "$R/system/snappyHexMeshDict" || { echo "REFUSE: snappyHexMeshDict is not byte-identical to the A1 dict"; exit 2; }
cp -p "$SRC/constant/triSurface/drivaer_466.stl" "$R/constant/triSurface/"
cmp -s "$SRC/constant/triSurface/drivaer_466.stl" "$R/constant/triSurface/drivaer_466.stl" || { echo "REFUSE: STL differs"; exit 2; }

# the single registered change, printed as a diff into the run directory
{ echo "# THE ONE CHANGE: r1_$LVL/system/snappyHexMeshDict -> r2_$LVL/system/snappyHexMeshDict"
  diff "$SRC/system/snappyHexMeshDict" "$R/system/snappyHexMeshDict"
  echo "# (empty below == byte-identical to the A1 graded dict)"
  diff "$A1/system/snappyHexMeshDict" "$R/system/snappyHexMeshDict"
} > "$R/THE_ONE_CHANGE.diff" 2>&1

S=$(date +%s)
timeout $(( CAP_MIN * 60 )) bash /home/ubuntu/Certonomous/cases/navier_class/DRIVAER/mesh/run_build.sh \
    "$LVL" "$R" 1 > "$R/launcher.out" 2>&1
RC=$?                                     # <-- captured INSIDE the wrapper
E=$(date +%s); W=$((E-S))
echo "$RC" > "$R/RUN_RC"
echo "$W"   > "$R/WALL_SECONDS.txt"
awk -v w="$W" 'BEGIN{printf "%.2f\n", w/60.0}' > "$R/CORE_MINUTES.txt"   # serial: ranks=1
{ echo "level=$LVL"; echo "cap_core_min=$CAP_MIN"; echo "predicted_peak_GiB=$PRED_GIB"
  echo "free_g_available_at_launch_GiB=$AVAIL"; echo "ceiling_GiB=$CEIL"
  echo "wall_s=$W"; echo "core_min=$(cat "$R/CORE_MINUTES.txt")"; echo "rc=$RC"
  echo "finished_utc=$(date -u +%FT%TZ)"; } > "$R/RUN_META.txt"
if [ "$RC" = "124" ]; then
  echo "CAP EXCEEDED: cap ${CAP_MIN} core-min, elapsed ${W} s. RUN STOPPED -- NOT A RESULT. No new budget." \
      > "$R/CAP_BREACH.txt"
fi

# eMesh regenerated by the build; assert it matches the graded one
if [ -f "$R/constant/triSurface/drivaer_466.eMesh" ] && [ -f "$SRC/constant/triSurface/drivaer_466.eMesh" ]; then
  if cmp -s "$SRC/constant/triSurface/drivaer_466.eMesh" "$R/constant/triSurface/drivaer_466.eMesh"; then
    echo "eMesh REGENERATED AND BYTE-IDENTICAL to r1_$LVL" >> "$R/RUN_META.txt"
  else
    echo "eMesh REGENERATED BUT DIFFERS from r1_$LVL -- FINDING" >> "$R/RUN_META.txt"
  fi
fi
echo "build_r2_level $LVL done rc=$RC wall=${W}s" >> "$R/launcher.out"
exit $RC
