#!/usr/bin/env python3
"""VMFL038-R2 mesh generator -- blockMeshDict from the frozen template.

PREREGISTRATION sec.4 (the isotropic family) and sec.8 requirement 7 (the
value-position placeholder discriminator).

THE ONE SUBSTANTIVE CHANGE FROM R1 LIVES HERE. R1 substituted only __NY__ and pinned
Nx at 180 inside the template, so cells went x2 per level and the near-wall aspect
ratio degraded 4 -> 8 -> 16. R2 substitutes BOTH, so cells go x4 and dx/dy is CONSTANT
at 4 across the whole triple.

WHY THE GUARD IS A VALUE-POSITION DISCRIMINATOR AND NOT A GREP (requirement 7).
R1's launcher checked its substitution with `grep -q '__NY__' && abort`. That test
cannot tell a SURVIVING SUBSTITUTION SITE from THE WORD APPEARING IN A COMMENT, and it
aborts a perfectly good run on the second. This generator instead parses the
`hex (...) (Nx Ny Nz) simpleGrading` line and refuses unless the three block counts are
integers equal to the requested Nx, Ny and 1. It additionally refuses if the template
carries any __TOKEN__ that is not in this generator's own substitution set.

NO `assert` STATEMENT APPEARS IN THIS FILE. `python3 -O` deletes asserts, so an assert
is a control that vanishes under the optimiser (L-332). Every check raises.
"""
import argparse
import os
import re
import sys

SUBS_KEYS = ("__NX__", "__NY__")
TOKEN_RE = re.compile(r"__[A-Z0-9_]+__")
_F = r"([^\s()]+)"
HEX_RE = re.compile(
    r"hex\s*\(\s*0\s+1\s+2\s+3\s+4\s+5\s+6\s+7\s*\)\s*"
    r"\(\s*" + _F + r"\s+" + _F + r"\s+" + _F + r"\s*\)\s*"
    r"simpleGrading\s*\(\s*" + _F + r"\s+" + _F + r"\s+" + _F + r"\s*\)"
)

# The frozen family. Nx/Ny both double per level; dx/dy = 0.18*Ny/(0.01*Nx) = 4 for all.
LEVELS = {"L1": (90, 20), "L2": (180, 40), "L3": (360, 80)}
DELTA_M = 0.01
LENGTH_M = 0.18
TARGET_AR = 4.0


class MeshRefusal(Exception):
    """Raised, never asserted -- see the module docstring."""


def _refuse(msg):
    raise MeshRefusal(msg)


def template_tokens(text):
    """Every __TOKEN__ in the template, comments included."""
    return set(TOKEN_RE.findall(text))


def check_token_subset(text):
    """REFUSE unless every token in the template is one this generator substitutes.

    This is the other half of requirement 7: the value-position check proves the
    substitution TOOK; this proves no token can survive it unnoticed.
    """
    extra = template_tokens(text) - set(SUBS_KEYS)
    if extra:
        _refuse(
            "template carries __TOKEN__(s) outside this generator's substitution set: "
            + ", ".join(sorted(extra))
        )
    return True


def substitute(text, nx, ny):
    out = text.replace("__NX__", str(nx)).replace("__NY__", str(ny))
    return out


def check_value_position(text, nx, ny):
    """VALUE-POSITION DISCRIMINATOR. Parse the block line; refuse on any mismatch.

    Returns (nx, ny, nz) read back out of the generated bytes.
    """
    m = HEX_RE.search(text)
    if m is None:
        _refuse("generated blockMeshDict has no parseable `hex (...) (Nx Ny Nz) simpleGrading` line")
    raw = (m.group(1), m.group(2), m.group(3))
    for r in raw:
        if not re.fullmatch(r"[0-9]+", r):
            _refuse("block count %r is not an integer -- substitution did not take in VALUE POSITION" % (r,))
    got = tuple(int(r) for r in raw)
    want = (int(nx), int(ny), 1)
    if got != want:
        _refuse("block counts in VALUE POSITION are %r, requested %r" % (got, want))
    grad = (m.group(4), m.group(5), m.group(6))
    if grad != ("1", "1", "1"):
        _refuse("grading in VALUE POSITION is %r, the frozen family is uniform (1 1 1)" % (grad,))
    return got


def check_aspect_ratio(nx, ny):
    dx = LENGTH_M / float(nx)
    dy = DELTA_M / float(ny)
    ar = dx / dy
    if abs(ar - TARGET_AR) > 1e-12:
        _refuse(
            "cell aspect ratio dx/dy = %.17g at (Nx=%d, Ny=%d); the frozen family holds it CONSTANT at %.1f "
            "(PREREGISTRATION sec.4.1). This is the defect that killed R1." % (ar, nx, ny, TARGET_AR)
        )
    return dx, dy, ar


def generate(template_path, out_path, nx, ny):
    with open(template_path, "r") as fh:
        text = fh.read()
    check_token_subset(text)
    check_aspect_ratio(nx, ny)
    out = substitute(text, nx, ny)
    counts = check_value_position(out, nx, ny)
    leftover = TOKEN_RE.findall(out)
    if leftover:
        _refuse("tokens survived substitution: " + ", ".join(sorted(set(leftover))))
    with open(out_path, "w") as fh:
        fh.write(out)
    return counts


# ----------------------------------------------------------------------------- selftest
def _selftest(tmpdir):
    npass = [0]
    nfail = [0]

    def check(name, cond):
        if cond:
            npass[0] += 1
            print("  PASS  " + name)
        else:
            nfail[0] += 1
            print("  FAIL  " + name)

    def refuses(name, fn):
        try:
            fn()
        except MeshRefusal as exc:
            check(name + "  [REFUSED: %s]" % str(exc)[:70], True)
            return
        check(name + "  [DID NOT REFUSE]", False)

    here = os.path.dirname(os.path.abspath(__file__))
    tpl = os.path.join(here, "case", "system", "blockMeshDict.template")
    print("MARKER_MESHGEN_SELFTEST_BEGIN")

    # 1. the real template, every frozen level -- must generate and read back
    for lvl, (nx, ny) in sorted(LEVELS.items()):
        outp = os.path.join(tmpdir, "blockMeshDict." + lvl)
        got = generate(tpl, outp, nx, ny)
        check("%s generates and reads back (%d %d 1)" % (lvl, nx, ny), got == (nx, ny, 1))
        with open(outp) as fh:
            body = fh.read()
        check("%s leaves no __TOKEN__ behind" % lvl, not TOKEN_RE.findall(body))

    # 2. cells x4 per level and CONSTANT aspect ratio -- the ordered change, asserted here
    cells = [LEVELS[k][0] * LEVELS[k][1] for k in ("L1", "L2", "L3")]
    check("cells go x4 per level: %r" % (cells,), cells[1] == 4 * cells[0] and cells[2] == 4 * cells[1])
    ars = [check_aspect_ratio(*LEVELS[k])[2] for k in ("L1", "L2", "L3")]
    check("aspect ratio CONSTANT at 4: %r" % (ars,), all(abs(a - 4.0) < 1e-12 for a in ars))

    # 3. MARKER_MESHGEN_VALUEPOS -- the value-position discriminator DRIVEN TO REFUSAL
    print("MARKER_MESHGEN_VALUEPOS")
    refuses(
        "value-position refuses when a token survives in VALUE POSITION",
        lambda: check_value_position(
            "blocks\n(\n    hex (0 1 2 3 4 5 6 7) (__NX__ 20 1) simpleGrading (1 1 1);\n);\n", 90, 20
        ),
    )
    refuses(
        "value-position refuses on the WRONG counts (180 20 1 requested as 90 20 1)",
        lambda: check_value_position(
            "hex (0 1 2 3 4 5 6 7) (180 20 1) simpleGrading (1 1 1)", 90, 20
        ),
    )
    refuses(
        "value-position refuses on non-uniform grading",
        lambda: check_value_position(
            "hex (0 1 2 3 4 5 6 7) (90 20 1) simpleGrading (1 5 1)", 90, 20
        ),
    )
    refuses(
        "value-position refuses when the block line is absent",
        lambda: check_value_position("nothing here at all", 90, 20),
    )
    # and the discriminator's WHOLE POINT: a comment mentioning the token must NOT abort
    ok_txt = (
        "// the launcher substitutes __NX__ and __NY__ here\n"
        "hex (0 1 2 3 4 5 6 7) (90 20 1) simpleGrading (1 1 1)\n"
    )
    got = check_value_position(ok_txt, 90, 20)
    check("a COMMENT naming the token does NOT abort a correct substitution", got == (90, 20, 1))

    # 4. MARKER_MESHGEN_TOKENSET -- token-subset containment DRIVEN TO REFUSAL
    print("MARKER_MESHGEN_TOKENSET")
    refuses(
        "token-subset refuses a template token outside the substitution set",
        lambda: check_token_subset("hex (...) (__NX__ __NY__ __NZ__)"),
    )
    with open(tpl) as fh:
        check("the real template's tokens are a SUBSET of the substitution set", check_token_subset(fh.read()))

    # 5. MARKER_MESHGEN_ASPECT -- the anisotropy guard DRIVEN TO REFUSAL on R1's own family
    print("MARKER_MESHGEN_ASPECT")
    # R1's family was (180,40), (180,80), (180,160) -- dx/dy 4, 8, 16. Its FIRST member
    # is isotropic and is in fact R2's own L2, so the guard must ACCEPT it; its second
    # and third are the anisotropy that killed R1 and the guard must REFUSE both.
    check("aspect guard ACCEPTS R1's L1 (180,40), which is R2's own L2", abs(check_aspect_ratio(180, 40)[2] - 4.0) < 1e-12)
    for ny in (80, 160):
        refuses(
            "aspect guard refuses R1's family member (Nx=180, Ny=%d, dx/dy=%.0f)" % (ny, (0.18 / 180) / (0.01 / ny)),
            lambda ny=ny: check_aspect_ratio(180, ny),
        )

    # 6. MARKER_MESHGEN_MAIN -- the CLI path the launcher actually calls, end to end.
    #    A selftest that exercises only the library functions leaves main()'s own
    #    formatting untested; this one shipped a TypeError there and the smoke, not the
    #    selftest, caught it. It does not recur.
    print("MARKER_MESHGEN_MAIN")
    for lvl in ("L1", "L2", "L3"):
        outp = os.path.join(tmpdir, "cli." + lvl)
        rc = main(["--level", lvl, "--template", tpl, "--out", outp])
        check("main() CLI path returns 0 at %s and writes the file" % lvl, rc == 0 and os.path.exists(outp))
    refuses("main() refuses with neither --level nor --nx/--ny", lambda: main(["--template", tpl, "--out", os.path.join(tmpdir, "x")]))

    # 7. no asserts in this file's own bytes
    import ast as _ast

    with open(os.path.abspath(__file__)) as fh:
        tree = _ast.parse(fh.read())
    nassert = sum(1 for n in _ast.walk(tree) if isinstance(n, _ast.Assert))
    print("MARKER_MESHGEN_AST assert_count=%d" % nassert)
    check("zero `assert` statements in this generator", nassert == 0)

    print("MARKER_MESHGEN_SELFTEST_END pass=%d fail=%d" % (npass[0], nfail[0]))
    return 0 if nfail[0] == 0 else 1


def main(argv):
    ap = argparse.ArgumentParser(description="VMFL038-R2 blockMeshDict generator")
    ap.add_argument("--template")
    ap.add_argument("--out")
    ap.add_argument("--nx", type=int)
    ap.add_argument("--ny", type=int)
    ap.add_argument("--level", choices=sorted(LEVELS))
    ap.add_argument("--selftest", action="store_true")
    args = ap.parse_args(argv)

    if args.selftest:
        import tempfile

        with tempfile.TemporaryDirectory() as td:
            return _selftest(td)

    if args.level:
        nx, ny = LEVELS[args.level]
    else:
        nx, ny = args.nx, args.ny
    if not nx or not ny or not args.template or not args.out:
        _refuse("need --level or (--nx and --ny), plus --template and --out")
    dx, dy, ar = check_aspect_ratio(nx, ny)
    counts = generate(args.template, args.out, nx, ny)
    print(
        "MESH OK  Nx=%d Ny=%d Nz=%d  cells=%d  dx=%.6e dy=%.6e  dx/dy=%.6f  -> %s"
        % (counts[0], counts[1], counts[2], counts[0] * counts[1], dx, dy, ar, args.out)
    )
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main(sys.argv[1:]))
    except MeshRefusal as exc:
        sys.stderr.write("MESH REFUSAL: %s\n" % exc)
        sys.exit(2)
