#!/usr/bin/env python3
"""gen_cone_mesh.py -- parametric axisymmetric-wedge blockMeshDict generator for
Navier-class Case-3, the Taylor-Maccoll supersonic sharp cone (M_inf=2.0, theta_c=15 deg).

TRUE axisymmetric wedge (NOT a planar slab): a planar 2-D cone gives the 2-D WEDGE
(oblique-shock) solution, not the CONICAL Taylor-Maccoll solution -- the whole point of
Case-3.  Axis handled by the canonical OpenFOAM wedge pattern (shared axis vertices,
`empty` axis patch, `wedge` front/back), copied from
tutorials/compressible/rhoCentralFoam/movingCone.

Two meridional blocks, revolved +/- 2.5 deg about the x-axis:
  block 1 (upstream)  x in [XMIN,0],  r in [0, RTOP]     -> lower edge is the AXIS
  block 2 (cone)      x in [0,L],     r in [x*tan(tc), RTOP] -> lower edge is the CONE WALL

Three grid levels for a Celik Fs=1.25 GCI triple; every count scales by the SAME factor
(r = 1.5 linear) so the representative grid size h refines uniformly.

Usage:  python3 gen_cone_mesh.py --level {coarse,medium,fine} --out system/blockMeshDict
Writes only the file the caller names; sends nothing, commits nothing (rules 7, 16).
"""
import argparse, math, sys

# ---- geometry (metres); frozen at pre-registration ----
THETA_C_DEG = 15.0          # cone half-angle
L    = 1.0                  # cone length along axis
XMIN = -0.5                 # upstream buffer (inlet ahead of apex)
RTOP = 1.2                  # farfield radius; > L*tan(beta)=0.649 so the attached shock exits the OUTLET, never the top
WEDGE_HALF_DEG = 2.5        # axisymmetric wedge half-angle (total 5 deg)

# ---- base (medium) cell counts; scaled by MULT per level ----
BASE = dict(nr=90, nx1=40, nx2=110)   # radial, upstream-axial, cone-axial
MULT = {"coarse": 1.0/1.5, "medium": 1.0, "fine": 1.5}

# ---- grading (expansion ratio last/first) ----
GR_RADIAL = 12.0   # cluster toward the lower boundary (cone wall / axis + shock region)
GR_AX1    = 0.25   # block1: cluster toward x=0 (apex/shock origin): last/first < 1
GR_AX2    = 4.0    # block2: cluster toward x=0 (apex)

def ri(x):
    return int(round(x))

def build(level):
    m = MULT[level]
    nr  = ri(BASE["nr"]*m)
    nx1 = ri(BASE["nx1"]*m)
    nx2 = ri(BASE["nx2"]*m)
    tc = math.radians(THETA_C_DEG)
    a  = math.radians(WEDGE_HALF_DEG)
    ca, sa = math.cos(a), math.sin(a)
    rb = L*math.tan(tc)                      # cone base radius

    def f(x, r):   # front (+z)
        return (x, r*ca,  r*sa)
    def b(x, r):   # back  (-z)
        return (x, r*ca, -r*sa)

    verts = [
        (XMIN, 0.0, 0.0),          # 0 axis (P0)
        (0.0,  0.0, 0.0),          # 1 axis (P1 apex)
        f(XMIN, RTOP),             # 2 P3 front
        f(0.0,  RTOP),             # 3 P2 front
        f(L,    rb),               # 4 P4 front
        f(L,    RTOP),             # 5 P5 front
        b(XMIN, RTOP),             # 6 P3 back
        b(0.0,  RTOP),             # 7 P2 back
        b(L,    rb),               # 8 P4 back
        b(L,    RTOP),             # 9 P5 back
    ]

    # Right-handed hex: x1=+axial, x2=+radial, x3=x1 x x2 = +z, so the x3=0 (back, -z)
    # face is listed FIRST.  block1 back (0 1 7 6) then front (0 1 3 2); block2 back
    # (1 8 9 7) then front (1 4 5 3).  Axis verts 0,1 shared -> bottom edge collapses (wedge).
    blocks = [
        ("hex (0 1 7 6 0 1 3 2)", (nx1, nr, 1),
         f"simpleGrading ({GR_AX1} {GR_RADIAL} 1)"),
        ("hex (1 8 9 7 1 4 5 3)", (nx2, nr, 1),
         f"simpleGrading ({GR_AX2} {GR_RADIAL} 1)"),
    ]

    patches = [
        ("axis", "empty", ["(0 1 1 0)"]),
        ("inlet", "patch", ["(0 2 6 0)"]),
        ("outlet", "patch", ["(4 5 9 8)"]),
        ("freestream", "patch", ["(2 3 7 6)", "(3 5 9 7)"]),
        ("cone", "wall", ["(1 4 8 1)"]),
        ("front", "wedge", ["(0 1 3 2)", "(1 4 5 3)"]),
        ("back", "wedge", ["(0 6 7 1)", "(1 7 9 8)"]),
    ]

    out = []
    out.append("/*--------------------------------*- C++ -*----------------------------------*\\")
    out.append("| Navier-class Case-3 Taylor-Maccoll cone -- GENERATED by gen_cone_mesh.py    |")
    out.append(f"| level={level}  nr={nr} nx1={nx1} nx2={nx2}  cells={(nx1+nx2)*nr}             |")
    out.append("\\*---------------------------------------------------------------------------*/")
    out.append("FoamFile\n{\n    version 2.0;\n    format ascii;\n    class dictionary;\n    object blockMeshDict;\n}")
    out.append("scale 1;\n")
    out.append("vertices\n(")
    for i, v in enumerate(verts):
        out.append(f"    ({v[0]:.10g} {v[1]:.10g} {v[2]:.10g})   // {i}")
    out.append(");\n")
    out.append("blocks\n(")
    for hexdef, (a1, a2, a3), grad in blocks:
        out.append(f"    {hexdef} ({a1} {a2} {a3}) {grad}")
    out.append(");\n")
    out.append("edges\n(\n);\n")
    out.append("boundary\n(")
    for name, typ, faces in patches:
        out.append(f"    {name}\n    {{\n        type {typ};\n        faces\n        (")
        for fc in faces:
            out.append(f"            {fc}")
        out.append("        );\n    }")
    out.append(");\n")
    out.append("mergePatchPairs\n(\n);\n")
    out.append("// ************************************************************************* //")
    return "\n".join(out), dict(nr=nr, nx1=nx1, nx2=nx2, cells=(nx1+nx2)*nr, rb=rb)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--level", required=True, choices=list(MULT))
    ap.add_argument("--out", required=True)
    args = ap.parse_args()
    txt, info = build(args.level)
    with open(args.out, "w") as fh:
        fh.write(txt + "\n")
    sys.stderr.write(f"[gen] level={args.level} {info}\n")

if __name__ == "__main__":
    main()
