#!/usr/bin/env python3
"""T23G -- WRITE THE THREE LEVELS' BUILDERS.  BUILDS NOTHING, LAUNCHES NOTHING.

T23G_PREREGISTRATION.md section 2 registers that the ladder is generated by
SCALING EIGHT INTEGERS and by NOTHING ELSE.  This script is the mechanism, and
it is written so that the claim is CHECKED rather than asserted:

  * the six source lines that carry those eight integers are replaced by EXACT
    WHOLE-LINE MATCH, each asserted to appear EXACTLY ONCE in the source;
  * NO REGEX TOUCHES A NUMBER.  `NR_BL_IN, GR_BL_IN = 40, 40.0` puts an integer
    division count and a float GRADING RATIO on one line, so a pattern-based
    substitution would silently rescale the boundary-layer grading and change
    the wall treatment.  Whole-line replacement is the only safe form here;
  * the GRADING RATIOS GR_BL_IN, GR_MID, GR_BL_OUT are IDENTICAL at every level.
    Section 7.4 depends on this: simpleGrading holds each block's TOTAL
    expansion fixed while the divisions double, which is why y+ approximately
    halves per level rather than moving unpredictably;
  * the MEDIUM builder must come out BYTE-IDENTICAL to the source's, and that is
    asserted, not hoped for -- it is the level whose answer is already on disk
    and against which G-REPRO is measured;
  * the derived per-region cell counts are recomputed here and must equal the
    frozen EXPECTED_CELLS before a single file is written.

It REFUSES if a case directory already exists: rule 4's age guard cannot date a
run into a tree somebody else has already touched.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = ("/home/ubuntu/Certonomous/verification/runs/T-family/T23_runs/"
       "T23_P305_U20/build_t23.py")

# The six source lines, VERBATIM, that carry the eight integers.
SRC_LINES = [
    "NR_BL_IN, GR_BL_IN = 40, 40.0     # fluid inner BL: 40 cells, last/first = 40",
    "NR_MID, GR_MID = 40, 1.0          # fluid core band",
    "NR_BL_OUT, GR_BL_OUT = 30, 1.0 / 40.0   # fluid outer BL, contracting to the duct wall",
    "NR_HOUS = 8                       # >= 8 across the 4 mm wall (directive 3.5)",
    "NR_CORE = 24",
    "NZ_UP, NZ_MID, NZ_DOWN = 80, 140, 100",
]

# The eight integers per level: section 2's table, transcribed.
#            BL_IN MID BL_OUT HOUS CORE  Z_UP Z_MID Z_DOWN
INTS = {
    "T23G_C": (20, 20, 15, 4, 12, 40, 70, 50),
    "T23G_M": (40, 40, 30, 8, 24, 80, 140, 100),
    "T23G_F": (80, 80, 60, 16, 48, 160, 280, 200),
}

EXPECTED_CELLS = {                      # section 3.1
    "T23G_C": {"fluid": 8800, "core": 840, "housing": 280},
    "T23G_M": {"fluid": 35200, "core": 3360, "housing": 1120},
    "T23G_F": {"fluid": 140800, "core": 13440, "housing": 4480},
}


def lines_for(level):
    a, b, c, h, co, zu, zm, zd = INTS[level]
    # GR_BL_IN 40.0, GR_MID 1.0 and GR_BL_OUT 1.0/40.0 are IDENTICAL at every
    # level -- only the division counts move (section 7.4).
    return [
        "NR_BL_IN, GR_BL_IN = %d, 40.0     # fluid inner BL, %s level: %d cells, last/first = 40" % (a, level, a),
        "NR_MID, GR_MID = %d, 1.0          # fluid core band" % b,
        "NR_BL_OUT, GR_BL_OUT = %d, 1.0 / 40.0   # fluid outer BL, contracting to the duct wall" % c,
        "NR_HOUS = %d                       # housing, radial (directive 3.5 asks >= 8; the COARSE arm of a ladder is deliberately below it)" % h,
        "NR_CORE = %d" % co,
        "NZ_UP, NZ_MID, NZ_DOWN = %d, %d, %d" % (zu, zm, zd),
    ]


def main():
    src = open(SRC).read()
    src_lines = src.split("\n")

    for ln in SRC_LINES:
        n = src_lines.count(ln)
        if n != 1:
            raise SystemExit("REFUSE: source line appears %d times, expected "
                             "exactly 1: %r" % (n, ln))

    for level in ("T23G_C", "T23G_M", "T23G_F"):
        a, b, c, h, co, zu, zm, zd = INTS[level]
        # The cell counts, DERIVED here from the integers about to be written.
        got = {"fluid": (a + b + c) * (zu + zm + zd),
               "core": co * zm, "housing": h * zm}
        if got != EXPECTED_CELLS[level]:
            raise SystemExit("REFUSE: %s derives %r, the frozen registration "
                             "section 3.1 says %r" % (level, got,
                                                      EXPECTED_CELLS[level]))

        if level == "T23G_M":
            # THE MEDIUM BUILDER IS THE SOURCE BUILDER, BYTE FOR BYTE.  Section
            # 2 registers the MEDIUM column as build_t23.py:65-70 UNALTERED, and
            # the medium level IS the mesh whose answer is already on disk and
            # against which G-REPRO is measured to 1e-6 K.  Byte-identity is the
            # strongest available statement of that and it is ASSERTED here.
            if INTS[level] != (40, 40, 30, 8, 24, 80, 140, 100):
                raise SystemExit("REFUSE: MEDIUM is not build_t23.py's own "
                                 "eight integers")
            text = src
            if text != src:
                raise SystemExit("REFUSE: MEDIUM builder is not byte-identical "
                                 "to %s" % SRC)
            diff = 0
        else:
            out_lines = list(src_lines)
            for old, rep in zip(SRC_LINES, lines_for(level)):
                out_lines[out_lines.index(old)] = rep
            text = "\n".join(out_lines)
            # EXACTLY the six lines that carry the eight integers, and no other.
            diff = sum(1 for x, y in zip(src_lines, out_lines) if x != y)
            if diff != 6:
                raise SystemExit("REFUSE: %s differs from the source builder in "
                                 "%d lines; exactly 6 carry the eight integers"
                                 % (level, diff))
            if len(out_lines) != len(src_lines):
                raise SystemExit("REFUSE: %s changed the builder's line COUNT"
                                 % level)

        d = os.path.join(HERE, level)
        if os.path.exists(d):
            raise SystemExit("REFUSE: %s already exists -- rule 4's age guard "
                             "cannot date a run into a tree already touched" % d)
        os.makedirs(d)
        open(os.path.join(d, "build_t23.py"), "w").write(text)
        print("%s  builder written  lines-differing-from-source=%d  ints=%r  "
              "cells fluid=%d core=%d housing=%d total=%d"
              % (level, diff, INTS[level], got["fluid"], got["core"],
                 got["housing"], sum(got.values())))
    print("\nTHREE BUILDERS WRITTEN.  NOTHING HAS BEEN MESHED AND NOTHING HAS "
          "BEEN LAUNCHED.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
