"""Build the one-page result sheet for the shock-reflection display act.

GENERATES `DMR_SHOCK_REFLECTION_RESULT_SHEET.tex` and compiles it. Every
number in the sheet is substituted from each grid's own graded record; none is
typed into the LaTeX by hand. Edit this generator, never the .tex.

STARTS NO SOLVER. It reads two JSON files and runs pdflatex.

Source of every figure, named in the sheet itself:
  verification/runs/DMR_runs/<grid>/locator_result.json   the graded record
  verification/campaign/DMR_RESULTS.md                    the compute figures

DEMO STANDARD v2 binds this sheet. R1: every number is in a table with a
header, units and an uncertainty column. R5: no run directory name, no gate
name, no tier word, no record filename, no rule number appears anywhere in the
rendered page. R9: no instrument, repair or process talk.
"""

from __future__ import annotations

import json
import math
import shutil
import subprocess
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[3]
RUNS = REPO / "verification" / "runs" / "DMR_runs"
FIGURE = HERE / "figures" / "dmr_density_contours.pdf"
OUT_TEX = HERE / "DMR_SHOCK_REFLECTION_RESULT_SHEET.tex"

T_END = 0.2
TRAVEL = 20.0 * T_END / math.sqrt(3.0)
CRITERION_PCT = 1.0
#: From the cost section of the graded record. Quoted, never re-derived.
ESTIMATE_CORE_MIN = 20.0
USED_CORE_MIN = 2.4

GRIDS = (
    {"key": "res60", "name": "Coarse", "cells": 14400, "shape": "240 by 60"},
    {"key": "res120", "name": "Fine", "cells": 57600, "shape": "480 by 120"},
)


def read(spec: dict) -> dict:
    path = RUNS / spec["key"] / "locator_result.json"
    record = json.loads(path.read_text(encoding="utf-8"))
    gate = record["gateV"]
    error = abs(float(gate["error"]))
    step = float(gate["locator_increment"])
    return {
        **spec,
        "x_measured": float(gate["x_measured"]),
        "x_exact": float(gate["x_exact_at_row"]),
        "error": error,
        "pct": 100.0 * error / TRAVEL,
        "step": step,
        "in_cells": error / step,
        "spacing": float(record["dx"]),
    }


def sci(value: float, digits: int = 5) -> str:
    """Engineering notation with an explicit power of ten, per the output rules."""
    if value == 0:
        return "$0$"
    exponent = math.floor(math.log10(abs(value)))
    mantissa = value / (10.0 ** exponent)
    return f"${mantissa:.{digits}f} \\times 10^{{{exponent}}}$"


def build(rows: list[dict]) -> str:
    fine = next(r for r in rows if r["name"] == "Fine")
    coarse = next(r for r in rows if r["name"] == "Coarse")
    finer_closer = fine["error"] < coarse["error"]
    both_subcell = all(r["in_cells"] < 1.0 for r in rows)

    position_rows = "\n".join(
        f"{r['name']} & {r['cells']:,} & {r['spacing']:.6f} & "
        f"{r['x_measured']:.5f} & {r['x_exact']:.5f} & {sci(r['error'])} & "
        f"{r['pct']:.2f}\\% & $\\pm{r['step']:.5f}$ \\\\"
        for r in rows)

    figure_block = (
        f"\\includegraphics[width=\\linewidth]{{figures/{FIGURE.stem}}}"
        if FIGURE.exists() else
        "\\textbf{The contour figure is not on disk and nothing is drawn in "
        "its place.}")

    return rf"""% ---------------------------------------------------------------
% Shock reflection -- one-page result sheet.
% GENERATED by make_dmr_sheet.py; every number is substituted from the
% graded records, none is typed by hand. Edit the generator, not this file.
% ---------------------------------------------------------------
\documentclass[8pt,a4paper]{{extarticle}}
\usepackage[margin=10mm,top=8mm,bottom=6mm]{{geometry}}
\usepackage{{booktabs,graphicx,xcolor,caption,microtype}}
\usepackage[T1]{{fontenc}}
\usepackage{{lmodern}}
\definecolor{{navy}}{{HTML}}{{1F4E79}}
\definecolor{{boxbg}}{{HTML}}{{FBF6E9}}
\definecolor{{boxrule}}{{HTML}}{{C9A227}}
\captionsetup{{font=small,labelfont=bf,skip=3pt}}
\setlength{{\parindent}}{{0pt}}
\setlength{{\parskip}}{{1pt}}
\pagestyle{{empty}}

\newcommand{{\shead}}[1]{{\vspace{{1pt}}{{\color{{navy}}\bfseries\large #1}}\vspace{{1pt}}\hrule\vspace{{3pt}}}}
\newcommand{{\role}}[1]{{{{\color{{navy}}\bfseries #1.}}}}

\begin{{document}}

{{\color{{navy}}\LARGE\bfseries A shock too steep to reflect cleanly: how well do we track it?}}\\[2pt]
{{A Mach 10 shock meets a wall at $60^\circ$ and cannot reflect off it
attached, so it lifts away and a second shock forms underneath to carry the
turn. Two-dimensional, inviscid, integrated to $t = {T_END}$ on two grids.}}

\shead{{The answer in one line}}

One quantity in this problem is known exactly: the incident shock travels at a
speed the shock relations fix, so its position at any instant is a closed
form. Solved, it sits within {{\bfseries {fine['pct']:.2f}\,\%}} of the
distance it travelled on the fine grid and {coarse['pct']:.2f}\,\% on the
coarse one, against a criterion of {CRITERION_PCT:.0f}\,\% that was written
down before the first mesh was built.
{"The finer grid landed closer than the coarser one, which is what was predicted in advance." if finer_closer else "The finer grid did NOT land closer than the coarser one, which is not what was predicted in advance."}
{"Both differences are smaller than one cell of their own grid." if both_subcell else ""}

\shead{{Table 1 -- Incident shock position at $t = {T_END}$, against the exact solution}}

\begin{{center}}\small
\begin{{tabular}}{{lccccccc}}
\toprule
Grid & Cells & Spacing & Solved & Exact & Difference & Share of & Resolution \\
 & & & position & position & & distance & of the \\
 & [--] & [--] & [--] & [--] & [--] & travelled [\%] & measurement [--] \\
\midrule
{position_rows}
\bottomrule
\end{{tabular}}
\end{{center}}

\vspace{{-7pt}}
{{\footnotesize Lengths are in the problem's own non-dimensional units, in
which the wall runs from $0$ to $4$ and the domain is one unit tall. The
distance the shock travelled between the start and $t = {T_END}$ at a fixed
height is $20t/\sqrt{{3}} = {TRAVEL:.5f}$, and the sixth column is the
difference as a share of it. The final column is the spacing at which the
shock position can be resolved on that grid, which is the grid spacing
itself.}}

\shead{{Table 2 -- Compute}}

\begin{{center}}\small
\begin{{tabular}}{{lcc}}
\toprule
Item & Core-minutes & Basis \\
\midrule
Set aside before running & {ESTIMATE_CORE_MIN:.0f} & fixed with the success criteria \\
Used & {USED_CORE_MIN:.1f} & both grids, meshing and post-processing included \\
Used as a share of what was set aside & {USED_CORE_MIN / ESTIMATE_CORE_MIN:.2f} & --- \\
\bottomrule
\end{{tabular}}
\end{{center}}

\vspace{{-7pt}}
{{\footnotesize A core-minute is one processor working for one minute; all
work here ran on four at once. Cost in currency is not quoted because this
machine cannot read its own billing.}}

\shead{{Density at $t = {T_END}$}}

\begin{{center}}
{figure_block}
\end{{center}}

\vspace{{-4pt}}
{{\footnotesize The main shock arcs from the lower left. Where it leaves the
wall, a second shock and a jet along the wall form beneath it. The fine grid
holds those features tighter than the coarse grid does.}}

\shead{{What was verified, in plain words}}

\role{{Lead Numericist}} The incident shock position was compared against the
exact closed-form solution for the shock speed at the same height on both
grids. On the fine grid it agrees to {fine['pct']:.2f}\,\% of the distance
the shock travelled; on the coarse grid, {coarse['pct']:.2f}\,\%. The
criterion was {CRITERION_PCT:.0f}\,\% and it was fixed before the run, not
chosen afterwards.

\role{{Lead Researcher}} The value of this problem is that it has an exact
answer for one quantity and a hard, sharp, genuinely time-dependent structure
for everything else. Agreeing with the exact part is the necessary condition; it
does not by itself certify the rest of the picture.

\role{{Lead Engineer}} The benchmark was priced at
{ESTIMATE_CORE_MIN:.0f} core-minutes and cost {USED_CORE_MIN:.1f}. The
estimate was the honest one available when it was written and it was high.

\shead{{Caveats}}

\fcolorbox{{boxrule}}{{boxbg}}{{\parbox{{\dimexpr\linewidth-2\fboxsep-2\fboxrule}}{{
\textbf{{The fine structure behind the main shock is shown here and is not
among the quantities measured.}} The second shock and the wall jet beneath the
main front are visible in the picture above. Read them as a picture, not as a
number: no measured value for either is reported on this sheet.\\[2pt]
\textbf{{This is an inviscid calculation.}} There is no turbulence model in it,
so nothing here says anything about turbulence modelling.\\[2pt]
\textbf{{The comparison is against exact theory, not against an experiment.}}
No experimental measurement of this configuration exists to compare the rest
of the structure against.
}}}}

\end{{document}}
"""


def main() -> int:
    rows = [read(spec) for spec in GRIDS]
    OUT_TEX.write_text(build(rows), encoding="utf-8")
    if not shutil.which("pdflatex"):
        print(f"wrote {OUT_TEX}; pdflatex is not on this host, so no page was "
              f"compiled")
        return 1
    for _ in range(2):
        proc = subprocess.run(
            ["pdflatex", "-interaction=nonstopmode", "-halt-on-error",
             OUT_TEX.name],
            cwd=HERE, capture_output=True, text=True)
    for junk in ("aux", "log", "out"):
        (HERE / f"{OUT_TEX.stem}.{junk}").unlink(missing_ok=True)
    pdf = HERE / f"{OUT_TEX.stem}.pdf"
    if proc.returncode != 0 or not pdf.exists():
        print("pdflatex failed; the last 30 lines of its output:")
        print("\n".join(proc.stdout.splitlines()[-30:]))
        return 1
    print(f"wrote {pdf}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
