#!/usr/bin/env python3
"""
DARPA SUBOFF hull + sail + four stern appendages -- MESH CASE BUILDER.
ONE SCRIPT GENERATES THE WHOLE FAMILY, so L1/L2/L3 stay similar (Sanaa's
instruction: "the family is generated from one script so L1/L2/L3 stay
similar").  It emits a complete case directory; it RUNS NOTHING.

FAMILY GENERATING RULE -- inherited verbatim from the SUBOFF_A1 family, so the
two bodies' ladders are comparable:
    base cell x1.5 per coarsening step, nLayers -1, EVERY OCTREE LEVEL IDENTICAL.
Nothing below is tuned toward a target cell count.  The delivered refinement
ratio is MEASURED from the built meshes afterwards, never fitted beforehand.

HALF MODEL, AND WHY IT IS STILL VALID WITH FOUR FINS.
The body is symmetric about the x-y plane (z = 0): the hull is axisymmetric, the
sail lies in that plane, the fins at azimuth 0 and 180 deg lie in it, and the
fins at 90 and 270 deg are mirror images of each other through it.  Sanaa's
sweep is in PITCH, so the free stream also lies in the x-y plane at every alpha.
The z = 0 symmetry therefore holds for the WHOLE sweep and the half model is
exact, not an approximation.
CONSEQUENCE FOR FORCE ACCOUNTING, REGISTERED HERE AND NOT DISCOVERED LATER:
the half model contains HALF of fin000, ALL of fin090, HALF of fin180 and NONE
of fin270.  fin270.stl is deliberately NOT copied into the case -- it lies
entirely outside the half domain and would produce an empty patch.  Total body
forces are 2 x the half-model forces; the hull/fin split doubles the same way.

FIVE CLOSED OVERLAPPING SOLIDS.  hull.stl, sail.stl and the three in-domain fin
STLs each close on themselves; the sail's lower lid and each fin's root lid are
buried inside the hull.  snappyHexMesh's castellation keeps only cells reachable
from locationInMesh, so the UNION survives; no boolean and no coincident-surface
sliver.

ZERO `assert` (L-332).  Refusals are sys.exit(2).
"""
import sys
if not __debug__:
    sys.stderr.write("REFUSED: must not run under python3 -O.\n"); sys.exit(2)
import os, json, argparse, shutil

FT2M = 0.3048
L_M = 14.291667 * FT2M                 # 4.35610 m
SAIL_LE_M, SAIL_TE_M = 3.032986 * FT2M, 4.241319 * FT2M
Y_CAP_M = 1.507813 * FT2M
RMAX_M = (5.0 / 6.0) * FT2M            # 0.254000 m

# stern appendages, BASELINE axial position (Groves Table 3, report page 14)
FIN_H_M = 13.146284 * FT2M             # 4.006987 m, trailing edge
FIN_TIP_R_M = RMAX_M                   # Groves Appendix C: RMAX = 0.833333 ft
FIN_ROOT_R_M = 0.08268545              # measured: hull radius at the TE station
FIN_CHORD_TIP_M = 0.5 * FT2M           # 0.152400 m exactly
FIN_CHORD_ROOT_M = 0.23228535          # c(y_root)
# the three IN-DOMAIN fins of the half model (fin270 is fin090's mirror)
FIN_STLS = ("fin000_upper_rudder", "fin090_horizontal", "fin180_lower_rudder")
FIN_ALL = FIN_STLS + ("fin270_horizontal",)

HDR = """/*--------------------------------*- C++ -*----------------------------------*\\
| SUBOFF hull+sail+4 stern appendages -- generated by
| cases/navier_class/SUBOFF_HULL_SAIL_4STERNPLANES/build_appended_mesh.py
\\*---------------------------------------------------------------------------*/
FoamFile
{{
    version     2.0;
    format      ascii;
    class       {cls};
    object      {obj};
}}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
"""


def w(path, cls, obj, body):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(HDR.format(cls=cls, obj=obj)); f.write(body)


LEVELS = {
    # name : (base cell m, hull lvl, sail lvl, FIN lvl, sail-TE box lvl,
    #         FIN-TE box lvl, junction lvl, nLayers)
    # Base cells and octree levels are the SUBOFF_A1 family's, unchanged, so the
    # hull and sail are resolved identically on both bodies and any difference in
    # the graded forces is attributable to the appendages and not to the ladder.
    "L1": (0.0787, 4, 6, 6, 9, 9, 6, 6),
    "L2": (0.0525, 4, 6, 6, 9, 9, 6, 7),
    "L3": (0.0350, 4, 6, 6, 9, 9, 6, 8),
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--case", required=True)
    ap.add_argument("--level", required=True, choices=sorted(LEVELS))
    ap.add_argument("--geom", required=True)
    ap.add_argument("--xmin", type=float, default=-2.0)
    ap.add_argument("--xmax", type=float, default=9.0)
    ap.add_argument("--rfar", type=float, default=3.0)
    ap.add_argument("--sail-te-trunc-frac", type=float, default=0.995)
    ap.add_argument("--fin-te-trunc-frac", type=float, default=0.98)
    ap.add_argument("--sail-base-mm", type=float, default=1.3109)
    ap.add_argument("--fin-base-tip-mm", type=float, required=True,
                    help="MEASURED fin TE base full thickness at the tip, from "
                         "the geometry manifest -- never assumed")
    ap.add_argument("--fin-base-root-mm", type=float, required=True)
    ap.add_argument("--nproc", type=int, default=16)
    ap.add_argument("--full-width", action="store_true",
                    help="Build the FULL body instead of the z >= 0 half.  ONE "
                         "SWITCH, and it must stay one switch: mirroring about "
                         "z = 0 is nearly free while a mesh is being generated "
                         "and expensive once a family exists.  DEFAULT IS HALF, "
                         "because Sanaa's registered sweep is ALPHA -- velocity "
                         "in the x-y plane, SYMMETRIC about z = 0 -- so a half "
                         "model is exact for everything she asked for and full "
                         "width would double every point of it for data she did "
                         "not ask for.  USE THIS FOR DRIFT.  A drift case on a "
                         "half model does not crash and does not warn: the "
                         "symmetryPlane forces the plane-normal velocity to "
                         "zero, so it returns a converged, plausible, "
                         "SYMMETRISED field that is not the flow anyone asked "
                         "for, and it would clear the completion rule, the "
                         "planted controls and the age guard on its way to a "
                         "band.")
    a = ap.parse_args()

    if os.path.exists(os.path.join(a.case, "constant", "polyMesh")):
        sys.stderr.write("REFUSED: constant/polyMesh already exists in the case. "
                         "A builder never overwrites a built mesh.\n"); sys.exit(2)
    fins_in_domain = FIN_ALL if a.full_width else FIN_STLS
    need = ("hull.stl", "sail.stl") + tuple(f + ".stl" for f in FIN_ALL)
    for s in need:
        if not os.path.isfile(os.path.join(a.geom, s)):
            sys.stderr.write(f"REFUSED: {s} not found under --geom.  All four fin "
                             "surfaces must exist even though only three enter the "
                             "half model, so the full body is reproducible.\n")
            sys.exit(2)

    d0, l_hull, l_sail, l_fin, l_ste, l_fte, l_jct, nlay = LEVELS[a.level]

    nx = int(round((a.xmax - a.xmin) / d0)); ny = int(round(2 * a.rfar / d0))
    nz = int(round((2 if a.full_width else 1) * a.rfar / d0))
    xmax = a.xmin + nx * d0; ymax = ny * d0 / 2.0
    zmax = nz * d0 / (2.0 if a.full_width else 1.0)
    zmin = -zmax if a.full_width else 0.0
    ymin = -ymax
    d_ste = d0 / 2 ** l_ste
    d_fte = d0 / 2 ** l_fte
    d_fin = d0 / 2 ** l_fin

    # ---- PREDICTED feature resolution (octree arithmetic, NOT measurements) ----
    fin_root_full_thk_mm = 2.0 * 0.10002881 * FIN_CHORD_ROOT_M * 1000.0
    fin_tip_full_thk_mm = 2.0 * 0.10002881 * FIN_CHORD_TIP_M * 1000.0
    pred = {
        "cells_across_sail_TE_base": a.sail_base_mm * 1e-3 / d_ste,
        "cells_across_fin_TE_base_at_tip": a.fin_base_tip_mm * 1e-3 / d_fte,
        "cells_across_fin_TE_base_at_root": a.fin_base_root_mm * 1e-3 / d_fte,
        "CELLS_ACROSS_THE_APPENDAGE_ROOT": fin_root_full_thk_mm * 1e-3 / d_fin,
        "cells_across_the_appendage_TIP_thickness": fin_tip_full_thk_mm * 1e-3 / d_fin,
        "cells_along_the_fin_ROOT_chord": FIN_CHORD_ROOT_M / d_fin,
        "cells_along_the_fin_TIP_chord": FIN_CHORD_TIP_M / d_fin,
        "cells_along_the_fin_EXPOSED_SPAN": (FIN_TIP_R_M - FIN_ROOT_R_M) / d_fin,
        "hull_axial_faces": L_M / (d0 / 2 ** l_hull),
    }

    os.makedirs(os.path.join(a.case, "constant", "triSurface"), exist_ok=True)
    for s in ("hull.stl", "sail.stl") + tuple(f + ".stl" for f in fins_in_domain):
        shutil.copy(os.path.join(a.geom, s),
                    os.path.join(a.case, "constant", "triSurface", s))

    v = [(a.xmin, ymin, zmin), (xmax, ymin, zmin), (xmax, ymax, zmin),
         (a.xmin, ymax, zmin),
         (a.xmin, ymin, zmax), (xmax, ymin, zmax), (xmax, ymax, zmax),
         (a.xmin, ymax, zmax)]
    # THE z = zmin FACE.  On a HALF model it is the symmetry plane and is named
    # `symm`.  On a FULL model there is no symmetry plane, and the face is folded
    # into `farfield` rather than kept as a patch still called `symm` -- a patch
    # named for a symmetry that is not there is the same class of trap as a
    # configuration named by a bare number, and a downstream boundary-condition
    # file keyed on `symm` MUST fail loudly rather than quietly apply a
    # symmetry-shaped condition to an ordinary far-field face.
    if a.full_width:
        faces = ("    farfield { type patch; faces ((0 1 5 4) (3 7 6 2) "
                 "(4 5 6 7) (0 3 2 1)); }\n")
    else:
        faces = ("    farfield { type patch; faces ((0 1 5 4) (3 7 6 2) "
                 "(4 5 6 7)); }\n"
                 "    symm     { type symmetryPlane; faces ((0 3 2 1)); }\n")
    w(os.path.join(a.case, "system", "blockMeshDict"), "dictionary", "blockMeshDict",
      "scale 1;\nvertices\n(\n" +
      "".join(f"    ({p[0]:.9g} {p[1]:.9g} {p[2]:.9g})\n" for p in v) +
      f");\nblocks\n(\n    hex (0 1 2 3 4 5 6 7) ({nx} {ny} {nz}) simpleGrading (1 1 1)\n);\n"
      "edges ();\nboundary\n(\n"
      "    inlet    { type patch; faces ((0 4 7 3)); }\n"
      "    outlet   { type patch; faces ((1 2 6 5)); }\n" +
      faces +
      ");\nmergePatchPairs ();\n")

    # ---- refinement regions ----------------------------------------------------
    # SAIL trailing-edge box -- identical to the SUBOFF_A1 family's.
    x_ste = SAIL_LE_M + a.sail_te_trunc_frac * (SAIL_TE_M - SAIL_LE_M)
    z_sbase = 0.5 * a.sail_base_mm * 1e-3
    ste = (x_ste - 0.0015, x_ste + 0.0015, 0.96 * RMAX_M, Y_CAP_M + 0.002,
           4.0 * z_sbase)
    # FIN trailing-edge boxes -- ONE PER FIN, EACH THIN ALONG ITS OWN THICKNESS
    # DIRECTION.
    # A MEASURED DEFECT, RECORDED RATHER THAN QUIETLY FIXED.  The first version of
    # this builder used a SINGLE searchableBox spanning the full radial extent in
    # BOTH y and z.  A searchableBox is axis-aligned, so that box does not hug the
    # fins -- it fills the ENTIRE ANNULAR DISC at the fin trailing-edge station,
    # including all the empty fluid between the four appendages.  Measured on the
    # build of 2026-09-12T22:54Z: refinement level 9 reached 54,685,951 cells and
    # was still climbing when the job was stopped, against a whole-mesh target of
    # about 6e6.  The boxes below are thin along each fin's own thickness
    # direction and therefore refine the wake of the fin and nothing else.
    x_fte_tip = FIN_H_M - (1.0 - a.fin_te_trunc_frac) * FIN_CHORD_TIP_M
    x_fte_root = FIN_H_M - (1.0 - a.fin_te_trunc_frac) * FIN_CHORD_ROOT_M
    fte_x0 = x_fte_root - 0.0010                 # covers the whole TE taper ...
    fte_x1 = FIN_H_M + 0.0010                    # ... plus a 1 mm margin each side
    fte_s0 = FIN_ROOT_R_M - 0.004                # spanwise, root side
    fte_s1 = FIN_TIP_R_M + 0.004                 # spanwise, tip side
    # thickness half-extent: the SAME PROPORTION the SUBOFF_A1 sail box uses,
    # namely 2 x the full base thickness, evaluated at the thicker (root) base.
    fte_t = 2.0 * a.fin_base_root_mm * 1e-3
    # NO SEPARATE FIN-ROOT JUNCTION BOX, AND THE REASON IS MEASURED.
    # A searchableBox around the fin roots is a CUBE: the first version of this
    # builder wrote one of 252 x 300 x 300 mm at level 6, which is ~1.2e7 cells of
    # octree in mostly empty fluid.  The fin `mode distance` regions below already
    # refine the junction FROM BOTH SIDES -- level 6 within 4 mm of the fin and
    # level 5 within 20 mm, which lifts the neighbouring HULL cells (level 4) at
    # the root as well.  The junction is therefore resolved without the cube, and
    # RM1/RM2/RM3 measure whether that is true rather than assuming it.

    fin_geom = "".join(
        f"    {f}.stl {{ type triSurfaceMesh; name {f}; }}\n" for f in fins_in_domain)
    fin_surf = "".join(
        f"        {f} {{ level ({l_fin} {l_fin + 1}); "
        f"patchInfo {{ type wall; inGroups (wall); }} }}\n" for f in fins_in_domain)
    fin_regions = "".join(
        f"        {f} {{ mode distance; levels ((0.004 {l_fin}) "
        f"(0.020 {l_fin - 1}) (0.080 {l_fin - 2})); }}\n" for f in fins_in_domain)
    fin_layers = "".join(f"            {f} {{ nSurfaceLayers {nlay}; }}\n"
                         for f in fins_in_domain)

    # one TE box per in-domain fin, thin along THAT fin's thickness direction
    fte_boxes = {
        # fin000 spans +y, thickness is z
        "finTeBox000": ((fte_x0, fte_s0, -fte_t), (fte_x1, fte_s1, fte_t)),
        # fin180 spans -y, thickness is z
        "finTeBox180": ((fte_x0, -fte_s1, -fte_t), (fte_x1, -fte_s0, fte_t)),
        # fin090 spans +z, thickness is y
        "finTeBox090": ((fte_x0, -fte_t, fte_s0), (fte_x1, fte_t, fte_s1)),
    }
    fte_geom = "".join(
        f"    {n} {{ type searchableBox; min ({lo[0]:.6f} {lo[1]:.6f} {lo[2]:.6f}); "
        f"max ({hi[0]:.6f} {hi[1]:.6f} {hi[2]:.6f}); }}\n"
        for n, (lo, hi) in fte_boxes.items())
    fte_regions = "".join(
        f"        {n} {{ mode inside; levels ((1e15 {l_fte})); }}\n"
        for n in fte_boxes)

    snappy = f"""castellatedMesh true;
snap            true;
addLayers       true;

geometry
{{
    hull.stl {{ type triSurfaceMesh; name hull; }}
    sail.stl {{ type triSurfaceMesh; name sail; }}
{fin_geom}    sailTeBox {{ type searchableBox; min ({ste[0]:.6f} {ste[2]:.6f} {-ste[4]:.6f}); max ({ste[1]:.6f} {ste[3]:.6f} {ste[4]:.6f}); }}
{fte_geom}}}

castellatedMeshControls
{{
    maxLocalCells       4000000;
    maxGlobalCells      120000000;
    minRefinementCells  10;
    nCellsBetweenLevels 3;
    resolveFeatureAngle 30;
    allowFreeStandingZoneFaces true;
    features ();
    refinementSurfaces
    {{
        hull {{ level ({l_hull} {l_hull}); patchInfo {{ type wall; inGroups (wall); }} }}
        sail {{ level ({l_sail} {l_sail + 1}); patchInfo {{ type wall; inGroups (wall); }} }}
{fin_surf}    }}
    refinementRegions
    {{
        hull      {{ mode distance; levels ((0.030 {l_hull - 1}) (0.150 {l_hull - 2}) (0.500 {l_hull - 3})); }}
        sail      {{ mode distance; levels ((0.006 {l_sail}) (0.030 {l_sail - 1})); }}
{fin_regions}        sailTeBox {{ mode inside;   levels ((1e15 {l_ste})); }}
{fte_regions}    }}
    locationInMesh ({a.xmin + 0.5 * d0:.6f} {ymax - 0.5 * d0:.6f} {zmax - 0.5 * d0:.6f});
}}

snapControls
{{
    nSmoothPatch 5; tolerance 2.0; nSolveIter 60; nRelaxIter 8;
    nFeatureSnapIter 15; implicitFeatureSnap true; explicitFeatureSnap false;
    multiRegionFeatureSnap false;
}}

addLayersControls
{{
    relativeSizes true;
    layers
    {{
        hull {{ nSurfaceLayers {nlay}; }}
        sail {{ nSurfaceLayers {nlay}; }}
{fin_layers}    }}
    expansionRatio 1.2;
    finalLayerThickness 0.5;
    minThickness 0.02;
    nGrow 0;
    featureAngle 130; slipFeatureAngle 30;
    nRelaxIter 8; nSmoothSurfaceNormals 3; nSmoothNormals 5; nSmoothThickness 10;
    maxFaceThicknessRatio 0.5; maxThicknessToMedialRatio 0.3;
    minMedialAxisAngle 90; nBufferCellsNoExtrude 0;
    nLayerIter 50; nRelaxedIter 20;
}}

meshQualityControls
{{
    maxNonOrtho 65; maxBoundarySkewness 20; maxInternalSkewness 3.5;
    maxConcave 80; minVol 1e-16; minTetQuality 1e-15; minArea -1;
    minTwist 0.02; minDeterminant 0.001; minFaceWeight 0.03; minVolRatio 0.01;
    minTriangleTwist -1; nSmoothScale 4; errorReduction 0.75;
    relaxed {{ maxNonOrtho 70; minDeterminant 0.001; }}
}}

mergeTolerance 1e-6;
writeFlags (noRefinement);
"""
    w(os.path.join(a.case, "system", "snappyHexMeshDict"),
      "dictionary", "snappyHexMeshDict", snappy)

    w(os.path.join(a.case, "system", "controlDict"), "dictionary", "controlDict",
      "application simpleFoam;\nstartFrom startTime;\nstartTime 0;\nstopAt endTime;\n"
      "endTime 1;\ndeltaT 1;\nwriteControl timeStep;\nwriteInterval 1;\n"
      "purgeWrite 0;\nwriteFormat ascii;\nwritePrecision 8;\nrunTimeModifiable false;\n")
    w(os.path.join(a.case, "system", "fvSchemes"), "dictionary", "fvSchemes",
      "ddtSchemes { default steadyState; }\ngradSchemes { default cellLimited Gauss linear 1; }\n"
      "divSchemes { default none; div(phi,U) bounded Gauss linearUpwind grad(U);\n"
      "  div(phi,k) bounded Gauss limitedLinear 1; div(phi,omega) bounded Gauss limitedLinear 1;\n"
      "  div((nuEff*dev2(T(grad(U))))) Gauss linear; }\n"
      "laplacianSchemes { default Gauss linear corrected; }\n"
      "interpolationSchemes { default linear; }\nsnGradSchemes { default corrected; }\n")
    w(os.path.join(a.case, "system", "fvSolution"), "dictionary", "fvSolution",
      "solvers { p { solver GAMG; tolerance 1e-8; relTol 0.01; smoother GaussSeidel; }\n"
      "  \"(U|k|omega)\" { solver smoothSolver; smoother symGaussSeidel;\n"
      "                  tolerance 1e-8; relTol 0.1; } }\n"
      "SIMPLE { nNonOrthogonalCorrectors 2; consistent yes;\n"
      "  residualControl { p 1e-6; U 1e-6; \"(k|omega)\" 1e-6; } }\n"
      "relaxationFactors { equations { U 0.9; \".*\" 0.9; } }\n")
    w(os.path.join(a.case, "system", "decomposeParDict"), "dictionary",
      "decomposeParDict", f"numberOfSubdomains {a.nproc};\nmethod scotch;\n")
    w(os.path.join(a.case, "constant", "transportProperties"), "dictionary",
      "transportProperties", "transportModel  Newtonian;\nnu              1e-06;\n")
    w(os.path.join(a.case, "constant", "momentumTransport"), "dictionary",
      "momentumTransport", "simulationType RAS;\nRAS { model kOmegaSST; turbulence on;\n"
      "      printCoeffs on; }\n")
    w(os.path.join(a.case, "constant", "turbulenceProperties"), "dictionary",
      "turbulenceProperties", "simulationType RAS;\nRAS { RASModel kOmegaSST; turbulence on;\n"
      "      printCoeffs on; }\n")

    man = {
        "configuration_named_by_geometry":
            "hull WITH sail AND four identical stern appendages at the BASELINE "
            "axial position; NO ring wing, NO ring-wing struts",
        "width": "FULL" if a.full_width else "HALF (z >= 0)",
        "half_model": {
            "symmetry_plane": ("z = 0 (x-y plane)" if not a.full_width
                               else "NONE -- full width built"),
            "valid_for_the_whole_alpha_sweep_because":
                "the body is mirror-symmetric about z = 0 and the pitch free "
                "stream lies in that plane at every alpha",
            "fins_in_domain": list(fins_in_domain),
            "fin_not_in_domain": "fin270_horizontal (mirror of fin090 through z=0)",
            "force_accounting": "total = 2 x half-model, hull and fin patches alike",
        },
        "level": a.level, "base_cell_m": d0,
        "background": {"nx": nx, "ny": ny, "nz": nz, "cells": nx * ny * nz,
                       "bbox": [[a.xmin, ymin, zmin], [xmax, ymax, zmax]]},
        "octree_levels": {"hull": l_hull, "sail": [l_sail, l_sail + 1],
                          "fin": [l_fin, l_fin + 1], "sailTeBox": l_ste,
                          "finTeBox": l_fte, "nLayers": nlay},
        "cell_sizes_m": {"base": d0, "hull_surface": d0 / 2 ** l_hull,
                         "sail_surface": d0 / 2 ** l_sail, "fin_surface": d_fin,
                         "sail_TE_box": d_ste, "fin_TE_box": d_fte},
        "boxes_m": dict({"sailTeBox": [[ste[0], ste[2], -ste[4]], [ste[1], ste[3], ste[4]]],
                         },
                        **{n: [list(lo), list(hi)] for n, (lo, hi) in fte_boxes.items()}),
        "fin_geometry_m": {"h_TE": FIN_H_M, "tip_radius": FIN_TIP_R_M,
                           "root_radius_at_TE": FIN_ROOT_R_M,
                           "chord_tip": FIN_CHORD_TIP_M,
                           "chord_root": FIN_CHORD_ROOT_M,
                           "te_trunc_frac": a.fin_te_trunc_frac,
                           "TE_base_full_mm_tip": a.fin_base_tip_mm,
                           "TE_base_full_mm_root": a.fin_base_root_mm,
                           "max_full_thickness_mm_root": fin_root_full_thk_mm,
                           "max_full_thickness_mm_tip": fin_tip_full_thk_mm},
        "PREDICTED": pred,
        "note": "PREDICTED values are octree arithmetic, NOT measurements.  Every "
                "gate reads the BUILT mesh via probe_appended_features.py, never "
                "this file.",
    }
    with open(os.path.join(a.case, "BUILD_MANIFEST.json"), "w") as f:
        json.dump(man, f, indent=2)

    print(f"{a.level}: WIDTH = {'FULL' if a.full_width else 'HALF (z >= 0)'}; "
          f"background {nx}x{ny}x{nz} = {nx*ny*nz} cells, base {d0*1000:.2f} mm")
    print(f"  hull surface {d0/2**l_hull*1000:.3f} mm  sail {d0/2**l_sail*1000:.3f} mm  "
          f"fin {d_fin*1000:.3f} mm")
    print(f"  PREDICTED cells across the APPENDAGE ROOT : "
          f"{pred['CELLS_ACROSS_THE_APPENDAGE_ROOT']:.1f}  (floor 16)")
    print(f"  PREDICTED cells across the fin TE base    : "
          f"tip {pred['cells_across_fin_TE_base_at_tip']:.1f}, "
          f"root {pred['cells_across_fin_TE_base_at_root']:.1f}  (floor 8)")
    print(f"  PREDICTED cells across the sail TE base   : "
          f"{pred['cells_across_sail_TE_base']:.1f}  (floor 8)")
    print(f"  PREDICTED cells along the fin exposed span: "
          f"{pred['cells_along_the_fin_EXPOSED_SPAN']:.1f}")


if __name__ == "__main__":
    main()
