#!/usr/bin/env python3
"""snappyHexMeshDict for the PPTC VP1304 open-water passage — one script, three levels.

HOW THE FAMILY RATIO OF 1.5 IS REALISED.  Sanaa's §6.3 asks for "uniform ratio 1.5 in the
refinement levels and the surface size".  Refinement levels are integer powers of two, so a
ratio of 1.5 cannot come from the level.  It comes from the BACKGROUND: `make_blockmesh.py`
scales the background by the family ratio, the refinement level is held constant, and the
achieved surface cell is background / 2^level.  That gives exactly 1.5 between levels:

    coarse  ratio 1.00   background ~20.0 mm   level 5  ->  0.625 mm surface cell
    medium  ratio 1.50   background ~13.3 mm   level 5  ->  0.417 mm
    fine    ratio 2.25   background ~ 8.9 mm   level 5  ->  0.278 mm

RESOLUTION FOLLOWS THE GEOMETRY.  The blades carry KQ and the graded blade loading and are
twisted, thin-edged and highly curved; the hub, cap and shaft carry only thrust and are smooth
bodies of revolution — which is what this case's own patch classifier established about them.
They are refined less.  `shaftExtension` is a flow boundary excluded from BOTH graded
integrations (pre-registration amendment 2) and is refined least of all.

THE MRF ZONE IS A REGISTERED PARAMETER WITH A SENSITIVITY, NEVER A DEFAULT.  §6.2: a cylinder
of diameter 1.3D, axial extent -0.5D to +0.5D, with the 1.3D-versus-1.6D difference in KT
measured once on the coarse level.  The lesson is this lab's own Rushton act, where an MRF zone
left near the swept volume cost more than 12 % on the power number.  `--mrf-diameter` exists so
the sensitivity is run from the same script, not from a hand-edited dictionary.
"""
from __future__ import annotations

import argparse
import math
import os

D = 0.250
R = D / 2.0

# Registered surface refinement levels.  Held CONSTANT across the family; the ratio comes from
# the background (see the module docstring).
LEVELS = {
    'blades': (5, 5),
    'hub': (4, 4),
    'cap': (4, 4),
    'shaft': (3, 3),
    'shaftExtension': (2, 2),
}
# Prism layers: pre-registration 6.3 -- 6 layers, growth ratio 1.2, on blades, hub, cap and
# shaft.  NOT on shaftExtension: it is excluded from both graded integrations, so layers there
# would buy nothing and cost cells.
LAYER_PATCHES = ('blades', 'hub', 'cap', 'shaft')
N_LAYERS = 6
EXPANSION = 1.2

HEADER = """/*--------------------------------*- C++ -*----------------------------------*\\
| PPTC VP1304 open-water passage -- snappyHexMeshDict                         |
| Generated by cases/PPTC_VP1304/mesh/make_snappy.py -- DO NOT EDIT BY HAND   |
\\*---------------------------------------------------------------------------*/
FoamFile
{
    version     2.0;
    format      ascii;
    class       dictionary;
    object      snappyHexMeshDict;
}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

castellatedMesh {castellate};
snap            {snap};
addLayers       {layers};

"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('--case', required=True)
    ap.add_argument('--ratio', type=float, default=1.0)
    # PHASE CONTROL: snappyHexMesh writes constant/polyMesh after EACH phase even under
    # -overwrite, so a run that dies in layer addition leaves the SNAPPED mesh intact and the
    # layer phase can be re-run alone. That is a 25-minute saving per attempt and it is the
    # only reason a layer experiment is affordable at all.
    ap.add_argument('--castellate', default='true')
    ap.add_argument('--snap', default='true')
    ap.add_argument('--layers', default='true')
    # LAYER PATCH CONTROL: registered default is all four of blades, hub, cap and shaft
    # (pre-registration 6.3). Narrowing it is a DISCLOSED departure, never a silent one, and
    # it exists because snappyHexMesh cannot extrude layers on a wall that TERMINATES ON A
    # CYCLIC -- which in a sector mesh the hub, cap and shaft always do, at any wedge phase.
    ap.add_argument('--layer-patches', default=','.join(LAYER_PATCHES))
    ap.add_argument('--mrf-diameter', type=float, default=1.3,
                    help='MRF zone diameter in propeller diameters -- REGISTERED PARAMETER, '
                         'sensitivity 1.3 vs 1.6 on the coarse level (pre-registration 6.2)')
    ap.add_argument('--mrf-axial', type=float, default=0.5,
                    help='MRF zone half-extent in propeller diameters, each side of the '
                         'propeller plane')
    a = ap.parse_args()

    r_mrf = a.mrf_diameter * D / 2.0
    x_mrf = a.mrf_axial * D

    # str.replace, NOT str.format: the header contains the FoamFile block's literal
    # braces, and .format would have to escape every one of them. The three switches
    # are echoed back below so the dictionary that was written is on the record.
    hdr = (HEADER.replace('{castellate}', a.castellate)
                 .replace('{snap}', a.snap)
                 .replace('{layers}', a.layers))
    for tok in ('{castellate}', '{snap}', '{layers}'):
        if tok in hdr:
            raise SystemExit(f'REFUSE: {tok} was not substituted in the header')
    o = [hdr, 'geometry\n{\n']
    for p in LEVELS:
        o.append(f'    {p}\n    {{\n        type triSurfaceMesh;\n'
                 f'        file "{p}.stl";\n        name {p};\n    }}\n')
    # blade refinement region: a cylinder enclosing the blades with a margin
    o.append(f'    bladeRegion\n    {{\n        type searchableCylinder;\n'
             f'        point1 (-0.100 0 0);\n        point2 ( 0.060 0 0);\n'
             f'        radius {1.06*R:.6f};\n    }}\n')
    # tip-vortex path: a cylinder along the wake, 1D downstream (pre-registration 6.3)
    o.append(f'    tipVortex\n    {{\n        type searchableCylinder;\n'
             f'        point1 (-{D:.6f} 0 0);\n        point2 ( 0.030 0 0);\n'
             f'        radius {1.04*R:.6f};\n    }}\n')
    # the MRF zone -- a registered parameter, written from the command line, never a default
    o.append(f'    MRFzone\n    {{\n        type searchableCylinder;\n'
             f'        point1 (-{x_mrf:.6f} 0 0);\n        point2 ( {x_mrf:.6f} 0 0);\n'
             f'        radius {r_mrf:.6f};\n    }}\n')
    o.append('}\n\n')

    o.append('castellatedMeshControls\n{\n')
    o.append('    maxLocalCells       4000000;\n    maxGlobalCells      60000000;\n')
    o.append('    minRefinementCells  10;\n    maxLoadUnbalance    0.10;\n')
    o.append('    nCellsBetweenLevels 3;\n\n')
    o.append('    features\n    (\n')
    for p in LEVELS:
        lvl = LEVELS[p][1]
        o.append(f'        {{ file "{p}.eMesh"; level {lvl}; }}\n')
    o.append('    );\n\n    refinementSurfaces\n    {\n')
    for p, (lo, hi) in LEVELS.items():
        o.append(f'        {p}\n        {{\n            level ({lo} {hi});\n'
                 f'            patchInfo {{ type wall; }}\n        }}\n')
    o.append('    }\n\n')
    o.append('    resolveFeatureAngle 30;\n\n    refinementRegions\n    {\n')
    o.append(f'        bladeRegion {{ mode inside; levels ((1e15 {LEVELS["blades"][0]-1})); }}\n')
    o.append(f'        tipVortex   {{ mode inside; levels ((1e15 {LEVELS["blades"][0]-1})); }}\n')
    # the MRF zone is a CELL ZONE, not a refinement -- it carries the rotating-frame source
    o.append('    }\n\n')
    # a point in the fluid inside the 72 deg sector: r = 0.5 m on the sector centreline (+y),
    # x = +0.4 m, which is upstream of the cap tip and outside every body
    o.append('    locationInMesh (0.4 0.5 0.0);\n')
    o.append('    allowFreeStandingZoneFaces false;\n}\n\n')

    o.append('snapControls\n{\n    nSmoothPatch 3;\n    tolerance 2.0;\n    nSolveIter 50;\n'
             '    nRelaxIter 5;\n    nFeatureSnapIter 15;\n    implicitFeatureSnap false;\n'
             '    explicitFeatureSnap true;\n    multiRegionFeatureSnap false;\n}\n\n')

    o.append('addLayersControls\n{\n    relativeSizes true;\n    layers\n    {\n')
    for p in [q for q in a.layer_patches.split(',') if q]:
        o.append(f'        {p}\n        {{\n            nSurfaceLayers {N_LAYERS};\n        }}\n')
    o.append('    }\n')
    o.append(f'    expansionRatio {EXPANSION};\n')
    o.append('    finalLayerThickness 0.5;\n    minThickness 0.05;\n')
    o.append('    nGrow 0;\n    featureAngle 130;\n    slipFeatureAngle 30;\n'
             '    nRelaxIter 5;\n    nSmoothSurfaceNormals 1;\n    nSmoothNormals 3;\n'
             '    nSmoothThickness 10;\n    maxFaceThicknessRatio 0.5;\n'
             '    maxThicknessToMedialRatio 0.3;\n    minMedialAxisAngle 90;\n'
             '    nBufferCellsNoExtrude 0;\n    nLayerIter 50;\n    nRelaxedIter 20;\n}\n\n')

    # Quality: Sanaa's 6.4 gates are non-orthogonality < 70 and skewness < 4, and the lab
    # standard enforces skewness 4 on BOUNDARY faces too (MESH_STANDARD.md 3.2), which
    # snappyHexMesh's own defaults do not -- its maxBoundarySkewness default is 20.
    o.append('meshQualityControls\n{\n    maxNonOrtho 65;\n    maxBoundarySkewness 4;\n'
             '    maxInternalSkewness 4;\n    maxConcave 80;\n    minVol 1e-13;\n'
             '    minTetQuality 1e-30;\n    minArea -1;\n    minTwist 0.02;\n'
             '    minDeterminant 0.001;\n    minFaceWeight 0.02;\n    minVolRatio 0.01;\n'
             '    minTriangleTwist -1;\n    nSmoothScale 4;\n    errorReduction 0.75;\n'
             '    relaxed { maxNonOrtho 70; }\n}\n\n')
    o.append('mergeTolerance 1e-6;\n\n'
             '// ************************************************************************* //\n')

    p = os.path.join(a.case, 'system', 'snappyHexMeshDict')
    os.makedirs(os.path.dirname(p), exist_ok=True)
    with open(p, 'w') as fh:
        fh.write(''.join(o))

    bg = 20.0 / a.ratio          # near-field background cell, mm, from make_blockmesh
    print(f'wrote {p}')
    print(f'  family ratio {a.ratio}: near-field background {bg:.2f} mm')
    for pp, (lo, hi) in LEVELS.items():
        print(f'    {pp:>16} level {hi} -> surface cell {bg/2**hi:.4f} mm')
    print(f'  MRF zone: diameter {a.mrf_diameter}D = {2*r_mrf:.4f} m, '
          f'axial +-{a.mrf_axial}D = +-{x_mrf:.4f} m   [REGISTERED PARAMETER]')
    print(f'  phases: castellatedMesh {a.castellate}, snap {a.snap}, '
          f'addLayers {a.layers}')
    print(f'  layers: {N_LAYERS} at expansion {EXPANSION} on {a.layer_patches} '
          f'(none on shaftExtension -- excluded from both graded integrations)')
    print(f'  quality: maxBoundarySkewness 4 (snappy default is 20; MESH_STANDARD 3.2 '
          f'enforces 4 on boundary faces)')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
