#!/usr/bin/env python3
"""Background sector mesh for the PPTC VP1304 open-water passage.

Writes `system/blockMeshDict` for the domain registered in pre-registration section 6.1:

    inlet   3D upstream of the propeller plane   x = +0.750 m
    outlet  6D downstream                        x = -1.500 m
    outer radius 4D                              r =  1.000 m
    single blade passage of 72 deg with CYCLIC periodic boundaries

AXIS ORIENTATION, from GEOMETRY_ADMISSION_RECORD.md section 2: the nose cap sits at +x and
the shaft at -x, so the freestream runs +x -> -x.  The inlet is therefore the +x face.

THE AXIS IS IN THE FLUID and must be meshed.  Upstream of the nose-cap tip (x > +0.134 m)
there is no body on the centreline, so an annular background with a hollow core would leave
an unphysical hole there.  The inner radial block is therefore a pie slice whose inner edge
is COLLAPSED onto the axis, giving prism cells along the centreline -- the standard sector
construction.  Those cells sit in the far field ahead of the cap and are refined by nothing.

GRADING.  The domain is 2.25 m long and 1.0 m in radius while the propeller is 0.25 m across,
so a uniform background is impossible at any sensible cell count: at 25 mm it would be 90 M
cells before a single refinement.  The background is therefore graded -- near-isotropic and
fine through the propeller region, expanding into the far field -- and snappyHexMesh supplies
the resolution at the blades.  Cell counts scale with the family ratio (section 6.3).
"""
from __future__ import annotations

import argparse
import math
import os

D = 0.250
X_INLET = +3.0 * D          # +0.750
X_OUTLET = -6.0 * D         # -1.500
R_OUTER = 4.0 * D           # +1.000

X_NEAR_FWD = +0.30          # near-field box, forward face
X_NEAR_AFT = -0.30          # near-field box, aft face
R_NEAR = 0.16               # radial split: pie slice inside, graded annulus outside

HEADER = """/*--------------------------------*- C++ -*----------------------------------*\\
| PPTC VP1304 open-water passage -- background sector mesh                    |
| Generated by cases/PPTC_VP1304/mesh/make_blockmesh.py -- DO NOT EDIT BY HAND |
\\*---------------------------------------------------------------------------*/
FoamFile
{
    version     2.0;
    format      ascii;
    class       dictionary;
    object      blockMeshDict;
}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

scale   1;

"""


def sector_points(x, r, half_deg):
    """Four (x, y, z) corners at axial station x, radius r, at -half and +half degrees."""
    a = math.radians(half_deg)
    return [(x, r * math.cos(-a), r * math.sin(-a)),
            (x, r * math.cos(+a), r * math.sin(+a))]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('--case', required=True)
    ap.add_argument('--ratio', type=float, default=1.0,
                    help='family refinement ratio: 1.0 coarse, 1.5 medium, 2.25 fine')
    ap.add_argument('--half-angle', type=float, default=36.0)
    a = ap.parse_args()

    k = a.ratio
    ha = a.half_angle

    # base counts at ratio 1.0 (coarse), scaled by the family ratio and rounded up
    def n(base):
        return max(1, int(math.ceil(base * k)))

    n_theta = n(12)          # circumferential cells across the 72 deg passage
    n_r_in = n(8)            # radial cells, axis -> R_NEAR
    n_r_out = n(18)          # radial cells, R_NEAR -> R_OUTER (graded)
    n_x_aft = n(22)          # outlet -> near-field aft (graded)
    n_x_mid = n(28)          # near-field block (uniform)
    n_x_fwd = n(11)          # near-field fwd -> inlet (graded)

    exp_r_out = 8.0          # radial expansion into the far field
    exp_x_aft = 5.0          # axial expansion toward the outlet
    exp_x_fwd = 3.0          # axial expansion toward the inlet

    # vertex layout: 4 axial stations x 2 radial shells, plus the collapsed axis line
    xs = [X_OUTLET, X_NEAR_AFT, X_NEAR_FWD, X_INLET]
    v, idx = [], {}

    def add(key, p):
        idx[key] = len(v)
        v.append(p)

    for i, x in enumerate(xs):
        add(('ax', i), (x, 0.0, 0.0))                      # on the axis (collapsed edge)
        lo, hi = sector_points(x, R_NEAR, ha)
        add(('in', i, 0), lo)
        add(('in', i, 1), hi)
        lo, hi = sector_points(x, R_OUTER, ha)
        add(('out', i, 0), lo)
        add(('out', i, 1), hi)

    blocks, edges = [], []
    for i in range(3):
        nx = (n_x_aft, n_x_mid, n_x_fwd)[i]
        gx = (f'{1.0/exp_x_aft:g}', '1', f'{exp_x_fwd:g}')[i]
        # inner pie slice: the two axis vertices are repeated, collapsing the inner edge
        b = [idx[('ax', i)], idx[('in', i, 0)], idx[('in', i, 1)], idx[('ax', i)],
             idx[('ax', i + 1)], idx[('in', i + 1, 0)], idx[('in', i + 1, 1)], idx[('ax', i + 1)]]
        blocks.append((b, (n_r_in, n_theta, nx), ('1', '1', gx)))
        # outer annulus, graded radially into the far field
        b = [idx[('in', i, 0)], idx[('out', i, 0)], idx[('out', i, 1)], idx[('in', i, 1)],
             idx[('in', i + 1, 0)], idx[('out', i + 1, 0)], idx[('out', i + 1, 1)],
             idx[('in', i + 1, 1)]]
        blocks.append((b, (n_r_out, n_theta, nx), (f'{exp_r_out:g}', '1', gx)))
        # arc edges so the circumferential faces are true arcs, not chords
        for shell, rad in (('in', R_NEAR), ('out', R_OUTER)):
            for j in (i, i + 1):
                mid = (xs[j], rad, 0.0)
                edges.append((idx[(shell, j, 0)], idx[(shell, j, 1)], mid))

    out = [HEADER, 'vertices\n(\n']
    for p in v:
        out.append(f'    ({p[0]:.8g} {p[1]:.8g} {p[2]:.8g})\n')
    out.append(');\n\nblocks\n(\n')
    for b, nn, gg in blocks:
        out.append(f'    hex ({" ".join(str(i) for i in b)}) '
                   f'({nn[0]} {nn[1]} {nn[2]}) simpleGrading ({gg[0]} {gg[1]} {gg[2]})\n')
    out.append(');\n\nedges\n(\n')
    seen = set()
    for p0, p1, m in edges:
        if (p0, p1) in seen:
            continue
        seen.add((p0, p1))
        out.append(f'    arc {p0} {p1} ({m[0]:.8g} {m[1]:.8g} {m[2]:.8g})\n')
    out.append(');\n\nboundary\n(\n')

    def face_list(pick):
        s = []
        for i in range(3):
            s += pick(i)
        return s

    # inlet: +x end, both radial blocks (station index 3)
    inlet = [[idx[('ax', 3)], idx[('ax', 3)], idx[('in', 3, 1)], idx[('in', 3, 0)]],
             [idx[('in', 3, 0)], idx[('in', 3, 1)], idx[('out', 3, 1)], idx[('out', 3, 0)]]]
    outlet = [[idx[('ax', 0)], idx[('in', 0, 0)], idx[('in', 0, 1)], idx[('ax', 0)]],
              [idx[('in', 0, 0)], idx[('out', 0, 0)], idx[('out', 0, 1)], idx[('in', 0, 1)]]]
    outer = face_list(lambda i: [[idx[('out', i, 0)], idx[('out', i + 1, 0)],
                                 idx[('out', i + 1, 1)], idx[('out', i, 1)]]])
    cyc0 = face_list(lambda i: [
        [idx[('ax', i)], idx[('ax', i + 1)], idx[('in', i + 1, 0)], idx[('in', i, 0)]],
        [idx[('in', i, 0)], idx[('in', i + 1, 0)], idx[('out', i + 1, 0)], idx[('out', i, 0)]]])
    cyc1 = face_list(lambda i: [
        [idx[('ax', i)], idx[('in', i, 1)], idx[('in', i + 1, 1)], idx[('ax', i + 1)]],
        [idx[('in', i, 1)], idx[('out', i, 1)], idx[('out', i + 1, 1)], idx[('in', i + 1, 1)]]])

    def emit(name, typ, faces, extra=''):
        out.append(f'    {name}\n    {{\n        type {typ};\n{extra}        faces\n        (\n')
        for f in faces:
            out.append(f'            ({" ".join(str(i) for i in f)})\n')
        out.append('        );\n    }\n')

    emit('inlet', 'patch', inlet)
    emit('outlet', 'patch', outlet)
    emit('outerBoundary', 'patch', outer)
    rot = ('        neighbourPatch  periodic1;\n        transform       rotational;\n'
           '        rotationAxis    (1 0 0);\n        rotationCentre  (0 0 0);\n')
    emit('periodic0', 'cyclic', cyc0, rot)
    rot = ('        neighbourPatch  periodic0;\n        transform       rotational;\n'
           '        rotationAxis    (1 0 0);\n        rotationCentre  (0 0 0);\n')
    emit('periodic1', 'cyclic', cyc1, rot)
    out.append(');\n\nmergePatchPairs\n(\n);\n\n'
               '// ************************************************************************* //\n')

    p = os.path.join(a.case, 'system', 'blockMeshDict')
    os.makedirs(os.path.dirname(p), exist_ok=True)
    with open(p, 'w') as fh:
        fh.write(''.join(out))

    total = sum(nn[0] * nn[1] * nn[2] for _, nn, _ in blocks)
    print(f'wrote {p}')
    print(f'  family ratio {k}, passage {2*ha:g} deg')
    print(f'  cells: theta {n_theta}, radial {n_r_in}+{n_r_out}, '
          f'axial {n_x_aft}+{n_x_mid}+{n_x_fwd}  -> background {total} cells')
    dx = (X_NEAR_FWD - X_NEAR_AFT) / n_x_mid
    dr = R_NEAR / n_r_in
    dth = math.radians(2 * ha) * 0.125 / n_theta
    print(f'  near-field cell at the blade tip: dx {1e3*dx:.1f} mm, dr {1e3*dr:.1f} mm, '
          f'r.dtheta {1e3*dth:.1f} mm  (aspect {max(dx,dr,dth)/min(dx,dr,dth):.2f})')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
