#!/usr/bin/env python3
"""
SUBOFF_A1 -- MESH CASE BUILDER.  One level of the hull+sail half-model
snappyHexMesh family.  Emits a complete case directory; it does NOT run anything.

HALF MODEL.  The sail sits at TOP DEAD CENTRE (theta = 0, +y) and the flow is at
zero drift, so the x-y plane (z = 0) is a symmetry plane.  The background block
spans z in [0, Rfar]; the STL solids are FULL bodies and are simply cut by it.

TWO CLOSED OVERLAPPING SOLIDS.  hull.stl and sail.stl each close on themselves and
the sail's lower lid is buried at y = 0, deep inside the hull.  snappyHexMesh's
castellation keeps only cells reachable from locationInMesh, so the UNION is what
survives; no boolean is needed and no coincident-surface sliver is created.

ZERO `assert` (L-332).
"""
import sys
if not __debug__:
    sys.stderr.write("REFUSED: must not run under python3 -O.\n"); sys.exit(2)
import os, json, math, argparse, shutil

FT2M = 0.3048
L_M  = 14.291667 * FT2M          # 4.35610 m
SAIL_LE_M, SAIL_TE_M = 3.032986 * FT2M, 4.241319 * FT2M
Y_CAP_M   = 1.507813 * FT2M
RMAX_M    = (5.0 / 6.0) * FT2M

HDR = """/*--------------------------------*- C++ -*----------------------------------*\\
| SUBOFF_A1  --  generated by cases/navier_class/SUBOFF_A1/build_suboff_a1_mesh.py |
\\*---------------------------------------------------------------------------*/
FoamFile
{{
    version     2.0;
    format      ascii;
    class       {cls};
    object      {obj};
}}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
"""


def w(path, cls, obj, body):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(HDR.format(cls=cls, obj=obj)); f.write(body)


LEVELS = {
    # name : (base cell size m, hull lvl, sail lvl, TE box lvl, junction lvl, nLayers)
    "L1": (0.0787, 4, 6, 9, 6, 6),
    "L2": (0.0525, 4, 6, 9, 6, 7),
    "L3": (0.0350, 4, 6, 9, 6, 8),
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--case", required=True)
    ap.add_argument("--level", required=True, choices=sorted(LEVELS))
    ap.add_argument("--geom", required=True, help="dir holding hull.stl / sail.stl")
    ap.add_argument("--xmin", type=float, default=-2.0)
    ap.add_argument("--xmax", type=float, default=9.0)
    ap.add_argument("--rfar", type=float, default=3.0)
    a = ap.parse_args()

    if os.path.exists(os.path.join(a.case, "constant", "polyMesh")):
        sys.stderr.write("REFUSED: constant/polyMesh already exists in the case. "
                         "A builder never overwrites a built mesh (rule-4 sibling).\n")
        sys.exit(2)
    for s in ("hull.stl", "sail.stl"):
        if not os.path.isfile(os.path.join(a.geom, s)):
            sys.stderr.write(f"REFUSED: {s} not found under --geom.\n"); sys.exit(2)

    d0, l_hull, l_sail, l_te, l_jct, nlay = LEVELS[a.level]

    # ---- background block, snapped so the domain is an integer number of d0 ----
    nx = int(round((a.xmax - a.xmin) / d0)); ny = int(round(2 * a.rfar / d0))
    nz = int(round(a.rfar / d0))
    xmax = a.xmin + nx * d0; ymax = ny * d0 / 2.0; zmax = nz * d0
    ymin = -ymax
    d_te = d0 / 2 ** l_te
    base_mm = 1.3109                      # measured by the geometry generator
    cells_across_base = base_mm * 1e-3 / d_te

    os.makedirs(os.path.join(a.case, "constant", "triSurface"), exist_ok=True)
    for s in ("hull.stl", "sail.stl"):
        shutil.copy(os.path.join(a.geom, s),
                    os.path.join(a.case, "constant", "triSurface", s))

    v = [(a.xmin, ymin, 0), (xmax, ymin, 0), (xmax, ymax, 0), (a.xmin, ymax, 0),
         (a.xmin, ymin, zmax), (xmax, ymin, zmax), (xmax, ymax, zmax), (a.xmin, ymax, zmax)]
    w(os.path.join(a.case, "system", "blockMeshDict"), "dictionary", "blockMeshDict",
      "scale 1;\nvertices\n(\n" + "".join(f"    ({p[0]:.9g} {p[1]:.9g} {p[2]:.9g})\n" for p in v) +
      f");\nblocks\n(\n    hex (0 1 2 3 4 5 6 7) ({nx} {ny} {nz}) simpleGrading (1 1 1)\n);\n"
      "edges ();\nboundary\n(\n"
      "    inlet    { type patch; faces ((0 4 7 3)); }\n"
      "    outlet   { type patch; faces ((1 2 6 5)); }\n"
      "    farfield { type patch; faces ((0 1 5 4) (3 7 6 2) (4 5 6 7)); }\n"
      "    symm     { type symmetryPlane; faces ((0 3 2 1)); }\n"
      ");\nmergePatchPairs ();\n")

    # ---- refinement regions -----------------------------------------------
    # MEASURED, NOT GUESSED.  The first build of this level used BOXES around the
    # whole near field and a 40 mm x 271 mm x 20 mm level-9 box at the trailing
    # edge.  It reached 8,740,333 cells at surface-refinement iteration 6 and was
    # still climbing when it was stopped: that level-9 box alone is ~6.0e7 cells
    # of octree.  The regions below hug the body by DISTANCE and keep the level-9
    # box down to the base itself.
    x_te   = SAIL_LE_M + 0.995 * (SAIL_TE_M - SAIL_LE_M)
    z_base = 0.5 * 1.3109e-3                # half the truncated base, metres
    te_x0, te_x1 = x_te - 0.0015, x_te + 0.0015
    te_y0, te_y1 = 0.96 * RMAX_M, Y_CAP_M + 0.002
    te_z = 4.0 * z_base
    jc_x0, jc_x1 = SAIL_LE_M - 0.020, SAIL_TE_M + 0.020
    jc_y0, jc_y1 = RMAX_M - 0.020, RMAX_M + 0.010
    jc_z = 0.025

    snappy = f"""castellatedMesh true;
snap            true;
addLayers       true;

geometry
{{
    hull.stl {{ type triSurfaceMesh; name hull; }}
    sail.stl {{ type triSurfaceMesh; name sail; }}
    teBox  {{ type searchableBox; min ({te_x0:.6f} {te_y0:.6f} {-te_z:.6f}); max ({te_x1:.6f} {te_y1:.6f} {te_z:.6f}); }}
    jctBox {{ type searchableBox; min ({jc_x0:.6f} {jc_y0:.6f} {-jc_z:.6f}); max ({jc_x1:.6f} {jc_y1:.6f} {jc_z:.6f}); }}
}}

castellatedMeshControls
{{
    maxLocalCells       2000000;
    maxGlobalCells      60000000;
    minRefinementCells  10;
    nCellsBetweenLevels 3;
    resolveFeatureAngle 30;
    allowFreeStandingZoneFaces true;
    features ();
    refinementSurfaces
    {{
        hull {{ level ({l_hull} {l_hull}); patchInfo {{ type wall; inGroups (wall); }} }}
        sail {{ level ({l_sail} {l_sail + 1}); patchInfo {{ type wall; inGroups (wall); }} }}
    }}
    refinementRegions
    {{
        hull   {{ mode distance; levels ((0.030 {l_hull - 1}) (0.150 {l_hull - 2}) (0.500 {l_hull - 3})); }}
        sail   {{ mode distance; levels ((0.006 {l_sail}) (0.030 {l_sail - 1})); }}
        jctBox {{ mode inside;   levels ((1e15 {l_jct})); }}
        teBox  {{ mode inside;   levels ((1e15 {l_te})); }}
    }}
    locationInMesh ({a.xmin + 0.5 * d0:.6f} {ymax - 0.5 * d0:.6f} {zmax - 0.5 * d0:.6f});
}}

snapControls
{{
    nSmoothPatch 5; tolerance 2.0; nSolveIter 60; nRelaxIter 8;
    nFeatureSnapIter 15; implicitFeatureSnap true; explicitFeatureSnap false;
    multiRegionFeatureSnap false;
}}

addLayersControls
{{
    relativeSizes true;
    layers {{ hull {{ nSurfaceLayers {nlay}; }} sail {{ nSurfaceLayers {nlay}; }} }}
    expansionRatio 1.2;
    finalLayerThickness 0.5;
    minThickness 0.02;
    nGrow 0;
    featureAngle 130; slipFeatureAngle 30;
    nRelaxIter 8; nSmoothSurfaceNormals 3; nSmoothNormals 5; nSmoothThickness 10;
    maxFaceThicknessRatio 0.5; maxThicknessToMedialRatio 0.3;
    minMedialAxisAngle 90; nBufferCellsNoExtrude 0;
    nLayerIter 50; nRelaxedIter 20;
}}

meshQualityControls
{{
    maxNonOrtho 65; maxBoundarySkewness 20; maxInternalSkewness 3.5;
    maxConcave 80; minVol 1e-16; minTetQuality 1e-15; minArea -1;
    minTwist 0.02; minDeterminant 0.001; minFaceWeight 0.03; minVolRatio 0.01;
    minTriangleTwist -1; nSmoothScale 4; errorReduction 0.75;
    relaxed {{ maxNonOrtho 70; minDeterminant 0.001; }}
}}

mergeTolerance 1e-6;
writeFlags (noRefinement);
"""
    w(os.path.join(a.case, "system", "snappyHexMeshDict"),
      "dictionary", "snappyHexMeshDict", snappy)

    w(os.path.join(a.case, "system", "controlDict"), "dictionary", "controlDict",
      "application simpleFoam;\nstartFrom startTime;\nstartTime 0;\nstopAt endTime;\n"
      "endTime 1;\ndeltaT 1;\nwriteControl timeStep;\nwriteInterval 1;\n"
      "purgeWrite 0;\nwriteFormat ascii;\nwritePrecision 8;\nrunTimeModifiable false;\n")
    w(os.path.join(a.case, "system", "fvSchemes"), "dictionary", "fvSchemes",
      "ddtSchemes { default steadyState; }\ngradSchemes { default cellLimited Gauss linear 1; }\n"
      "divSchemes { default none; div(phi,U) bounded Gauss linearUpwind grad(U);\n"
      "  div(phi,k) bounded Gauss limitedLinear 1; div(phi,omega) bounded Gauss limitedLinear 1;\n"
      "  div((nuEff*dev2(T(grad(U))))) Gauss linear; }\n"
      "laplacianSchemes { default Gauss linear corrected; }\n"
      "interpolationSchemes { default linear; }\nsnGradSchemes { default corrected; }\n")
    w(os.path.join(a.case, "system", "fvSolution"), "dictionary", "fvSolution",
      "solvers { p { solver GAMG; tolerance 1e-8; relTol 0.01; smoother GaussSeidel; }\n"
      "  \"(U|k|omega)\" { solver smoothSolver; smoother symGaussSeidel;\n"
      "                  tolerance 1e-8; relTol 0.1; } }\n"
      "SIMPLE { nNonOrthogonalCorrectors 2; consistent yes;\n"
      "  residualControl { p 1e-6; U 1e-6; \"(k|omega)\" 1e-6; } }\n"
      "relaxationFactors { equations { U 0.9; \".*\" 0.9; } }\n")
    nproc = 8
    w(os.path.join(a.case, "system", "decomposeParDict"), "dictionary", "decomposeParDict",
      f"numberOfSubdomains {nproc};\nmethod scotch;\n")

    w(os.path.join(a.case, "constant", "transportProperties"), "dictionary",
      "transportProperties", "transportModel  Newtonian;\nnu              1e-06;\n")
    w(os.path.join(a.case, "constant", "momentumTransport"), "dictionary",
      "momentumTransport", "simulationType RAS;\nRAS { model kOmegaSST; turbulence on;\n"
      "      printCoeffs on; }\n")
    w(os.path.join(a.case, "constant", "turbulenceProperties"), "dictionary",
      "turbulenceProperties", "simulationType RAS;\nRAS { RASModel kOmegaSST; turbulence on;\n"
      "      printCoeffs on; }\n")

    man = {
        "level": a.level, "base_cell_m": d0,
        "background": {"nx": nx, "ny": ny, "nz": nz,
                       "cells": nx * ny * nz,
                       "bbox": [[a.xmin, ymin, 0.0], [xmax, ymax, zmax]]},
        "levels": {"hull": l_hull, "sail": [l_sail, l_sail + 1],
                   "teBox": l_te, "jctBox": l_jct, "nLayers": nlay},
        "te_box_m": [[te_x0, te_y0, -te_z], [te_x1, te_y1, te_z]],
        "finest_cell_m": d_te,
        "hull_surface_cell_m": d0 / 2 ** l_hull,
        "hull_axial_faces_predicted": L_M / (d0 / 2 ** l_hull),
        "PREDICTED_cells_across_truncated_TE_base": cells_across_base,
        "note": "PREDICTED counts are octree arithmetic, NOT measurements. The gate "
                "reads the BUILT mesh (probe_suboff_a1_features.py), never this file.",
    }
    with open(os.path.join(a.case, "BUILD_MANIFEST.json"), "w") as f:
        json.dump(man, f, indent=2)
    print(f"{a.level}: background {nx}x{ny}x{nz} = {nx*ny*nz} cells, base {d0*1000:.2f} mm")
    print(f"  hull surface cell {d0/2**l_hull*1000:.3f} mm -> "
          f"{L_M/(d0/2**l_hull):.0f} axial faces predicted (floor 400)")
    print(f"  finest (TE box) cell {d_te*1e6:.1f} um -> "
          f"{cells_across_base:.2f} cells across the 1.3109 mm base predicted (floor 8)")


if __name__ == "__main__":
    main()
