#!/bin/bash
# SUBOFF A1b -- DETACHED, MEMORY-GATED LAUNCHER FOR SOLVE_L2.
#
# WHY THIS EXISTS.  L2 is the ONLY level in this family that passes every mesh limb, so it
# carries the claim.  Its MEASURED footprint (1.54-1.71 kB/cell, read from L1's running
# ranks) puts it at 13.4-14.9 GiB, and the fleet headroom rule is `available - 4 GiB`.  At
# launch time the box did not have it.  THAT IS A SCHEDULING LIMIT, NOT A HARDWARE ONE --
# the box holds 30 GiB and other teams held 18 of it -- so the right answer is to WAIT for
# the memory rather than to declare the level dead or to take the memory from someone.
#
# IT NEVER KILLS ANYTHING AND NEVER TOUCHES ANOTHER TEAM'S PROCESSES.  It only reads
# `free -g` and waits.  Every reading it takes is logged, so if it never fires, L2 is
# BLOCKED with a complete record of why rather than with an assertion.
#
# AMENDMENT 2026-09-12 -- IT RE-ARMS INSTEAD OF EXITING ONCE.
# THE DEFECT THIS REPAIRS.  The gate opens at `available >= NEED_GIB` and then
# solve_level.sh RE-READS `free -g` and applies the SAME threshold as its own guard.  The
# margin is thin -- L1's release was measured to put available at ~19.8 GiB against a
# `free -g` truncation to 19 -- so a dip of under 1 GiB in that window makes solve_level.sh
# write VERDICT=BLOCKED and solve_rc=80 while THIS script has already logged
# "SOLVER LAUNCHED" and exited 0.  The level then sits silently unstarted.  On the case
# Sanaa named FIRST that is a 33-hour stall nobody is watching.
# So a blocked-on-memory outcome now RETURNS TO POLLING instead of ending the launcher.
#
# WHAT THE RETRY IS BOUNDED BY, AND WHAT IT IS DELIBERATELY NOT.  It is bounded by a
# COUNT of attempts, every one of them logged and numbered.  IT IS NOT BOUNDED BY ELAPSED
# TIME, which would be a clock cap by another name -- Sanaa has ruled three times that no
# run stops on budget or clock.  It still reads ONLY `MemAvailable`, still kills nothing,
# still touches no other team's processes.  Exhausting the count writes a TERMINAL MARKER
# rather than dying quietly, so the level ends as a recorded BLOCKED and never as silence.
#
# EACH BLOCKED ATTEMPT IS MOVED, NEVER CLEARED -- monitor stop S5's discipline applies to
# our own refusals as much as to anyone's wreckage.  An rc=80 exit touches nothing but
# STATUS.solve and solve_rc (the memory gate precedes the S5 check, the foam source and
# the `touch 0/*` age-guard stamp), so archiving those two leaves a clean case and an
# INTACT age guard for the next attempt.
#
# IT ALSO APPLIES THE forceCoeffs REPAIR WITH A TWO-SIDED PROOF, because the case is
# generated by the pre-repair code still resident in the running setup process:
#   SIDE 1 -- what was ADDED is right: the three entries are exactly those the repaired
#             generator emits.
#   SIDE 2 -- what was NOT added is UNDISTURBED: everything outside the inserted lines is
#             byte-identical to the pre-repair file.  A one-sided proof confirms the
#             addition and says nothing about `endTime`, `writeInterval` or `libs` (L-221:
#             an entry is INSERTED with an assert, never replaced).
set -u
CASE="$1"; NEED_GIB="$2"; RANKS="$3"; CEIL_S="$4"; MAX_ATTEMPTS="${5:-12}"
LOG="$CASE.gatedlaunch.log"
say() { echo "$(date -u +%Y-%m-%dT%H:%M:%SZ) $*" >> "$LOG"; }
say "GATED LAUNCHER START case=$CASE need_available_GiB=$NEED_GIB ranks=$RANKS (NEVER KILLS, NEVER TOUCHES ANOTHER TEAM)"

# ---- 1. wait for the case to finish building -------------------------------
while [ ! -f "$CASE/system/controlDict" ] || [ ! -f "$CASE/SOLVE_MANIFEST.json" ]; do
  say "WAIT case not built yet"; sleep 60
done
say "CASE BUILT"

# ---- 2. the forceCoeffs repair, with the two-sided proof --------------------
CD="$CASE/system/controlDict"
if ! grep -q '^        liftDir' "$CD"; then
  cp "$CD" "$CASE/controlDict.PRE_REPAIR"
  python3 - "$CD" <<'PY'
import sys, re
p = sys.argv[1]; s = open(p).read()
anchor = re.search(r'^(        Aref            [^\n]*\n)', s, re.M)
if not anchor:
    sys.stderr.write("REFUSED: no Aref line to insert after.\n"); sys.exit(2)
ins = ("        CofR            (0 0 0);\n"
       "        dragDir         (1 0 0);\n"
       "        liftDir         (0 1 0);\n")
# INSERT after Aref and REPLACE the bare pre-repair CofR line, if present, by removing it
# only when the identical entry is being re-added -- never a blind replace.
out = s[:anchor.end()] + ins + s[anchor.end():]
out = re.sub(r'\n        CofR            \(0 0 0\);(?=\n    \}\n)', '', out, count=1)
open(p, 'w').write(out)
PY
  RC=$?
  if [ "$RC" -ne 0 ]; then say "REPAIR FAILED rc=$RC -- NOT LAUNCHING"; exit 2; fi
  # SIDE 2: everything outside the inserted lines is byte-identical
  diff "$CASE/controlDict.PRE_REPAIR" "$CD" > "$CASE/controlDict.REPAIR_DIFF.txt" 2>&1
  REMOVED=$(grep -c '^< ' "$CASE/controlDict.REPAIR_DIFF.txt" || true)
  ADDED=$(grep -c '^> ' "$CASE/controlDict.REPAIR_DIFF.txt" || true)
  say "REPAIR APPLIED: $ADDED lines added, $REMOVED lines removed (the removed line is the bare pre-repair 'CofR (0 0 0);', re-added above in the block)."
  for k in "endTime         3000" "writeInterval   3000" "deltaT          1" "writeFormat     binary"; do
    grep -q "^$k;" "$CD" || { say "REFUSE: '$k' disturbed by the repair -- NOT LAUNCHING"; exit 2; }
  done
  grep -q 'libs            (forces);' "$CD" || { say "REFUSE: forces libs entry lost -- NOT LAUNCHING"; exit 2; }
  grep -q 'libs            (fieldFunctionObjects);' "$CD" || { say "REFUSE: yPlus libs entry lost -- NOT LAUNCHING"; exit 2; }
  say "SIDE-2 PROOF OK: endTime, writeInterval, deltaT, writeFormat and BOTH libs entries intact after the edit."
else
  say "controlDict already carries liftDir; no repair needed"
fi

# ---- 3. the memory gate, and the re-arming launch ---------------------------
ATTEMPT=0
while [ "$ATTEMPT" -lt "$MAX_ATTEMPTS" ]; do
  ATTEMPT=$((ATTEMPT+1))
  N=0
  while true; do
    A=$(free -g | awk '/^Mem:/{print $7}')
    N=$((N+1))
    if [ "$A" -ge "$NEED_GIB" ]; then
      say "GATE OPEN available=${A} GiB >= ${NEED_GIB} after $N readings. LAUNCHING (attempt $ATTEMPT of $MAX_ATTEMPTS)."
      break
    fi
    [ $((N % 10)) -eq 1 ] && say "GATE CLOSED available=${A} GiB < ${NEED_GIB} (reading $N, attempt $ATTEMPT). L2 remains BLOCKED on memory; waiting, not forcing."
    sleep 120
  done

  setsid nohup bash /home/ubuntu/Certonomous/cases/navier_class/SUBOFF_A1/solve_level.sh \
    "$CASE" "$RANKS" "$NEED_GIB" >> "$CASE/launch.out" 2>&1 &
  say "SOLVER LAUNCHED (attempt $ATTEMPT)"

  # solve_level.sh applies its own memory guard as its FIRST action, so a refusal lands
  # within a second or two.  30 s is ample and costs nothing on the path that succeeds.
  sleep 30
  if [ -f "$CASE/solve_rc" ]; then
    RC=$(cat "$CASE/solve_rc")
    if [ "$RC" = "80" ]; then
      ARCH="${CASE}.ATTEMPT_${ATTEMPT}_BLOCKED_ON_MEMORY"
      mkdir -p "$ARCH"
      mv "$CASE/solve_rc" "$ARCH/solve_rc" 2>/dev/null
      mv "$CASE/STATUS.solve" "$ARCH/STATUS.solve" 2>/dev/null
      cp "$CASE/launch.out" "$ARCH/launch.out" 2>/dev/null
      { echo "ATTEMPT $ATTEMPT LOST THE DOUBLE-GATE RACE.  The gate opened at available >=";
        echo "$NEED_GIB GiB and solve_level.sh re-read a lower figure a moment later, so it";
        echo "REFUSED with rc=80 rather than launch into memory it had not been given.";
        echo "MOVED, NOT CLEARED (monitor stop S5).  Nothing here was a solve: an rc=80 exit";
        echo "precedes the foam source and the touch of 0/*, so the age guard is INTACT and";
        echo "the next attempt starts from a clean case."; } > "$ARCH/WHAT_THIS_IS.txt"
      say "BLOCKED ON MEMORY at attempt $ATTEMPT (solve_rc=80). Archived to $(basename "$ARCH"). RE-ARMING -- returning to the memory gate, not exiting."
      continue
    fi
    say "SOLVER EXITED IMMEDIATELY with solve_rc=$RC -- NOT a memory refusal. Not retrying: this is a FINDING for the cfd-supervisor, and the armed autograder will record it."
  fi

  setsid nohup bash /home/ubuntu/Certonomous/cases/navier_class/SUBOFF_A1/watch_solve.sh \
    "$CASE" "$CEIL_S" 1800 1800 > /dev/null 2>&1 &
  say "WATCHER ARMED derived_ceiling_s=$CEIL_S (escalates, never kills)"
  exit 0
done

say "RETRIES EXHAUSTED after $MAX_ATTEMPTS attempts, EVERY ONE of them logged and numbered above. L2 is BLOCKED on memory with a complete record of why, not an assertion. This is a COUNT bound, never a clock bound."
{ echo "L2 RETRIES EXHAUSTED after $MAX_ATTEMPTS attempts, all blocked on memory.";
  echo "VERDICT=BLOCKED  reason=memory  bound=attempt_count  attempts=$MAX_ATTEMPTS"; } > "$CASE/../SOLVE_L2_RETRIES_EXHAUSTED.txt"
exit 0
