#!/bin/bash
# SUBOFF A1b -- DETACHED, MEMORY-GATED LAUNCHER FOR SOLVE_L2.
#
# WHY THIS EXISTS.  L2 is the ONLY level in this family that passes every mesh limb, so it
# carries the claim.  Its MEASURED footprint (1.54-1.71 kB/cell, read from L1's running
# ranks) puts it at 13.4-14.9 GiB, and the fleet headroom rule is `available - 4 GiB`.  At
# launch time the box did not have it.  THAT IS A SCHEDULING LIMIT, NOT A HARDWARE ONE --
# the box holds 30 GiB and other teams held 18 of it -- so the right answer is to WAIT for
# the memory rather than to declare the level dead or to take the memory from someone.
#
# IT NEVER KILLS ANYTHING AND NEVER TOUCHES ANOTHER TEAM'S PROCESSES.  It only reads
# `free -g` and waits.  Every reading it takes is logged, so if it never fires, L2 is
# BLOCKED with a complete record of why rather than with an assertion.
#
# IT ALSO APPLIES THE forceCoeffs REPAIR WITH A TWO-SIDED PROOF, because the case is
# generated by the pre-repair code still resident in the running setup process:
#   SIDE 1 -- what was ADDED is right: the three entries are exactly those the repaired
#             generator emits.
#   SIDE 2 -- what was NOT added is UNDISTURBED: everything outside the inserted lines is
#             byte-identical to the pre-repair file.  A one-sided proof confirms the
#             addition and says nothing about `endTime`, `writeInterval` or `libs` (L-221:
#             an entry is INSERTED with an assert, never replaced).
set -u
CASE="$1"; NEED_GIB="$2"; RANKS="$3"; CEIL_S="$4"
LOG="$CASE.gatedlaunch.log"
say() { echo "$(date -u +%Y-%m-%dT%H:%M:%SZ) $*" >> "$LOG"; }
say "GATED LAUNCHER START case=$CASE need_available_GiB=$NEED_GIB ranks=$RANKS (NEVER KILLS, NEVER TOUCHES ANOTHER TEAM)"

# ---- 1. wait for the case to finish building -------------------------------
while [ ! -f "$CASE/system/controlDict" ] || [ ! -f "$CASE/SOLVE_MANIFEST.json" ]; do
  say "WAIT case not built yet"; sleep 60
done
say "CASE BUILT"

# ---- 2. the forceCoeffs repair, with the two-sided proof --------------------
CD="$CASE/system/controlDict"
if ! grep -q '^        liftDir' "$CD"; then
  cp "$CD" "$CASE/controlDict.PRE_REPAIR"
  python3 - "$CD" <<'PY'
import sys, re
p = sys.argv[1]; s = open(p).read()
anchor = re.search(r'^(        Aref            [^\n]*\n)', s, re.M)
if not anchor:
    sys.stderr.write("REFUSED: no Aref line to insert after.\n"); sys.exit(2)
ins = ("        CofR            (0 0 0);\n"
       "        dragDir         (1 0 0);\n"
       "        liftDir         (0 1 0);\n")
# INSERT after Aref and REPLACE the bare pre-repair CofR line, if present, by removing it
# only when the identical entry is being re-added -- never a blind replace.
out = s[:anchor.end()] + ins + s[anchor.end():]
out = re.sub(r'\n        CofR            \(0 0 0\);(?=\n    \}\n)', '', out, count=1)
open(p, 'w').write(out)
PY
  RC=$?
  if [ "$RC" -ne 0 ]; then say "REPAIR FAILED rc=$RC -- NOT LAUNCHING"; exit 2; fi
  # SIDE 2: everything outside the inserted lines is byte-identical
  diff "$CASE/controlDict.PRE_REPAIR" "$CD" > "$CASE/controlDict.REPAIR_DIFF.txt" 2>&1
  REMOVED=$(grep -c '^< ' "$CASE/controlDict.REPAIR_DIFF.txt" || true)
  ADDED=$(grep -c '^> ' "$CASE/controlDict.REPAIR_DIFF.txt" || true)
  say "REPAIR APPLIED: $ADDED lines added, $REMOVED lines removed (the removed line is the bare pre-repair 'CofR (0 0 0);', re-added above in the block)."
  for k in "endTime         3000" "writeInterval   3000" "deltaT          1" "writeFormat     binary"; do
    grep -q "^$k;" "$CD" || { say "REFUSE: '$k' disturbed by the repair -- NOT LAUNCHING"; exit 2; }
  done
  grep -q 'libs            (forces);' "$CD" || { say "REFUSE: forces libs entry lost -- NOT LAUNCHING"; exit 2; }
  grep -q 'libs            (fieldFunctionObjects);' "$CD" || { say "REFUSE: yPlus libs entry lost -- NOT LAUNCHING"; exit 2; }
  say "SIDE-2 PROOF OK: endTime, writeInterval, deltaT, writeFormat and BOTH libs entries intact after the edit."
else
  say "controlDict already carries liftDir; no repair needed"
fi

# ---- 3. the memory gate ----------------------------------------------------
N=0
while true; do
  A=$(free -g | awk '/^Mem:/{print $7}')
  N=$((N+1))
  if [ "$A" -ge "$NEED_GIB" ]; then
    say "GATE OPEN available=${A} GiB >= ${NEED_GIB} after $N readings. LAUNCHING."
    break
  fi
  [ $((N % 10)) -eq 1 ] && say "GATE CLOSED available=${A} GiB < ${NEED_GIB} (reading $N). L2 remains BLOCKED on memory; waiting, not forcing."
  sleep 120
done

# ---- 4. launch, and arm the non-killing watcher ----------------------------
setsid nohup bash /home/ubuntu/Certonomous/cases/navier_class/SUBOFF_A1/solve_level.sh \
  "$CASE" "$RANKS" "$NEED_GIB" >> "$CASE/launch.out" 2>&1 &
say "SOLVER LAUNCHED"
sleep 5
setsid nohup bash /home/ubuntu/Certonomous/cases/navier_class/SUBOFF_A1/watch_solve.sh \
  "$CASE" "$CEIL_S" 1800 1800 > /dev/null 2>&1 &
say "WATCHER ARMED derived_ceiling_s=$CEIL_S (escalates, never kills)"
exit 0
