#!/usr/bin/env python3
"""
SUBOFF_A1 -- BUILD ONE **SOLVE** CASE FROM ONE **BUILT MESH LEVEL**.  It emits a
complete simpleFoam case and RUNS NOTHING.

WHY A SEPARATE DIRECTORY, AND NOT A SOLVE IN PLACE.  Three registered reasons:
  1. Monitor stop S5 (pre-registration 7): "`0/` or a time dir exists at launch =>
     REFUSE to launch.  Never clear the directory."  A guard is satisfied LITERALLY,
     by moving the case, never by disabling it.  A fresh SOLVE_<level>/ has neither.
  2. Commit 0bdf38639: a post-processor writing into a graded tree is invisible to the
     rule-4 age guard.  L1/ and L2/ are the MESH-graded trees whose determinant
     evidence (12.8) must stay byte-untouched; the solver writes somewhere else.
  3. The mesh-build dicts (snappyHexMeshDict, the mesh controlDict) survive intact
     as provenance instead of being overwritten by solve dicts.

THE MESH IS PINNED BY sha256, NOT BY TRUST.  Every polyMesh file is hashed in the
SOURCE and in the DESTINATION and this script REFUSES (exit 2) on any mismatch, so a
"copied mesh" can never quietly be a different mesh (R1b was cleared of exactly this
by 15/15 sha256 pins).

RESIDUAL CONTROL IS DELIBERATELY ABSENT -- see `--end-time` below.

ZERO `assert` (L-332).
"""
import sys
if not __debug__:
    sys.stderr.write("REFUSED: must not run under python3 -O.\n"); sys.exit(2)
import os, re, json, math, shutil, hashlib, argparse, datetime

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import suboff_a1_polymesh as PM                                   # noqa: E402

FT2M = 0.3048
L_M  = 14.291667 * FT2M          # 4.3561001016 m
RE_L = 1.2e7
NU   = 1.0e-6

HDR = """/*--------------------------------*- C++ -*----------------------------------*\\
| SUBOFF_A1 SOLVE -- generated by cases/navier_class/SUBOFF_A1/setup_solve.py |
\\*---------------------------------------------------------------------------*/
FoamFile
{{
    version     2.0;
    format      ascii;
    class       {cls};
    object      {obj};
}}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
"""

MESH_FILES = ("points", "faces", "owner", "neighbour", "boundary")


def w(path, cls, obj, body):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(HDR.format(cls=cls, obj=obj)); f.write(body)


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for blk in iter(lambda: f.read(1 << 20), b""):
            h.update(blk)
    return h.hexdigest()


TIME_RE = re.compile(r"^-?\d+(\.\d+)?$")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--mesh-dir", required=True, help="the BUILT mesh level (read-only)")
    ap.add_argument("--case", required=True, help="the SOLVE case to create")
    ap.add_argument("--level", required=True)
    ap.add_argument("--ranks", type=int, required=True)
    ap.add_argument("--end-time", type=int, required=True,
                    help="SIMPLE iterations.  deltaT=1, so endTime IS the iteration "
                         "count and rule 4's ExecutionTime-count clause reads "
                         "round(endTime/deltaT) == endTime.")
    ap.add_argument("--ct-reference", required=True)
    ap.add_argument("--scratch", required=True)
    a = ap.parse_args()

    # ---- REFUSALS, BEFORE ANYTHING IS WRITTEN ------------------------------
    src_pm = os.path.join(a.mesh_dir, "constant", "polyMesh")
    if not os.path.isdir(src_pm):
        sys.stderr.write(f"REFUSED: no constant/polyMesh under {a.mesh_dir}.\n"); sys.exit(2)
    if not os.path.isfile(a.ct_reference):
        sys.stderr.write(f"REFUSED: CT reference {a.ct_reference} absent.  Gate D2's "
                         "anchor is written BEFORE the freeze (5.3).\n"); sys.exit(2)
    if os.path.exists(a.case):
        for e in os.listdir(a.case):
            if e == "0" or TIME_RE.match(e) or e.startswith("processor") \
               or e in ("log.simpleFoam", "rc", "RC.txt", "postProcessing"):
                sys.stderr.write(
                    f"REFUSED (monitor stop S5): '{e}' already exists in {a.case}.  A "
                    "guard is satisfied by MOVING the case, never by clearing the "
                    "directory.\n")
                sys.exit(2)
    if a.ranks < 1:
        sys.stderr.write("REFUSED: --ranks must be >= 1.\n"); sys.exit(2)
    if a.end_time < 1:
        sys.stderr.write("REFUSED: --end-time must be >= 1.\n"); sys.exit(2)

    # ---- RULE 3 FIRST, then the two areas ---------------------------------
    plant = PM.plant_and_verify(a.scratch)
    s_hull = PM.patch_area(a.mesh_dir, "hull", patches=("hull", "sail"))
    s_sail = PM.patch_area(a.mesh_dir, "sail", patches=("hull", "sail"))
    aref = s_hull + s_sail
    bnd = PM.read_boundary(a.mesh_dir)
    for p in ("inlet", "outlet", "farfield", "symm", "hull", "sail"):
        if p not in bnd:
            sys.stderr.write(f"REFUSED: patch '{p}' absent from the built mesh.\n")
            sys.exit(2)
    if bnd["symm"]["type"] != "symmetryPlane":
        sys.stderr.write("REFUSED: 'symm' is not a symmetryPlane; the half-model "
                         "assumption (3.5) does not hold.\n"); sys.exit(2)

    # ---- copy the mesh and PIN IT ------------------------------------------
    dst_pm = os.path.join(a.case, "constant", "polyMesh")
    os.makedirs(dst_pm, exist_ok=True)
    pins = {}
    for fn in MESH_FILES:
        s = os.path.join(src_pm, fn)
        if not os.path.isfile(s):
            sys.stderr.write(f"REFUSED: {fn} missing from the source polyMesh.\n")
            sys.exit(2)
        d = os.path.join(dst_pm, fn)
        shutil.copyfile(s, d)
        hs, hd = sha256(s), sha256(d)
        if hs != hd:
            sys.stderr.write(f"REFUSED: sha256 mismatch on {fn} after copy.\n"); sys.exit(2)
        pins[fn] = hs
    for fn in ("cellZones", "faceZones", "pointZones"):
        s = os.path.join(src_pm, fn)
        if os.path.isfile(s):
            shutil.copyfile(s, os.path.join(dst_pm, fn))
            pins[fn] = sha256(s)
    os.makedirs(os.path.join(a.case, "constant", "triSurface"), exist_ok=True)
    for stl in ("hull.stl", "sail.stl"):
        s = os.path.join(a.mesh_dir, "constant", "triSurface", stl)
        if os.path.isfile(s):
            shutil.copyfile(s, os.path.join(a.case, "constant", "triSurface", stl))

    # ---- the flow condition -------------------------------------------------
    u = RE_L * NU / L_M
    # Spalding/Spalart-Rumsey freestream convention for k-omega SST external flow:
    #   k_inf = 1e-6 U^2 ;  omega_inf = 5 U / L  =>  nut_inf/nu ~ 2.4
    # [INFERRED] -- a working convention from this lane's knowledge; NO source for it
    # is on disk, and rule 15 forbids dressing that up as a citation.
    k_inf = 1.0e-6 * u * u
    om_inf = 5.0 * u / L_M
    nut_inf = k_inf / om_inf

    w(os.path.join(a.case, "constant", "transportProperties"), "dictionary",
      "transportProperties", f"transportModel  Newtonian;\nnu              {NU:.10g};\n")
    for obj in ("turbulenceProperties", "momentumTransport"):
        w(os.path.join(a.case, "constant", obj), "dictionary", obj,
          "simulationType RAS;\n"
          "RAS { RASModel kOmegaSST; model kOmegaSST; turbulence on; printCoeffs on; }\n")

    # ---- 0/ ------------------------------------------------------------------
    def field(obj, cls, dims, internal, bcs):
        body = (f"dimensions      {dims};\ninternalField   uniform {internal};\n"
                "boundaryField\n{\n")
        for p, spec in bcs:
            body += f"    {p}\n    {{\n{spec}    }}\n"
        body += "}\n"
        w(os.path.join(a.case, "0", obj), cls, obj, body)

    ui = f"({u:.10g} 0 0)"
    field("U", "volVectorField", "[0 1 -1 0 0 0 0]", ui, [
        ("inlet", f"        type            fixedValue;\n        value           uniform {ui};\n"),
        ("outlet", f"        type            inletOutlet;\n        inletValue      uniform (0 0 0);\n        value           uniform {ui};\n"),
        ("farfield", "        type            slip;\n"),
        ("symm", "        type            symmetryPlane;\n"),
        ("hull", "        type            noSlip;\n"),
        ("sail", "        type            noSlip;\n"),
    ])
    field("p", "volScalarField", "[0 2 -2 0 0 0 0]", "0", [
        ("inlet", "        type            zeroGradient;\n"),
        ("outlet", "        type            fixedValue;\n        value           uniform 0;\n"),
        ("farfield", "        type            slip;\n"),
        ("symm", "        type            symmetryPlane;\n"),
        ("hull", "        type            zeroGradient;\n"),
        ("sail", "        type            zeroGradient;\n"),
    ])
    field("k", "volScalarField", "[0 2 -2 0 0 0 0]", f"{k_inf:.10g}", [
        ("inlet", f"        type            fixedValue;\n        value           uniform {k_inf:.10g};\n"),
        ("outlet", f"        type            inletOutlet;\n        inletValue      uniform {k_inf:.10g};\n        value           uniform {k_inf:.10g};\n"),
        ("farfield", "        type            slip;\n"),
        ("symm", "        type            symmetryPlane;\n"),
        ("hull", f"        type            kqRWallFunction;\n        value           uniform {k_inf:.10g};\n"),
        ("sail", f"        type            kqRWallFunction;\n        value           uniform {k_inf:.10g};\n"),
    ])
    field("omega", "volScalarField", "[0 0 -1 0 0 0 0]", f"{om_inf:.10g}", [
        ("inlet", f"        type            fixedValue;\n        value           uniform {om_inf:.10g};\n"),
        ("outlet", f"        type            inletOutlet;\n        inletValue      uniform {om_inf:.10g};\n        value           uniform {om_inf:.10g};\n"),
        ("farfield", "        type            slip;\n"),
        ("symm", "        type            symmetryPlane;\n"),
        ("hull", f"        type            omegaWallFunction;\n        value           uniform {om_inf:.10g};\n"),
        ("sail", f"        type            omegaWallFunction;\n        value           uniform {om_inf:.10g};\n"),
    ])
    # nutUSpaldingWallFunction is REGISTERED by pre-registration 5.2 and 11.5 and is
    # the arming condition of Gate W (11.2): a wall patch carrying anything else
    # makes Gate W BLOCKED, never PASS.
    field("nut", "volScalarField", "[0 2 -1 0 0 0 0]", f"{nut_inf:.10g}", [
        ("inlet", f"        type            calculated;\n        value           uniform {nut_inf:.10g};\n"),
        ("outlet", f"        type            calculated;\n        value           uniform {nut_inf:.10g};\n"),
        ("farfield", f"        type            calculated;\n        value           uniform {nut_inf:.10g};\n"),
        ("symm", "        type            symmetryPlane;\n"),
        ("hull", "        type            nutUSpaldingWallFunction;\n        value           uniform 0;\n"),
        ("sail", "        type            nutUSpaldingWallFunction;\n        value           uniform 0;\n"),
    ])

    # ---- system/ -------------------------------------------------------------
    # writeInterval == endTime: ONE write, at endTime.  A writeInterval that does not
    # divide endTime writes NO fields at all, which the completion rule would read as
    # an incomplete run.
    w(os.path.join(a.case, "system", "controlDict"), "dictionary", "controlDict",
      f"""application     simpleFoam;
startFrom       startTime;
startTime       0;
stopAt          endTime;
endTime         {a.end_time};
deltaT          1;
writeControl    timeStep;
writeInterval   {a.end_time};
purgeWrite      0;
writeFormat     binary;
writePrecision  8;
writeCompression off;
timeFormat      general;
timePrecision   6;
runTimeModifiable false;

functions
{{
    forceCoeffs
    {{
        type            forceCoeffs;
        libs            (forces);
        writeControl    timeStep;
        writeInterval   1;
        log             yes;
        patches         (hull sail);
        rho             rhoInf;
        rhoInf          1;          // incompressible: forces are kinematic, and CT
        magUInf         {u:.10g};   // is a ratio, so rhoInf cancels exactly.
        lRef            {L_M:.10g};
        Aref            {aref:.10g}; // MEASURED half-model wetted area of this level
        CofR            (0 0 0);
    }}
    yPlus
    {{
        type            yPlus;
        libs            (fieldFunctionObjects);
        writeFields     yes;
        executeControl  writeTime;
        writeControl    writeTime;
        log             yes;
    }}
    residuals
    {{
        type            solverInfo;
        libs            (utilityFunctionObjects);
        writeControl    timeStep;
        writeInterval   1;
        fields          (p U k omega);
    }}
}}
""")
    w(os.path.join(a.case, "system", "fvSchemes"), "dictionary", "fvSchemes",
      "ddtSchemes { default steadyState; }\n"
      "gradSchemes { default cellLimited Gauss linear 1; }\n"
      "divSchemes { default none; div(phi,U) bounded Gauss linearUpwind grad(U);\n"
      "  div(phi,k) bounded Gauss limitedLinear 1;\n"
      "  div(phi,omega) bounded Gauss limitedLinear 1;\n"
      "  div((nuEff*dev2(T(grad(U))))) Gauss linear; }\n"
      "laplacianSchemes { default Gauss linear corrected; }\n"
      "interpolationSchemes { default linear; }\nsnGradSchemes { default corrected; }\n"
      "wallDist { method meshWave; }\n")
    # NO residualControl.  The registered completion rule (7) requires
    #   last time == endTime   AND   ExecutionTime count == round(endTime/deltaT),
    # and a residualControl exit satisfies NEITHER: it stops early and writes at a
    # time below endTime.  Convergence is judged by the registered plateau test
    # (S3: a regression over the final 500 iterations) and by the residual record,
    # never by the solver stopping itself.
    w(os.path.join(a.case, "system", "fvSolution"), "dictionary", "fvSolution",
      "solvers\n{\n"
      "    p { solver GAMG; tolerance 1e-8; relTol 0.01; smoother GaussSeidel;\n"
      "        nCellsInCoarsestLevel 100; }\n"
      "    \"(U|k|omega)\" { solver smoothSolver; smoother symGaussSeidel;\n"
      "        nSweeps 2; tolerance 1e-8; relTol 0.1; }\n"
      "}\n"
      "SIMPLE\n{\n    nNonOrthogonalCorrectors 2;\n    consistent yes;\n"
      "    pRefCell 0;\n    pRefValue 0;\n}\n"
      "relaxationFactors { equations { U 0.9; \".*\" 0.9; } }\n")
    w(os.path.join(a.case, "system", "decomposeParDict"), "dictionary",
      "decomposeParDict", f"numberOfSubdomains {a.ranks};\nmethod scotch;\n")

    with open(a.ct_reference) as f:
        ref = json.load(f)

    man = {
        "level": a.level, "kind": "SOLVE case built from a BUILT mesh level",
        "written_utc": datetime.datetime.now(datetime.timezone.utc)
                       .strftime("%Y-%m-%dT%H:%M:%SZ"),
        "mesh_dir": os.path.abspath(a.mesh_dir),
        "polyMesh_sha256": pins,
        "ranks": a.ranks, "endTime": a.end_time, "deltaT": 1,
        "condition": {"Re_L": RE_L, "L_m": L_M, "nu": NU, "U_m_s": u,
                      "k_inf": k_inf, "omega_inf": om_inf, "nut_inf": nut_inf,
                      "nut_over_nu_freestream": nut_inf / NU},
        "Aref_m2_MEASURED": aref, "S_hull_m2": s_hull, "S_sail_m2": s_sail,
        "rule3_plant": plant,
        "CT_ref": ref["CT_ref"], "GATE_D2_BAND": ref["GATE_D2_BAND"],
        "wall_treatment": "nutUSpaldingWallFunction on hull and sail (5.2, 11.5)",
        "residualControl": "ABSENT BY REGISTRATION -- see setup_solve.py; an early "
                           "residual exit violates the completion rule's "
                           "last==endTime and ExecutionTime-count clauses.",
    }
    with open(os.path.join(a.case, "SOLVE_MANIFEST.json"), "w") as f:
        json.dump(man, f, indent=2)
    print(json.dumps({k: man[k] for k in
                      ("level", "ranks", "endTime", "Aref_m2_MEASURED", "S_hull_m2",
                       "S_sail_m2", "condition", "CT_ref", "GATE_D2_BAND",
                       "rule3_plant")}, indent=2))


if __name__ == "__main__":
    main()
