#!/usr/bin/env python3
"""Append the supervisor's research proposals to the agenda docket.

Every one is status 'proposed'. Nothing runs without the click.

Each proposal names a FALSIFIABLE hypothesis, not a task. "Investigate X" is a
chore; "X is caused by Y, and here is the measurement that would prove it is
not" is a research question. Where I have a specific mechanism in mind I state
it, so that being wrong is cheap and visible.
"""
import json
import pathlib

DOCKET = pathlib.Path("/home/ubuntu/Certonomous/demo-output/website/agenda/docket.json")
NOW = "2026-07-29T20:15:00Z"

NEW = [
    {
        "id": "r4-a1-idx6-wall-function-branch",
        "objective": (
            "Test whether A1's sign-flipped leading-edge shape derivative (idx6) is "
            "caused by discrete non-differentiability at the wall-function switching "
            "threshold, by measuring whether leading-edge cells cross that threshold "
            "under the finite-difference perturbation"
        ),
        "rationale": (
            "A1's CD/shape check fails on one component: idx6, the leading-edge combo "
            "mode, is sign-flipped and accounts for 82.7 percent of the squared-error "
            "norm. It is step-independent, survives a 3.65x mesh refinement, and the "
            "frozen-wall-distance mechanism was measured to contribute exactly zero. "
            "Root cause is unidentified and this is the deepest open question in the "
            "ladder. A mechanism nobody has tested: the Spalart-Allmaras wall-function "
            "branch is a discrete switch on the near-wall cell state. If leading-edge "
            "cells cross that switch between the plus and minus finite-difference "
            "perturbations, the function being differenced is not continuous there, so "
            "the finite difference is estimating the slope across a step rather than a "
            "derivative, and the adjoint, which linearizes one branch only, is right "
            "while the check is wrong. That would explain step-independence, which a "
            "truncation-error story cannot, and it would explain why only the leading "
            "edge misbehaves while mid-chord and aft components agree to 1.5-6.4 "
            "percent. The measurement is cheap: instrument the near-wall cell state at "
            "each perturbed configuration and count threshold crossings. If none cross, "
            "the hypothesis dies and we have eliminated it for good."
        ),
        "citations": [
            "Certonomous PROOF.md sections 8.2 and 12, leading-edge localisation of the A1 defect",
            "Certonomous DAFoam Case Status, cross-rung finding 2",
            "Spalart & Allmaras (1992), one-equation turbulence model for aerodynamic flows",
        ],
        "est_core_min": 25.0,
        "cost_basis": "estimate, from A1's measured 3.51 core-min per full check_totals cycle",
        "expected_knowledge_gain": (
            "Either the root cause of the lab's longest-standing gradient defect, or the "
            "elimination of the most plausible remaining mechanism. Both outcomes end a "
            "line of inquiry rather than extending it. If confirmed, it also tells every "
            "future user of this stack that a wall-function case cannot be gradient-"
            "verified by finite difference at the wall without checking for branch "
            "crossings first, which is a transferable result, not a local fix."
        ),
        "source_kind": "gate",
        "status": "proposed",
        "created_at": NOW,
        "decided_at": None,
        "decision_note": None,
    },
    {
        "id": "r4-b3-nonfinite-primal-state",
        "objective": (
            "Test whether B3's adjoint failure (PETSc DIVERGED_NANORINF at iteration 0) "
            "is caused by a non-finite value already present in the converged primal "
            "state, by scanning every primal field cell-by-cell for non-finite entries "
            "before the adjoint is launched"
        ),
        "rationale": (
            "B3's discrete adjoint dies with DIVERGED_NANORINF at GMRES iteration 0, "
            "reproduced identically across four configurations: two primal convergence "
            "levels, two objective types, and two ILU fill levels. Mesh quality was "
            "checked and cleared. Failing at iteration zero, before any GMRES progress, "
            "means the non-finite value is present in the operator or the right-hand "
            "side at the moment they are assembled, not generated by the solve. The "
            "adjoint linearizes about the converged primal state, so a single cell "
            "holding an inf or NaN in any primal field would produce exactly this "
            "signature. A converged residual norm does not exclude it: the norm is a sum "
            "over cells, and a non-finite entry in a field the residual does not weight "
            "can sit there unnoticed. That the failure is invariant to convergence level, "
            "objective and preconditioner is the strongest evidence for it - all three "
            "are downstream of the state, and none of them would change a poisoned input."
        ),
        "citations": [
            "Certonomous DAFoam Case Status, Ladder B3 stage 3 blocker",
            "PETSc users manual, KSPConvergedReason -9 DIVERGED_NANORINF",
        ],
        "est_core_min": 8.0,
        "cost_basis": "estimate, field scan is IO-bound, no solve required to test the hypothesis",
        "expected_knowledge_gain": (
            "A cheap test of the only hypothesis that explains all four reproductions at "
            "once. If it holds, B3 unblocks and the lab gains a preflight check that "
            "belongs in front of every adjoint we ever run. If it fails, we have "
            "eliminated the state and the search moves to the operator assembly, which "
            "is where it should go next anyway."
        ),
        "source_kind": "gate",
        "status": "proposed",
        "created_at": NOW,
        "decided_at": None,
        "decision_note": None,
    },
    {
        "id": "r4-coarse-adjoint-prolongation",
        "objective": (
            "Determine whether a gradient computed on a coarse adjoint mesh is accurate "
            "enough to drive optimization on a fine primal mesh, by measuring gradient "
            "direction agreement (cosine similarity, not just magnitude) between coarse "
            "and fine adjoints on the one case where both are affordable"
        ),
        "rationale": (
            "The adjoint memory wall blocks four cases and the reflex response is to buy "
            "a bigger machine. That may be the wrong purchase. Optimization does not need "
            "an accurate gradient magnitude; it needs an accurate gradient DIRECTION, "
            "because the line search recovers the step length. If the coarse-mesh adjoint "
            "points the same way as the fine-mesh adjoint, the wall stops being a blocker "
            "and becomes a cost-management technique, and it does so on hardware we "
            "already own. A4 already exercises this pattern informally, using a 2,777-cell "
            "adjoint mesh against a 45,760-cell primal, but nobody has measured whether "
            "the resulting direction is right - only that its magnitude lands within "
            "10.04 percent on a single scalar design variable, which says nothing about "
            "direction in a many-variable space. The measurement wanted is cosine "
            "similarity across the full design-variable vector at several coarsening "
            "ratios, on a case small enough that the fine-mesh adjoint is affordable as "
            "ground truth."
        ),
        "citations": [
            "Certonomous DAFoam Adjoint Memory Envelope (D3), cross-rung finding 1",
            "Certonomous DAFoam Case Status, A4 coarse-adjoint-mesh disclosure",
            "Nocedal & Wright, Numerical Optimization, on line-search tolerance to inexact gradients",
        ],
        "est_core_min": 120.0,
        "cost_basis": (
            "estimate, several full adjoint cycles at A1/A5 scale plus one fine-mesh "
            "reference; wide error bar because the fine reference may itself hit the wall"
        ),
        "expected_knowledge_gain": (
            "A direct answer to whether the memory wall requires capital expenditure or "
            "an algorithmic change. This is the proposal on this docket with the clearest "
            "commercial consequence, and the answer is the same regardless of which way "
            "it comes out: either we can optimize large geometries on this box today, or "
            "we have a measured, defensible basis for a hardware case rather than an "
            "assumed one."
        ),
        "source_kind": "measurement",
        "status": "proposed",
        "created_at": NOW,
        "decided_at": None,
        "decision_note": None,
    },
    {
        "id": "r4-m6-wall-treatment-plateau",
        "objective": (
            "Test whether the ONERA M6 primal residual plateau at 1.02e-06 is caused by "
            "wall resolution sitting in the buffer layer, by re-running the case on a "
            "wall-resolved mesh (yPlus below 1) and on a clean wall-function mesh (yPlus "
            "above 30) and observing whether the plateau moves"
        ),
        "rationale": (
            "The M6 act ships as a documented failure: the primal ran its full 3,000 "
            "iterations and missed its own 1e-08 gate at 1.02e-06. The turbulence "
            "equation alone is responsible - momentum, energy and pressure all satisfy "
            "the gate at 1e-07 to 1e-08. The residual reached 1e-06 inside the first "
            "quarter of the run and changed by a factor of 0.997 across the entire final "
            "third, so it is a fixed point rather than slow convergence and more "
            "iterations cannot help. The mesh has yPlus spanning 5.21 to 103.5 with mean "
            "33.8, which straddles the buffer layer: too coarse to resolve the viscous "
            "sublayer, too fine for a clean wall function. A turbulence equation that "
            "cannot settle while every other equation does is consistent with the near-"
            "wall treatment being ambiguous across the surface. This is a hypothesis, "
            "not a conclusion, and the run that produced it does not test it. Two meshes "
            "settle it: if the plateau clears on either, wall treatment is the cause; if "
            "it survives both, the cause is elsewhere and we have narrowed it sharply."
        ),
        "citations": [
            "Certonomous A3 ONERA M6 plateau record, 2026-07-29",
            "AGARD AR-138 and NASA Turbulence Modeling Resource, ONERA M6 case 2308",
        ],
        "est_core_min": 90.0,
        "cost_basis": (
            "measured, from this case's own 498-second solve stage at 4 ranks, doubled "
            "for two meshes plus mesh generation"
        ),
        "expected_knowledge_gain": (
            "Converts a documented failure into either a validated ninth case with a real "
            "Cp comparison against AGARD, or a sharper failure with wall treatment "
            "eliminated. The Cp gate is currently not merely unmet but unreachable, "
            "because the solver raises before writing a field, so this is the only route "
            "to a pressure comparison on this case at all."
        ),
        "source_kind": "gate",
        "status": "proposed",
        "created_at": NOW,
        "decided_at": None,
        "decision_note": None,
    },
    {
        "id": "r4-band-tightening-hump",
        "objective": (
            "Determine how tight the model-form uncertainty band on hump reattachment can "
            "be made while still containing the experiment, by replacing the extremal "
            "anisotropy limiting states with physically weighted perturbations and "
            "measuring the containment/width trade-off curve"
        ),
        "rationale": (
            "The D9 result is the lab's flagship epistemic claim: the band contains the "
            "known +13.95 percent reattachment error, and the prediction that it would "
            "was written before the runs. But the band spans 0.5278 to 1.2534, a factor "
            "of 2.4, and the record says plainly that containment is necessary and not "
            "sufficient. The band's width comes from channel 3 taking the barycentric "
            "map's extremal limiting states, which are bounds by construction and are not "
            "predictions. The open question, stated in the record itself, is not whether "
            "the band contains but how tight it can be made while still containing. That "
            "is a research question with a curve as its answer, not a single number: "
            "sweep the perturbation magnitude from extremal down toward zero and find "
            "where containment breaks. The point at which it breaks is itself the "
            "interesting result, because it measures how much of the band is doing real "
            "work. Channel 2, documented model bias from the literature, was never "
            "incorporated and belongs in this study."
        ),
        "citations": [
            "Certonomous F6a epistemic band record and its pre-registered prediction",
            "Emory, Iaccarino et al., eigenvalue perturbation and the barycentric map",
            "NASA Turbulence Modeling Resource, wall-mounted hump experiment",
        ],
        "est_core_min": 200.0,
        "cost_basis": (
            "estimate, roughly a dozen hump solves at the measured 51,626-cell case cost, "
            "plus the two channel-1 models that never completed"
        ),
        "expected_knowledge_gain": (
            "Moves the flagship claim from 'our band contains a real error' to 'our band "
            "contains a real error and here is how tight it can be', which is the "
            "difference between a demonstration and a product. Also closes a soft edge in "
            "the current result: kOmega defines the lower edge of channel 1 and is "
            "unconverged, so the published range rests partly on a number that did not "
            "meet its own gate."
        ),
        "source_kind": "challenge",
        "status": "proposed",
        "created_at": NOW,
        "decided_at": None,
        "decision_note": None,
    },
    {
        "id": "r4-asymptotic-range-ladders",
        "objective": (
            "Determine whether the non-asymptotic verdicts on the Ahmed body and B-52 "
            "refinement ladders come from an insufficient refinement ratio or from "
            "genuinely non-monotone grid convergence, by re-running each with a constant "
            "ratio and reporting the observed order of accuracy"
        ),
        "rationale": (
            "Two headline geometries report ladders not in the asymptotic range, and both "
            "consequently carry conservative bands rather than extrapolated ones - the "
            "B-52 at plus or minus 0.0063 on a Cd of 0.0472, which is 13 percent, and the "
            "Ahmed body downgraded from VALIDATED to SOLVER-BACKED specifically because "
            "its ladder was inconclusive. The existing ladders use unequal and in places "
            "small cell-count ratios, and the B-52's rungs are non-monotone: 0.0551, "
            "0.0448, 0.0491, 0.0472, 0.0496, 0.0523 as cells rise. Standard practice "
            "requires a constant refinement ratio to compute an observed order p at all, "
            "and without p there is no Richardson extrapolation and no grid-convergence "
            "index. The current verdicts may therefore be reporting a defect in the "
            "experiment design rather than in the solutions. This is worth settling "
            "because it is the difference between two flagship bodies being VALIDATED and "
            "not."
        ),
        "citations": [
            "Roache, Verification and Validation in Computational Science and Engineering",
            "ASME V&V 20 standard on grid-convergence index",
            "Certonomous geometry-study B-52 and Ahmed body mesh-sensitivity records",
        ],
        "est_core_min": 400.0,
        "cost_basis": (
            "measured, from the B-52's own 1,267-second and motorBike's 1,022-second "
            "rebuild times; three constant-ratio rungs per body on two bodies"
        ),
        "expected_knowledge_gain": (
            "Either an observed order of accuracy and a defensible extrapolated value for "
            "the lab's two most-filmed geometries, or hard evidence that these flows do "
            "not converge monotonically on this mesh family, which is itself a real "
            "finding about snapped-hex meshes on complex geometry and worth publishing."
        ),
        "source_kind": "measurement",
        "status": "proposed",
        "created_at": NOW,
        "decided_at": None,
        "decision_note": None,
    },
]


def main() -> int:
    d = json.loads(DOCKET.read_text())
    existing = {p["id"] for p in d["proposals"]}
    added = [p for p in NEW if p["id"] not in existing]
    if not added:
        print("  all proposals already present, nothing added")
        return 0
    d["proposals"].extend(added)
    d["generated_at"] = NOW
    DOCKET.write_text(json.dumps(d, indent=1) + "\n")
    for p in added:
        print(f"  + {p['id']:38s} {p['est_core_min']:6.0f} core-min  [{p['status']}]")
    print(f"\n  docket now holds {len(d['proposals'])} proposals")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
