#!/usr/bin/env python3
"""write_report_tables.py -- generate every numeric table the K0cX results
record quotes, so that no figure in it is retyped by hand.

    python3 write_report_tables.py      # writes REPORT_TABLES.md

Reads gate_k0cx.json and diagnostics_k0cx.json and nothing else.  It holds no
reference value and no measurement of its own; if either input is missing it
exits 2 rather than printing a table with a gap in it.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
MODELS = {"SST": "kOmegaSST", "KE": "kEpsilon", "LS": "LaunderSharmaKE",
          "LAM": "laminar"}


def main():
    gp = os.path.join(HERE, "gate_k0cx.json")
    dp = os.path.join(HERE, "diagnostics_k0cx.json")
    for p in (gp, dp):
        if not os.path.isfile(p):
            sys.stderr.write(f"REFUSE: {p} not found.\n")
            return 2
    g, d = json.load(open(gp)), json.load(open(dp))
    M, L = [], []

    def w(s=""):
        L.append(s)

    w("# K0cX report tables -- generated by write_report_tables.py\n")
    w(f"Generated from `gate_k0cx.json` ({g['generated_utc']}) and "
      "`diagnostics_k0cx.json`. Nothing here was retyped.\n")

    # ---- headline per model ------------------------------------------------
    w("\n## Verdicts\n")
    w("| model | verdict | rows failed | convergence refusals |")
    w("| --- | --- | ---: | --- |")
    for t in ("SST", "KE", "LS", "LAM"):
        gg = g["graded"][t]
        v = "control, NOT counted" if t == "LAM" else gg["verdict"]
        w(f"| {MODELS[t]} | **{v}** | {gg['n_fail']} of {gg['n_rows']} | "
          f"{'; '.join(gg['convergence_refusals']) or 'none'} |")
    w(f"\n**Rung: {g['rung_verdict']} -- {g['total_failed_rows']} of "
      f"{g['total_graded_rows']} graded rows failed.**\n")

    # ---- one row-by-row table per model, with the laminar control beside ----
    for t in ("SST", "KE", "LS"):
        w(f"\n## {MODELS[t]} -- every row, with the laminar control beside it\n")
        w("| Ra | row | quantity | reference | coarse | **fine** | deviation | "
          "band | verdict | mesh moved | laminar value | laminar verdict |")
        w("| ---: | --- | --- | ---: | ---: | ---: | ---: | ---: | --- | --- | ---: | --- |")
        for r in g["graded"][t]["rows"]:
            lam = g["laminar_rows"].get(f"{r['rung']}/{r['tag']}")
            w(f"| {r['rung']} | {r['tag']} | {r['quantity']} | {r['reference']:.4g} | "
              f"{r.get('coarse', float('nan')):.4g} | **{r['value']:.4g}** | "
              f"{r['deviation']:.4g} | {r['band']:.4g} {r['unit']} | "
              f"**{r['verdict']}** | "
              f"{'toward' if r.get('mesh_moved_toward_experiment') else 'AWAY'} | "
              f"{lam['value']:.4g} | {lam['verdict']} |")

    # ---- laminar control's own 20 rows -------------------------------------
    w("\n## The laminar control's own rows (counted toward no model)\n")
    w("| Ra | row | quantity | reference | value | deviation | band | verdict |")
    w("| ---: | --- | --- | ---: | ---: | ---: | ---: | --- |")
    for k in sorted(g["laminar_rows"], key=lambda s: (s.split("/")[0],
                                                      int(s.split("/R")[1]))):
        r = g["laminar_rows"][k]
        w(f"| {r['rung']} | {r['tag']} | {r['quantity']} | {r['reference']:.4g} | "
          f"{r['value']:.4g} | {r['deviation']:.4g} | {r['band']:.4g} "
          f"{r['unit']} | **{r['verdict']}** |")

    # ---- discrimination -----------------------------------------------------
    w("\n## Discrimination against the laminar control\n")
    w("| model | D-a: model PASSES, laminar FAILS | count | D-b: separated by "
      "more than the band | count | both fail |")
    w("| --- | --- | ---: | --- | ---: | ---: |")
    for t in ("SST", "KE", "LS"):
        dd = g["discrimination"][t]
        w(f"| {MODELS[t]} | {', '.join(dd['Da']) or '**EMPTY**'} | {len(dd['Da'])} | "
          f"{', '.join(dd['Db']) or '**EMPTY**'} | {len(dd['Db'])} | "
          f"{len(dd['both_fail'])} |")

    # ---- F3 -----------------------------------------------------------------
    w("\n## F3 relaminarisation diagnostics -- per case\n")
    w("K0cS fine mesh, for comparison: `nu_t/nu` **6.1e-04**, **25 996** "
      "bounding-k events of 40 000 iterations, implied `fmu` **0.034**, peak "
      "Reynolds shear stress **3.89e-17**.\n")
    w("| case | model | cells | first cell | `nu_t/nu` max | `k` max | `fmu` max | "
      "bounding k | bounding eps/omega | peak u'v' | y+ max | wall alphat/alpha | "
      "relaminarised |")
    w("| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- |")
    for c, v in d["F3_relaminarisation"]["cases"].items():
        f = v["fmu_implied_max"]
        be = v["bounding_epsilon_events"] or 0
        bo = v["bounding_omega_events"] or 0
        w(f"| {c} | {v['model']} | {v['cells']} | {v['mesh']} | "
          f"{v['nut_over_nu_max']:.4g} | {(v['k_max'] or 0):.3g} | "
          f"{('%.4g' % f) if f is not None else '-'} | {v['bounding_k_events']:.0f} | "
          f"{be:.0f} / {bo:.0f} | {(v['uv_peak_midheight'] or 0):.3g} | "
          f"{v['yplus_max']:.3f} | {v['wall_alphat_over_alpha']:.3g} | "
          f"**{'YES' if v['relaminarised'] else 'no'}** |")

    # ---- F2 -----------------------------------------------------------------
    w("\n## F2 mesh trend on core stratification\n")
    w("K0cS, for comparison: kOmegaSST moved **AWAY by 0.080**, "
      "LaunderSharmaKE **AWAY by 0.158**, kEpsilon grid-converged (0.004).\n")
    w("| model / Ra | S coarse | S fine | S extra-fine | deviation coarse | "
      "deviation fine | deviation x-fine | net | total movement |")
    w("| --- | ---: | ---: | ---: | ---: | ---: | ---: | --- | ---: |")
    for k, v in d["F2_mesh_trend_on_S"].items():
        s = {l["level"]: l["S"] for l in v["levels"]}
        dv = dict(zip([l["level"] for l in v["levels"]],
                      v["deviations_from_reference"]))
        def g_(m, key):
            return f"{m[key]:.4f}" if key in m else "-"
        w(f"| {k} | {g_(s,'c')} | {g_(s,'f')} | {g_(s,'x')} | {g_(dv,'c')} | "
          f"{g_(dv,'f')} | {g_(dv,'x')} | **{v['net_direction']}** | "
          f"{abs(v['total_movement']):.4f} |")

    # ---- F4 -----------------------------------------------------------------
    w("\n## F4 turbulent Prandtl number, at the value MEASURED in this cavity\n")
    w("K0cS, for comparison: Prt 0.85 -> 1.28 moved hot-wall Nusselt by "
      "**-1.75 %** on the square cavity.\n")
    w("| case | model | Ra | Prt | Nu base | Nu at measured Prt | **dNu** | "
      "S base | S at measured Prt | dS | `nu_t/nu` base -> sens | "
      "larger than the square cavity's 1.75 %? |")
    w("| --- | --- | --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | --- | --- |")
    for c, v in d["F4_prt_sensitivity"].items():
        w(f"| {c} | {v['model']} | {v['rung']} | {v['Prt_base']:.3f} -> "
          f"{v['Prt_measured']:.3f} ({v['Prt_change_pct']:+.1f} %) | "
          f"{v['Nu_base']:.4f} | {v['Nu_sens']:.4f} | **{v['dNu_pct']:+.2f} %** | "
          f"{v['S_base']:.4f} | {v['S_sens']:.4f} | {v['dS']:+.4f} | "
          f"{v['nut_base']:.2f} -> {v['nut_sens']:.2f} | "
          f"**{'YES' if v['larger_than_square_cavity'] else 'NO'}** |")

    # ---- C-REPRO ------------------------------------------------------------
    w("\n## C-REPRO: this build against K0cT's published numbers (threshold 1 %)\n")
    w("| this case | K0cT case | S here | S there | rel | Nu here | Nu there | "
      "rel | worst | within 1 %? |")
    w("| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- |")
    for c, v in d["C_REPRO"].items():
        if c.startswith("_"):
            continue
        w(f"| {c} | {v['k0ct_case']} | {v['S'][0]:.5f} | {v['S'][1]:.5f} | "
          f"{v['S'][2]:.3f} % | {v['Nu_avg'][0]:.4f} | {v['Nu_avg'][1]:.4f} | "
          f"{v['Nu_avg'][2]:.3f} % | {v['worst_rel_pct']:.3f} % | "
          f"**{'OK' if v['within_1pct'] else 'EXCEEDS -- BUILD DEFECT'}** |")

    # ---- convergence --------------------------------------------------------
    w("\n## Convergence, on the registered criterion (Nu p2p < 0.02 %, "
      "S p2p < 0.001, |Uy| p2p < 0.02 %)\n")
    w("| case | samples | Nu p2p % | S p2p | Uy p2p % | S window | verdict |")
    w("| --- | ---: | ---: | ---: | ---: | --- | --- |")
    for c in sorted(g["convergence"]):
        v = g["convergence"][c]
        sw = v.get("S_window")
        w(f"| {c} | {v['window_samples']} | {(v['Nu_pct'] or 0):.5f} | "
          f"{(v['S_abs'] or 0):.6f} | {(v['Uy_pct'] or 0):.5f} | "
          f"{('%.4f - %.4f' % (sw[0], sw[1])) if sw else '-'} | "
          f"**{'CONVERGED' if v['converged'] else 'REFUSED: ' + ','.join(v['failed'])}** |")

    # ---- near-identities ----------------------------------------------------
    w("\n## Reported, never gated: heat balance, y+, wall alphat\n")
    w("Heat balance on a sealed cavity is a **near-identity** "
      "(`VERIFICATION_CHARTER.md:106-111`) and is counted toward no verdict.\n")
    w("| case | model | Nu hot | Nu cold | closure % | y+ max | wall alphat/alpha |")
    w("| --- | --- | ---: | ---: | ---: | ---: | ---: |")
    for c, v in d["near_identities_REPORTED_NEVER_GATED"].items():
        w(f"| {c} | {v['model']} | {v['Nu_hot']:.4f} | {v['Nu_cold']:.4f} | "
          f"{v['heat_balance_pct']:.4f} | {v['yplus_max']:.3f} | "
          f"{v['wall_alphat_over_alpha']:.3g} |")

    # ---- cost ---------------------------------------------------------------
    c = d["cost"]
    w("\n## Cost, measured\n")
    w("| case | iterations | solver ExecutionTime (core-min) | wall (core-min) |")
    w("| --- | ---: | ---: | ---: |")
    for k in sorted(c["per_case"]):
        v = c["per_case"][k]
        w(f"| {k} | {(v['iterations'] or 0):.0f} | {v['core_minutes']:.2f} | "
          f"{v['wall_seconds']/60.0:.2f} |")
    w(f"| **pilots** | 2000 | **{c['pilots_core_minutes']:.2f}** | |")
    w(f"| **TOTAL** | | **{c['total_core_minutes']:.1f}** | "
      f"**{c['total_wall_core_minutes']:.1f}** |")
    w(f"\n**{c['total_core_minutes']:.1f} core-minutes = "
      f"{c['total_core_minutes']/60.0:.2f} core-hours = "
      f"${c['total_usd']:.3f}** at ${c['rate_usd_per_core_hour']} per core-hour.\n")

    # ---- mutation -----------------------------------------------------------
    mut = g["mutation_control"]
    bad = [m for m in mut if not (m["reachable_PASS"] and m["reachable_FAIL"])]
    w("\n## Mutation control\n")
    w(f"Every graded row re-graded against a mutated reference. "
      f"{len(mut)} row-checks; **{len(bad)}** rows not reachable in both "
      f"directions. every_row_reachable_both_ways = "
      f"**{g['every_row_reachable_both_ways']}**\n")
    if bad:
        w("| model | Ra | row | PASS reachable | FAIL reachable |")
        w("| --- | --- | --- | --- | --- |")
        for m in bad:
            w(f"| {m['model']} | {m['rung']} | {m['tag']} | "
              f"{m['reachable_PASS']} | {m['reachable_FAIL']} |")

    open(os.path.join(HERE, "REPORT_TABLES.md"), "w").write("\n".join(L) + "\n")
    print(f"wrote REPORT_TABLES.md, {len(L)} lines")
    return 0


if __name__ == "__main__":
    sys.exit(main())
